/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Poisson.CompensatedProfile

/-!
# A representative of the compensated integral of a mark profile for a sub-σ-algebra

The compensated step integral of a simple mark profile is a linear combination of the counts of
the Poisson random measure on the step times the profile's mark sets, so it is measurable for
the σ-algebra those counts generate. The elements of `L²(P)` that are almost everywhere equal to
an `m`-strongly measurable function form a closed subspace, so the `L²(P)` limit defining the
compensated integral over a step of a square-integrable mark profile has an `m`-strongly
measurable representative whenever the approximating compensated step integrals have one.

## Main definitions

* `LevyStochCalc.Poisson.compensatedProfileRepr` — a representative, for a σ-algebra on the
  sample space, of the compensated integral of a mark profile over a step.

## Main statements

* `LevyStochCalc.Poisson.SimpleProfile.stronglyMeasurable_stepIntegral_regionSigma` — the
  compensated step integral of a simple mark profile is strongly measurable for the σ-algebra
  generated by the counts on the step times its mark sets.
* `LevyStochCalc.Poisson.aestronglyMeasurable_compensatedProfile` — the compensated integral of
  a mark profile over a step is almost everywhere equal to an `m`-strongly measurable function
  when the approximating compensated step integrals are.
* `LevyStochCalc.Poisson.compensatedProfileRepr_ae_eq` — the representative agrees almost
  everywhere with the compensated integral.
* `LevyStochCalc.Poisson.stronglyMeasurable_compensatedProfileRepr` — strong measurability of
  the representative for the σ-algebra it is taken over.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped NNReal ENNReal

namespace LevyStochCalc.Poisson

universe u v

variable {Ω : Type u} (m : MeasurableSpace Ω) [mΩ : MeasurableSpace Ω] {E : Type v}
  [MeasurableSpace E] {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

/-! ### The simple case -/

/-- The compensated step integral of a simple mark profile is strongly measurable for the
σ-algebra generated by the counts of the Poisson random measure on the step times the profile's
mark sets. -/
theorem SimpleProfile.stronglyMeasurable_stepIntegral_regionSigma (N : PoissonRandomMeasure P ν)
    (G : SimpleProfile E ν) (a b : ℝ) :
    StronglyMeasurable[⨆ k, MeasurableSpace.comap
      (fun ω => N.N ω (Set.Ioc a b ×ˢ G.B k)) inferInstance] (G.stepIntegral N a b) := by
  have hk : ∀ k : Fin G.K, Measurable[⨆ k, MeasurableSpace.comap
      (fun ω => N.N ω (Set.Ioc a b ×ˢ G.B k)) inferInstance]
      (fun ω => N.N ω (Set.Ioc a b ×ˢ G.B k)) := fun k =>
    Measurable.mono (measurable_iff_comap_le.2 le_rfl)
      (le_iSup (fun k : Fin G.K => MeasurableSpace.comap
        (fun ω => N.N ω (Set.Ioc a b ×ˢ G.B k)) inferInstance) k) le_rfl
  have hrw : G.stepIntegral N a b = fun ω => ∑ k, G.c k
      * ((N.N ω (Set.Ioc a b ×ˢ G.B k)).toReal
        - (referenceIntensity ν (Set.Ioc a b ×ˢ G.B k)).toReal) := rfl
  refine Measurable.stronglyMeasurable ?_
  rw [hrw]
  exact Finset.measurable_sum _ fun k _ =>
    (((hk k).ennreal_toReal).sub measurable_const).const_mul _

/-! ### The limit case -/

/-- The compensated integral over a step of a square-integrable mark profile is almost
everywhere equal to an `m`-strongly measurable function whenever the compensated step integrals
of an approximating sequence of simple mark profiles are. -/
theorem aestronglyMeasurable_compensatedProfile (hm : m ≤ mΩ) (N : PoissonRandomMeasure P ν)
    {f : E → ℝ} (hf : MemLp f 2 ν) {a b : ℝ} (ha : 0 ≤ a) (hab : a ≤ b)
    (G : ℕ → SimpleProfile E ν)
    (hG : Tendsto (fun n => eLpNorm (fun e => (G n).toFun e - f e) 2 ν) atTop (nhds 0))
    (hGm : ∀ n, AEStronglyMeasurable[m] ((G n).stepIntegral N a b) P) :
    AEStronglyMeasurable[m] (compensatedProfile N f a b) P := by
  set u : ℕ → Lp ℝ 2 P := fun n => ((G n).memLp_stepIntegral N ha b).toLp _
  set v : Lp ℝ 2 P := (memLp_compensatedProfile N f a b).toLp _
  have hcoeu : ∀ n, ⇑(u n) =ᵐ[P] (G n).stepIntegral N a b :=
    fun n => MemLp.coeFn_toLp ((G n).memLp_stepIntegral N ha b)
  have hcoev : ⇑v =ᵐ[P] compensatedProfile N f a b :=
    MemLp.coeFn_toLp (memLp_compensatedProfile N f a b)
  have hmem : ∀ n, u n ∈ {h : Lp ℝ 2 P | AEStronglyMeasurable[m] (h : Ω → ℝ) P} :=
    fun n => (hGm n).congr (hcoeu n).symm
  have hlim : Tendsto u atTop (nhds v) := by
    rw [Lp.tendsto_Lp_iff_tendsto_eLpNorm']
    have heq : ∀ n, eLpNorm (⇑(u n) - ⇑v) 2 P
        = eLpNorm (fun ω => (G n).stepIntegral N a b ω - compensatedProfile N f a b ω) 2 P := by
      intro n
      refine eLpNorm_congr_ae ?_
      filter_upwards [hcoeu n, hcoev] with ω h1 h2
      simp [Pi.sub_apply, h1, h2]
    simp_rw [heq]
    exact tendsto_stepIntegral_compensatedProfile N hf ha hab G hG
  exact ((isClosed_aestronglyMeasurable hm).mem_of_tendsto hlim
    (Eventually.of_forall hmem)).congr hcoev

/-! ### The representative -/

open scoped Classical in
/-- A representative, for a σ-algebra `m` on the sample space, of the compensated integral over
a step of a square-integrable mark profile: an `m`-strongly measurable function almost everywhere
equal to `compensatedProfile N f a b`. Where the compensated integral has no `m`-strongly
measurable representative the value is the compensated integral itself. -/
noncomputable def compensatedProfileRepr (N : PoissonRandomMeasure P ν) (f : E → ℝ) (a b : ℝ) :
    Ω → ℝ :=
  if h : ∃ J : Ω → ℝ, StronglyMeasurable[m] J ∧ J =ᵐ[P] compensatedProfile N f a b
    then h.choose else compensatedProfile N f a b

/-- The representative agrees almost everywhere with the compensated integral of the mark
profile over the step. -/
theorem compensatedProfileRepr_ae_eq (N : PoissonRandomMeasure P ν) (f : E → ℝ) (a b : ℝ) :
    compensatedProfileRepr m N f a b =ᵐ[P] compensatedProfile N f a b := by
  classical
  by_cases h : ∃ J : Ω → ℝ, StronglyMeasurable[m] J ∧ J =ᵐ[P] compensatedProfile N f a b
  · rw [show compensatedProfileRepr m N f a b = h.choose from dif_pos h]
    exact h.choose_spec.2
  · rw [show compensatedProfileRepr m N f a b = compensatedProfile N f a b from dif_neg h]

/-- The representative of the compensated integral over a step of a square-integrable mark
profile is `m`-strongly measurable whenever the compensated step integrals of an approximating
sequence of simple mark profiles are almost everywhere equal to `m`-strongly measurable
functions. -/
theorem stronglyMeasurable_compensatedProfileRepr (hm : m ≤ mΩ) (N : PoissonRandomMeasure P ν)
    {f : E → ℝ} (hf : MemLp f 2 ν) {a b : ℝ} (ha : 0 ≤ a) (hab : a ≤ b)
    (G : ℕ → SimpleProfile E ν)
    (hG : Tendsto (fun n => eLpNorm (fun e => (G n).toFun e - f e) 2 ν) atTop (nhds 0))
    (hGm : ∀ n, AEStronglyMeasurable[m] ((G n).stepIntegral N a b) P) :
    StronglyMeasurable[m] (compensatedProfileRepr m N f a b) := by
  classical
  obtain ⟨J, hJm, hJae⟩ :=
    aestronglyMeasurable_compensatedProfile m hm N hf ha hab G hG hGm
  have h : ∃ J : Ω → ℝ, StronglyMeasurable[m] J ∧ J =ᵐ[P] compensatedProfile N f a b :=
    ⟨J, hJm, hJae.symm⟩
  rw [show compensatedProfileRepr m N f a b = h.choose from dif_pos h]
  exact h.choose_spec.1

end LevyStochCalc.Poisson
