/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.CharCylinder
import LevyStochCalc.Poisson.NaturalFiltration

/-!
# Cylinder characters of a Poisson random measure

The natural filtration of a Poisson random measure at a time `T` is generated by the counts on
the measurable subsets of `(-∞, T] × E`. Those counts take values in `ℝ≥0∞`, which is
order-isomorphic to the unit interval, so they carry the same information as real random
variables and the characters of finitely many of them separate the integrable variables the
filtration measures.
-/

open MeasureTheory Complex
open scoped RealInnerProductSpace NNReal ENNReal

namespace LevyStochCalc.Poisson

universe u v

/-- The extended nonnegative reals as a measurable subspace of the unit interval. -/
noncomputable def encodeEquiv : ℝ≥0∞ ≃ᵐ Set.Icc (0 : ℝ) 1 where
  toEquiv := ENNReal.orderIsoUnitIntervalBirational.toEquiv
  measurable_toFun := ENNReal.orderIsoUnitIntervalBirational.monotone.measurable
  measurable_invFun := ENNReal.orderIsoUnitIntervalBirational.symm.monotone.measurable

/-- A real-valued encoding of the extended nonnegative reals. -/
noncomputable def encode (x : ℝ≥0∞) : ℝ := (encodeEquiv x : ℝ)

theorem measurableEmbedding_encode : MeasurableEmbedding encode :=
  (MeasurableEmbedding.subtype_coe measurableSet_Icc).comp encodeEquiv.measurableEmbedding

/-- The encoding is injective, so it generates the same σ-algebra as the count itself. -/
theorem comap_encode {α : Type*} [MeasurableSpace α] (X : α → ℝ≥0∞) :
    MeasurableSpace.comap (fun a => encode (X a)) inferInstance
      = MeasurableSpace.comap X inferInstance := by
  have hcomp : (fun a => encode (X a)) = encode ∘ X := rfl
  rw [hcomp, ← MeasurableSpace.comap_comp]
  congr 1
  refine le_antisymm ?_ ?_
  · rintro s ⟨t, ht, rfl⟩
    exact measurableEmbedding_encode.measurable ht
  · intro s hs
    exact ⟨encode '' s, measurableEmbedding_encode.measurableSet_image' hs,
      measurableEmbedding_encode.injective.preimage_image s⟩

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

/-- The measurable subsets of the past of `T`, as an index type for the generating counts. -/
abbrev PastSet (E : Type v) [MeasurableSpace E] (T : ℝ) : Type v :=
  {C : Set (ℝ × E) // C ⊆ Set.Iic T ×ˢ Set.univ ∧ MeasurableSet C}

/-- The natural filtration at `T` is generated by the encoded counts on the past sets. -/
theorem naturalFiltration_eq_iSup_comap (N : PoissonRandomMeasure P ν) (T : ℝ) :
    naturalFiltration N T
      = ⨆ B : PastSet E T,
          MeasurableSpace.comap (fun ω => encode (N.N ω (B : Set (ℝ × E)))) inferInstance := by
  rw [naturalFiltration_seq_eq]
  refine le_antisymm (iSup₂_le fun B hB => ?_) (iSup_le fun B => ?_)
  · exact le_iSup_of_le ⟨B, hB⟩ (comap_encode fun ω => N.N ω B).ge
  · exact le_iSup₂_of_le (B : Set (ℝ × E)) B.2
      (comap_encode fun ω => N.N ω (B : Set (ℝ × E))).le

/-- **Cylinder characters of a Poisson random measure separate.** An integrable weight measurable
for the natural filtration at `T`, integrating to zero against every character of every finite
family of past counts, vanishes almost everywhere. -/
theorem ae_eq_zero_of_integral_char_cylinder (N : PoissonRandomMeasure P ν) (T : ℝ)
    {Z : Ω → ℂ} (hZ : Integrable Z P)
    (hZm : StronglyMeasurable[naturalFiltration N T] Z)
    (h : ∀ (F : Finset (PastSet E T)) (w : F → ℝ),
      ∫ ω, Complex.exp
          ((∑ B : F, encode (N.N ω ((B : PastSet E T) : Set (ℝ × E))) * w B : ℝ) * Complex.I)
        * Z ω ∂P = 0) :
    Z =ᵐ[P] 0 := by
  refine Probability.ae_eq_zero_of_integral_char_cylinder_eq_zero
    (Y := fun B : PastSet E T => fun ω => encode (N.N ω (B : Set (ℝ × E))))
    (fun B => measurableEmbedding_encode.measurable.comp
      (N.measurable_eval (B.2).2)) ((naturalFiltration N).le T)
    (naturalFiltration_eq_iSup_comap N T) hZ hZm ?_
  intro F w
  refine Eq.trans ?_ (h F w)
  refine integral_congr_ae (Filter.Eventually.of_forall fun ω => ?_)
  simp [RCLike.inner_apply, mul_comm]

end LevyStochCalc.Poisson
