/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Poisson.PastFutureIndependence
import LevyStochCalc.Probability.ComapTuple
import LevyStochCalc.Probability.IndepJoin
import LevyStochCalc.Probability.IndepLimit

/-!
# Poisson random measures with respect to a filtration

`IsPoissonFiltration N ℱ` says that the counts of the Poisson random measure `N` on regions
of the past `(-∞, t] × E` are `ℱ t`-measurable and that, for `0 ≤ s`, the σ-algebra `ℱ s` is
independent of the σ-algebra generated by the counts on *all* measurable regions of the future
`(s, ∞) × E`. Independence of `ℱ s` from the count on a single strip `(s, t] × A` of finite
intensity is the special case `IsPoissonFiltration.indep`. The natural filtration of `N` is an
instance, a smaller filtration to which `N` is adapted is one, and so is the right-continuous
version `ℱ₊`: for a finite family of future regions `D`, the counts `N(D ∩ ((r, ∞) × E))` are
jointly independent of `ℱ r ⊇ ℱ₊ s` and increase to `N(D)` as `r ↓ s`.
-/

open MeasureTheory ProbabilityTheory Filter Topology
open scoped ENNReal

namespace LevyStochCalc.Poisson

universe u v

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

/-- `N` is a Poisson random measure for the filtration `ℱ`: its counts on measurable regions
of `(-∞, t] × E` are `ℱ t`-measurable, and for `0 ≤ s` the σ-algebra `ℱ s` is independent of
the σ-algebra generated by the counts on the measurable regions of `(s, ∞) × E`. -/
structure IsPoissonFiltration (N : PoissonRandomMeasure P ν)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›) : Prop where
  measurable : ∀ ⦃t : ℝ⦄ ⦃B : Set (ℝ × E)⦄, B ⊆ Set.Iic t ×ˢ Set.univ → MeasurableSet B →
    Measurable[ℱ t] (fun ω => N.N ω B)
  indep_future : ∀ ⦃s : ℝ⦄, 0 ≤ s →
    Indep (ℱ s) (⨆ D ∈ {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D},
      MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P

/-- The σ-algebra `ℱ s` is independent of the count on a future strip `(s, t] × A` of finite
mark measure. -/
theorem IsPoissonFiltration.indep {N : PoissonRandomMeasure P ν}
    {ℱ : Filtration ℝ ‹MeasurableSpace Ω›} (h : IsPoissonFiltration N ℱ) :
    ∀ ⦃s t : ℝ⦄, 0 ≤ s → s < t → ∀ ⦃A : Set E⦄, MeasurableSet A → ν A ≠ ⊤ →
      Indep (ℱ s) (MeasurableSpace.comap (fun ω => N.N ω (Set.Ioc s t ×ˢ A)) inferInstance) P := by
  intro s t hs _ A hA _
  exact indep_of_indep_of_le_right (h.indep_future hs)
    (le_iSup₂_of_le (Set.Ioc s t ×ˢ A)
      ⟨Set.prod_mono Set.Ioc_subset_Ioi_self (Set.subset_univ A), measurableSet_Ioc.prod hA⟩ le_rfl)

/-- A Poisson random measure is one for its natural filtration. -/
theorem isPoissonFiltration_natural (N : PoissonRandomMeasure P ν) :
    IsPoissonFiltration N (naturalFiltration N) where
  measurable _ _ hB hBm := measurable_random_measure_of_le N hB hBm
  indep_future _ _ := N.indep_naturalFiltration_future

/-- A Poisson random measure for `ℱ` is one for any smaller filtration to which it is adapted. -/
theorem IsPoissonFiltration.of_le {N : PoissonRandomMeasure P ν}
    {ℱ 𝒢 : Filtration ℝ ‹MeasurableSpace Ω›} (h : IsPoissonFiltration N ℱ) (hle : 𝒢 ≤ ℱ)
    (hadapted : ∀ ⦃t : ℝ⦄ ⦃B : Set (ℝ × E)⦄, B ⊆ Set.Iic t ×ˢ Set.univ → MeasurableSet B →
      Measurable[𝒢 t] (fun ω => N.N ω B)) :
    IsPoissonFiltration N 𝒢 where
  measurable := hadapted
  indep_future _ hs := indep_of_indep_of_le_left (h.indep_future hs) (hle _)

/-- A Poisson random measure for `ℱ` is one for the right-continuous filtration `ℱ₊`. -/
theorem IsPoissonFiltration.rightCont {N : PoissonRandomMeasure P ν}
    {ℱ : Filtration ℝ ‹MeasurableSpace Ω›} (h : IsPoissonFiltration N ℱ) :
    IsPoissonFiltration N ℱ.rightCont where
  measurable _ _ hB hBm := (h.measurable hB hBm).mono (ℱ.le_rightCont _) le_rfl
  indep_future := by
    classical
    intro s hs
    obtain ⟨r, hr_anti, hr_gt, hr_tend⟩ := exists_seq_strictAnti_tendsto s
    have hle : ∀ k, ℱ.rightCont s ≤ ℱ (r k) := fun k => by
      rw [Filtration.rightCont_eq_of_neBot_nhdsGT ℱ s]
      exact iInf₂_le (r k) (hr_gt k)
    have hfin : ∀ (n : ℕ) (g : Fin n → Set (ℝ × E)),
        (∀ i, g i ∈ {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D}) →
        Indep (ℱ.rightCont s)
          (⨆ i, MeasurableSpace.comap (fun ω => N.N ω (g i)) inferInstance) P := by
      intro n g hg
      have hcut : ∀ (k : ℕ) (i : Fin n), MeasurableSet (g i ∩ Set.Ioi (r k) ×ˢ Set.univ) :=
        fun k i => (hg i).2.inter (measurableSet_Ioi.prod MeasurableSet.univ)
      have hYcomap : MeasurableSpace.comap (fun ω (i : Fin n) => N.N ω (g i)) inferInstance
          = ⨆ i, MeasurableSpace.comap (fun ω => N.N ω (g i)) inferInstance :=
        Probability.comap_pi_eq_iSup fun i ω => N.N ω (g i)
      rw [← hYcomap]
      refine Probability.indep_comap_of_tendsto_ae (ℱ.rightCont.le s)
        (fun k => measurable_pi_lambda _ fun i => N.measurable_eval (hcut k i))
        (measurable_pi_lambda _ fun i => N.measurable_eval (hg i).2) (fun k => ?_) ?_
      · have hkcomap : MeasurableSpace.comap
              (fun ω (i : Fin n) => N.N ω (g i ∩ Set.Ioi (r k) ×ˢ Set.univ)) inferInstance
            = ⨆ i, MeasurableSpace.comap
              (fun ω => N.N ω (g i ∩ Set.Ioi (r k) ×ˢ Set.univ)) inferInstance :=
          Probability.comap_pi_eq_iSup fun i ω => N.N ω (g i ∩ Set.Ioi (r k) ×ˢ Set.univ)
        rw [hkcomap]
        refine indep_of_indep_of_le_left (indep_of_indep_of_le_right
          (h.indep_future (hs.trans (hr_gt k).le)) ?_) (hle k)
        exact iSup_le fun i => le_iSup₂_of_le (g i ∩ Set.Ioi (r k) ×ˢ Set.univ)
          ⟨Set.inter_subset_right, hcut k i⟩ le_rfl
      · refine ae_of_all _ fun ω => tendsto_pi_nhds.2 fun i => ?_
        have hmono : Monotone fun k => g i ∩ Set.Ioi (r k) ×ˢ Set.univ := fun a b hab =>
          Set.inter_subset_inter_right _
            (Set.prod_mono (Set.Ioi_subset_Ioi (hr_anti.antitone hab)) le_rfl)
        have hunion : ⋃ k, g i ∩ Set.Ioi (r k) ×ˢ Set.univ = g i := by
          refine Set.Subset.antisymm (Set.iUnion_subset fun _ => Set.inter_subset_left)
            fun x hx => ?_
          obtain ⟨k, hk⟩ := (hr_tend.eventually (eventually_lt_nhds ((hg i).1 hx).1)).exists
          exact Set.mem_iUnion.2 ⟨k, hx, hk, Set.mem_univ _⟩
        have hlim := tendsto_measure_iUnion_atTop (μ := N.N ω) hmono
        rwa [hunion] at hlim
    have hsup : (⨆ D ∈ {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D},
          MeasurableSpace.comap (fun ω => N.N ω D) inferInstance)
        = ⨆ D : {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D},
            MeasurableSpace.comap (fun ω => N.N ω (D : Set (ℝ × E))) inferInstance :=
      le_antisymm
        (iSup₂_le fun D hD => le_iSup (fun D : {D : Set (ℝ × E) |
            D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D} =>
          MeasurableSpace.comap (fun ω => N.N ω (D : Set (ℝ × E))) inferInstance) ⟨D, hD⟩)
        (iSup_le fun D => le_iSup₂_of_le (D : Set (ℝ × E)) D.2 le_rfl)
    rw [hsup]
    refine (Probability.indep_iSup_of_finset
      (fun D : {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D} =>
        (N.measurable_eval D.2.2).comap_le) (ℱ.rightCont.le s) fun S => ?_).symm
    exact indep_of_indep_of_le_left
      (hfin S.card (fun i => ((S.equivFin.symm i).1 : Set (ℝ × E)))
        (fun i => (S.equivFin.symm i).1.2)).symm
      (iSup₂_le fun D hD => le_iSup_of_le (S.equivFin ⟨D, hD⟩) (by simp))

end LevyStochCalc.Poisson
