/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Poisson.RandomMeasure
import LevyStochCalc.Poisson.RegionIndependence

/-!
# Independent scattering in σ-algebra form

A Poisson random measure scatters independently: the counts on any countable pairwise-disjoint
family of regions are jointly independent (`PoissonRandomMeasure.independent_disjoint`). The
σ-algebra form of the same property — the σ-algebra generated by the counts on *all* measurable
regions disjoint from `D` is independent of the count on `D` — is the raw-random-measure statement
of `LevyStochCalc.Poisson.RegionIndependence`, specialised here to the structure's fields.

## Main statements

* `PoissonRandomMeasure.indep_iSup_comap_of_disjoint` — the finite-family case.
* `PoissonRandomMeasure.indep_of_disjoint_region` — the σ-algebra form.
* `PoissonRandomMeasure.indep_iSup_comap_of_disjoint_pair`,
  `PoissonRandomMeasure.indep_of_disjoint_region_pair` — the two-sided versions, for a finite
  family of regions on each side.
-/

universe u v w

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace LevyStochCalc.Poisson

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

namespace PoissonRandomMeasure

variable (N : PoissonRandomMeasure.{u, v, w} P ν)

/-- The counts on finitely many measurable regions disjoint from `D` generate a σ-algebra
independent of the count on `D`. -/
theorem indep_iSup_comap_of_disjoint {n : ℕ} {D : Set (ℝ × E)}
    (hD : MeasurableSet D) (C : Fin n → Set (ℝ × E)) (hC : ∀ i, MeasurableSet (C i))
    (hCD : ∀ i, Disjoint (C i) D) :
    Indep (⨆ i, MeasurableSpace.comap (fun ω => N.N ω (C i)) inferInstance)
      (MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P :=
  indep_iSup_comap_of_disjoint_of_indep (fun hB => N.measurable_eval hB)
    (fun B hB hd => (N.independent_disjoint (fun o : ULift.{w} _ => B o.down)
      (fun o => hB o.down) fun o o' h => hd fun h' => h (by rw [ULift.ext_iff]; exact h'))
        |>.of_precomp (g := ULift.down) ULift.down_surjective)
    hD C hC hCD

/-- **Independent scattering, σ-algebra form**: the σ-algebra generated by the counts on all
measurable regions disjoint from `D` is independent of the count on `D`. -/
theorem indep_of_disjoint_region {D : Set (ℝ × E)} (hD : MeasurableSet D) :
    Indep (⨆ C ∈ {C : Set (ℝ × E) | Disjoint C D ∧ MeasurableSet C},
        MeasurableSpace.comap (fun ω => N.N ω C) inferInstance)
      (MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P :=
  indep_of_disjoint_region_of_indep (fun hB => N.measurable_eval hB)
    (fun B hB hd => (N.independent_disjoint (fun o : ULift.{w} _ => B o.down)
      (fun o => hB o.down) fun o o' h => hd fun h' => h (by rw [ULift.ext_iff]; exact h'))
        |>.of_precomp (g := ULift.down) ULift.down_surjective)
    hD

/-- The counts on two finite families of measurable regions whose unions are disjoint generate
independent σ-algebras. -/
theorem indep_iSup_comap_of_disjoint_pair {n p : ℕ} (C : Fin n → Set (ℝ × E))
    (D : Fin p → Set (ℝ × E)) (hC : ∀ i, MeasurableSet (C i)) (hD : ∀ j, MeasurableSet (D j))
    (hCD : ∀ i j, Disjoint (C i) (D j)) :
    Indep (⨆ i, MeasurableSpace.comap (fun ω => N.N ω (C i)) inferInstance)
      (⨆ j, MeasurableSpace.comap (fun ω => N.N ω (D j)) inferInstance) P :=
  indep_iSup_comap_of_disjoint_families (fun hB => N.measurable_eval hB)
    (fun B hB hd => (N.independent_disjoint (fun o : ULift.{w} _ => B o.down)
      (fun o => hB o.down) fun o o' h => hd fun h' => h (by rw [ULift.ext_iff]; exact h'))
        |>.of_precomp (g := ULift.down) ULift.down_surjective)
    C D hC hD hCD

/-- The σ-algebra generated by the counts on all measurable regions disjoint from a finite family
`D` is independent of the counts on `D`. -/
theorem indep_of_disjoint_region_pair {p : ℕ} (D : Fin p → Set (ℝ × E))
    (hD : ∀ j, MeasurableSet (D j)) :
    Indep (⨆ C ∈ {C : Set (ℝ × E) | (∀ j, Disjoint C (D j)) ∧ MeasurableSet C},
        MeasurableSpace.comap (fun ω => N.N ω C) inferInstance)
      (⨆ j, MeasurableSpace.comap (fun ω => N.N ω (D j)) inferInstance) P :=
  indep_of_disjoint_region_families (fun hB => N.measurable_eval hB)
    (fun B hB hd => (N.independent_disjoint (fun o : ULift.{w} _ => B o.down)
      (fun o => hB o.down) fun o o' h => hd fun h' => h (by rw [ULift.ext_iff]; exact h'))
        |>.of_precomp (g := ULift.down) ULift.down_surjective)
    D hD

end PoissonRandomMeasure

end LevyStochCalc.Poisson
