import LevyStochCalc.Poisson.RandomMeasure

/-!
# Natural filtration of a Poisson random measure

For a `PoissonRandomMeasure N` on `[0, ∞) × E` over `(Ω, P)`, the *natural
filtration* at time `t` is the σ-algebra generated by

  `{ N(B) : B ⊆ (-∞, t] × E, B measurable }`,

i.e., by the family of measure-evaluations on past time-rectangles. Mirrors
`LevyStochCalc.Brownian.Martingale.naturalFiltration` for Brownian motion.
The σ-algebra is exactly the one already appearing in
`PoissonRandomMeasure.joint_past_future_independent`; this file packages it
as a `MeasureTheory.Filtration ℝ m₀` so that `Martingale` claims can be
stated against it.
-/

namespace LevyStochCalc.Poisson

open MeasureTheory
open scoped NNReal ENNReal

universe u v
variable {Ω : Type u} [MeasurableSpace Ω]
variable {E : Type v} [MeasurableSpace E]

/-- The *natural filtration* of a Poisson random measure `N`. At time `t`
the σ-algebra is `⨆ B ⊆ Iic t × univ, σ(N(·, B))`. -/
noncomputable def naturalFiltration
    {P : Measure Ω} [IsProbabilityMeasure P]
    {ν : Measure E} [SigmaFinite ν]
    (N : PoissonRandomMeasure P ν) :
    MeasureTheory.Filtration ℝ ‹MeasurableSpace Ω› where
  seq t := ⨆ B ∈ { C : Set (ℝ × E) | C ⊆ Set.Iic t ×ˢ Set.univ ∧ MeasurableSet C },
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance
  mono' s t hst := by
    refine iSup_le fun B => iSup_le fun hB => ?_
    have hB_t : B ∈ { C : Set (ℝ × E) | C ⊆ Set.Iic t ×ˢ Set.univ ∧ MeasurableSet C } := by
      refine ⟨?_, hB.2⟩
      refine hB.1.trans ?_
      exact Set.prod_mono (Set.Iic_subset_Iic.mpr hst) (le_refl _)
    exact le_iSup_of_le B (le_iSup_of_le hB_t le_rfl)
  le' t := by
    refine iSup_le fun B => iSup_le fun hB => ?_
    intro u hu
    obtain ⟨v, hv, hvu⟩ := hu
    rw [← hvu]
    exact (N.measurable_eval hB.2) hv

/-- **Past-meas: each `N(·, B)` is `(naturalFiltration N)`-measurable at any
time `t` whose `Iic t × E` contains `B`.** Direct consequence of the
construction of `naturalFiltration`: the σ-algebra at time `t` is the
supremum (over past rectangles) of the comap σ-algebras. -/
lemma measurable_random_measure_of_le
    {P : Measure Ω} [IsProbabilityMeasure P]
    {ν : Measure E} [SigmaFinite ν]
    (N : PoissonRandomMeasure P ν)
    {t : ℝ} {B : Set (ℝ × E)}
    (hB_subset : B ⊆ Set.Iic t ×ˢ Set.univ) (hB_meas : MeasurableSet B) :
    Measurable[(naturalFiltration N).seq t] (fun ω => N.N ω B) := by
  refine Measurable.of_comap_le (m₁ := (naturalFiltration N).seq t) ?_
  show MeasurableSpace.comap (fun ω => N.N ω B) inferInstance ≤ (naturalFiltration N).seq t
  exact le_iSup_of_le B (le_iSup_of_le ⟨hB_subset, hB_meas⟩ le_rfl)

/-- **Filtration σ-algebra equals the supremum used in `joint_past_future_independent`.**
This is `rfl`-level: the construction picks the same iSup as the structural
hypothesis on `PoissonRandomMeasure`. -/
lemma naturalFiltration_seq_eq
    {P : Measure Ω} [IsProbabilityMeasure P]
    {ν : Measure E} [SigmaFinite ν]
    (N : PoissonRandomMeasure P ν) (t : ℝ) :
    (naturalFiltration N).seq t =
      ⨆ B ∈ { C : Set (ℝ × E) | C ⊆ Set.Iic t ×ˢ Set.univ ∧ MeasurableSet C },
        MeasurableSpace.comap (fun ω => N.N ω B) inferInstance := rfl

end LevyStochCalc.Poisson
