/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Poisson.IndependentScattering
import LevyStochCalc.Poisson.NaturalFiltration

/-!
# Past/future independence of a Poisson random measure, joint form

For a Poisson random measure `N` and two disjoint regions `R₁`, `R₂` of the time-mark space
`ℝ × E`, the σ-algebra generated by the counts on all measurable subsets of `R₁` is independent
of the σ-algebra generated by the counts on all measurable subsets of `R₂`; neither region is
required to be measurable. Taking `R₁ = (-∞, s] × E` and `R₂ = (s, ∞) × E` gives the past/future
independence of the natural filtration in joint form: the σ-algebra at time `s` is independent
of the σ-algebra generated by the counts on *all* measurable regions of the future, rather than
of the count on a single strip `(s, t] × A`.

## Main statements

* `PoissonRandomMeasure.indep_iSup_comap_of_disjoint_regions` — two disjoint regions.
* `PoissonRandomMeasure.indep_naturalFiltration_future` — past and future of the natural
  filtration.
-/

universe u v w

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Poisson

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

namespace PoissonRandomMeasure

/-- The counts on the measurable subsets of a region `R₁` generate a σ-algebra independent of
the one generated by the counts on the measurable subsets of a region `R₂` disjoint from `R₁`. -/
theorem indep_iSup_comap_of_disjoint_regions (N : PoissonRandomMeasure.{u, v, w} P ν)
    {R₁ R₂ : Set (ℝ × E)} (h : Disjoint R₁ R₂) :
    Indep (⨆ C ∈ {C : Set (ℝ × E) | C ⊆ R₁ ∧ MeasurableSet C},
        MeasurableSpace.comap (fun ω => N.N ω C) inferInstance)
      (⨆ D ∈ {D : Set (ℝ × E) | D ⊆ R₂ ∧ MeasurableSet D},
        MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P := by
  classical
  set 𝒞 := {C : Set (ℝ × E) | C ⊆ R₁ ∧ MeasurableSet C}
  set 𝒟 := {D : Set (ℝ × E) | D ⊆ R₂ ∧ MeasurableSet D}
  have hright : (⨆ D ∈ 𝒟, MeasurableSpace.comap (fun ω => N.N ω D) inferInstance)
      = ⨆ D : 𝒟, MeasurableSpace.comap (fun ω => N.N ω (D : Set (ℝ × E))) inferInstance :=
    le_antisymm
      (iSup₂_le fun D hD => le_iSup (fun D : 𝒟 =>
        MeasurableSpace.comap (fun ω => N.N ω (D : Set (ℝ × E))) inferInstance) ⟨D, hD⟩)
      (iSup_le fun D => le_iSup₂_of_le (D : Set (ℝ × E)) D.2 le_rfl)
  rw [hright]
  refine Indep.symm (Probability.indep_iSup_of_finset
    (fun D => (N.measurable_eval D.2.2).comap_le)
    (iSup₂_le fun C hC => (N.measurable_eval hC.2).comap_le) fun S => ?_)
  refine indep_of_indep_of_le_left (indep_of_indep_of_le_right
    (N.indep_of_disjoint_region_pair
      (fun i : Fin S.card => ((S.equivFin.symm i : 𝒟) : Set (ℝ × E)))
      (fun i => (S.equivFin.symm i).1.2.2)).symm ?_) ?_
  · exact iSup₂_le fun C hC =>
      le_iSup₂_of_le C ⟨fun j => h.mono hC.1 (S.equivFin.symm j).1.2.1, hC.2⟩ le_rfl
  · exact iSup₂_le fun D hD => le_iSup_of_le (S.equivFin ⟨D, hD⟩) (by simp)

/-- The σ-algebra of the natural filtration at time `s` is independent of the σ-algebra
generated by the counts on all measurable regions contained in `(s, ∞) × E`. -/
theorem indep_naturalFiltration_future (N : PoissonRandomMeasure.{u, v, w} P ν) {s : ℝ} :
    Indep (naturalFiltration N s)
      (⨆ D ∈ {D : Set (ℝ × E) | D ⊆ Set.Ioi s ×ˢ Set.univ ∧ MeasurableSet D},
        MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P := by
  have hpast : naturalFiltration N s
      = ⨆ C ∈ {C : Set (ℝ × E) | C ⊆ Set.Iic s ×ˢ Set.univ ∧ MeasurableSet C},
          MeasurableSpace.comap (fun ω => N.N ω C) inferInstance := rfl
  rw [hpast]
  exact N.indep_iSup_comap_of_disjoint_regions
    (Set.disjoint_prod.mpr (Or.inl (Set.Iic_disjoint_Ioi le_rfl)))

end PoissonRandomMeasure

end LevyStochCalc.Poisson
