/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Basic

/-!
# Layer 0 substrate: Poisson random measure on `[0, ∞) × E`

A *Poisson random measure* on the time-space `[0, ∞) × E` (where `E` is a
measurable mark space with σ-finite intensity `ν`), defined over a
probability space `(Ω, P)`, is a measurable family

  `N : Ω → Measure (ℝ × E)`

with the following properties:

* For each measurable `B ⊆ ℝ × E` with `(volume.restrict [0,∞) ⊗ ν)(B) < ∞`,
  `N(·, B) ~ Poisson` with mean equal to that intensity.
* For any pairwise-disjoint family of such sets, the random variables
  `(N(·, B_i))_i` are independent under `P`.

This is the time-aware structure required for the *compensated* integral
`∫_0^t ∫_E φ(s, e) Ñ(ds, de)` to be well-defined.

## References

* Applebaum, *Lévy Processes and Stochastic Calculus*, Cambridge 2009, §2.3, Thm 2.3.1.
* Ikeda–Watanabe, *Stochastic Differential Equations and Diffusion Processes*,
  North-Holland 1989, §I.8.
* Sato, *Lévy Processes and Infinitely Divisible Distributions*,
  Cambridge 1999, §19.

## Status

Phase 2 spec: structure fields wired to real Mathlib types on the `ℝ × E`
time-space. The intensity is `volume.restrict (Set.Ici 0) ⊗ ν` (Lebesgue
restricted to `[0, ∞)` tensor `ν` on the mark space).

Existence theorem `PoissonRandomMeasure.exists_of_sigmaFinite` carries the
substantive `sorry` (Ionescu-Tulcea construction).
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace LevyStochCalc.Poisson

universe u v

variable {Ω : Type u} [MeasurableSpace Ω]
variable {E : Type v} [MeasurableSpace E]

/-- The Poisson distribution `Poisson(μ)` viewed as a measure on `ℝ≥0∞` (via
the natural inclusion `ℕ ↪ ℝ≥0∞`). Convenience for stating
`P.map (N · A) = …` since `N(·, A) : Ω → ℝ≥0∞` (an extended-real count). -/
noncomputable def poissonMeasureENN (μ : ℝ≥0) : Measure ℝ≥0∞ :=
  (ProbabilityTheory.poissonMeasure μ).map (fun n : ℕ => (n : ℝ≥0∞))

/-- The reference intensity on `ℝ × E`: Lebesgue on `[0, ∞)` tensor `ν` on
the mark space. -/
noncomputable def referenceIntensity {E : Type v} [MeasurableSpace E]
    (ν : Measure E) : Measure (ℝ × E) :=
  (volume.restrict (Set.Ici (0 : ℝ))).prod ν

/-- A *Poisson random measure on `[0, ∞) × E`* with intensity
`volume.restrict [0,∞) ⊗ ν`, defined over a probability space `(Ω, P)`. -/
structure PoissonRandomMeasure
    (P : Measure Ω) [IsProbabilityMeasure P]
    (ν : Measure E) [SigmaFinite ν] where
  /-- The underlying ω-indexed family of measures on `ℝ × E`. -/
  N : Ω → Measure (ℝ × E)
  /-- For each measurable `B ⊆ ℝ × E`, the map `ω ↦ N(ω, B)` is measurable. -/
  measurable_eval : ∀ {B : Set (ℝ × E)}, MeasurableSet B →
    Measurable (fun ω => N ω B)
  /-- `N(·, B)` has `Poisson` law with mean `(referenceIntensity ν)(B)` under
  `P`, for every measurable `B` with finite intensity. -/
  poisson_law : ∀ {B : Set (ℝ × E)}, MeasurableSet B →
    referenceIntensity ν B ≠ ⊤ →
    P.map (fun ω => N ω B) = poissonMeasureENN (referenceIntensity ν B).toNNReal
  /-- For any pairwise-disjoint countable family of measurable subsets of
  `ℝ × E`, the family of evaluation random variables `(ω ↦ N(ω, B_i))_i` is
  independent under `P`. -/
  independent_disjoint :
    ∀ {ι : Type*} (B : ι → Set (ℝ × E)),
      (∀ i, MeasurableSet (B i)) →
      Pairwise (fun i j => Disjoint (B i) (B j)) →
      ProbabilityTheory.iIndepFun (fun (i : ι) (ω : Ω) => N ω (B i)) P
  /-- **σ-algebra-level past/future independence.** The σ-algebra generated by
  `{N(·, B) : B ⊆ (−∞, s] × E, B measurable}` (the "past at time `s`") is
  independent of `σ(N(·, (s, t] × A))` (a future increment).

  This is strictly stronger than `independent_disjoint` (which is iIndepFun
  for finite/countable families) and is needed to apply
  `MeasureTheory.condExp_indep_eq` in the compensated stochastic-integral
  proofs. For PRMs it follows from joint independence on disjoint subsets;
  packaged as a structural hypothesis in the same spirit as
  `BrownianMotion.joint_increment_independent`. -/
  joint_past_future_independent :
    ∀ {s t : ℝ}, 0 ≤ s → s < t → ∀ {A : Set E}, MeasurableSet A → ν A ≠ ⊤ →
      ProbabilityTheory.Indep
        (⨆ B ∈ { C : Set (ℝ × E) | C ⊆ Set.Iic s ×ˢ Set.univ ∧ MeasurableSet C },
          MeasurableSpace.comap (fun ω => N ω B) inferInstance)
        (MeasurableSpace.comap
          (fun ω => N ω (Set.Ioc s t ×ˢ A)) inferInstance)
        P

/-- The compensated random measure: `Ñ(B) := N(B) − ν̂(B)` where
`ν̂ := referenceIntensity ν`. Returns a real number when `ν̂(B) < ∞`. -/
noncomputable def PoissonRandomMeasure.compensated
    {P : Measure Ω} [IsProbabilityMeasure P]
    {ν : Measure E} [SigmaFinite ν]
    (N : PoissonRandomMeasure P ν) (B : Set (ℝ × E)) (ω : Ω) : ℝ :=
  (N.N ω B).toReal - (referenceIntensity ν B).toReal

/-- **Step 1: σ-finite decomposition of the intensity.** A σ-finite measure `ν`
on `E` decomposes as a sequence of pairwise-disjoint measurable sets each of
finite mass covering all of `E`. Built from `MeasureTheory.spanningSets` +
`Set.disjointed`. -/
lemma sigmaFinite_decomposition
    (E : Type v) [MeasurableSpace E] (ν : Measure E) [SigmaFinite ν] :
    ∃ s : ℕ → Set E,
      (∀ n, MeasurableSet (s n)) ∧
      Pairwise (fun i j => Disjoint (s i) (s j)) ∧
      (∀ n, ν (s n) < ⊤) ∧
      (⋃ n, s n) = Set.univ := by
  refine ⟨disjointed (MeasureTheory.spanningSets ν), ?_, ?_, ?_, ?_⟩
  · intro n
    exact MeasurableSet.disjointed (MeasureTheory.measurableSet_spanningSets ν) n
  · exact disjoint_disjointed _
  · intro n
    refine lt_of_le_of_lt ?_ (MeasureTheory.measure_spanningSets_lt_top ν n)
    exact MeasureTheory.measure_mono (disjointed_subset _ _)
  · rw [iUnion_disjointed]
    exact MeasureTheory.iUnion_spanningSets ν

/-- **CITED AXIOM: Poisson random measure construction.**

For every σ-finite intensity `ν` on a standard Borel space `E`, there exists a
probability space carrying a Poisson random measure with intensity
`volume.restrict [0,∞) ⊗ ν`.

**Reference**: Applebaum, D. *Lévy Processes and Stochastic Calculus*, 2nd ed.,
Cambridge University Press 2009, Theorem 2.3.1; Kallenberg, O. *Random Measures,
Theory and Applications*, Springer 2017, Proposition 3.6.

**Standard proof outline**: Decompose ν as a sum of finite measures (σ-finiteness);
on each finite piece, construct a finite Poisson random measure via the
"Poisson recipe": (a) sample N ~ Poisson(ν(B) · vol[0,T]), (b) sample N i.i.d.
points uniformly from B according to ν/ν(B); take their sum. Use the standard
property that this gives a Poisson random measure. Combine independently across
the σ-finite decomposition (Mathlib: `MeasureTheory.Measure.pi` + `iIndepFun_pi`).

**Replacement plan**: when Mathlib gains `PoissonRandomMeasure` / `Levy process`
construction, replace this `axiom` with a forwarder. Tracked in
`tools/cited_axioms.md`. -/
axiom PoissonRandomMeasure.exists_of_sigmaFinite
    (E : Type v) [MeasurableSpace E] [StandardBorelSpace E]
    (ν : Measure E) [SigmaFinite ν] :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω)
      (_ : IsProbabilityMeasure P), Nonempty (PoissonRandomMeasure P ν)

/-- **Step 2: Poisson random measure with finite intensity exists.**

Forwarded to the σ-finite case (`PoissonRandomMeasure.exists_of_sigmaFinite`,
Tier 1 cited axiom #2): any finite measure is automatically σ-finite (witnessed
by the `[SigmaFinite ν]` instance already in the signature), so the σ-finite
axiom gives the conclusion directly. The `_h_finite : ν Set.univ ≠ ⊤` argument
is retained in the signature for documentation of the original staging plan
(`sigmaFinite_decomposition` → finite-piece construction → combine), but the
present proof discharges by direct forward — the explicit Poisson-recipe
construction outlined in the axiom's docstring is what *would* discharge this
lemma without invoking the σ-finite axiom; that route is multi-week downstream
work tracked in `tools/cited_axioms.md` #2. -/
lemma poissonRandomMeasure_finite_exists
    (E : Type v) [MeasurableSpace E] [StandardBorelSpace E]
    (ν : Measure E) [SigmaFinite ν] (_h_finite : ν Set.univ ≠ ⊤) :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω)
      (_ : IsProbabilityMeasure P), Nonempty (PoissonRandomMeasure P ν) :=
  PoissonRandomMeasure.exists_of_sigmaFinite E ν

-- 2026-05-22 (deleted): `poissonRandomMeasure_combine` was a public
-- `True := trivial` placeholder for the σ-finite-piece combination step.
-- The actual combination is delivered inline within
-- `PoissonRandomMeasure.exists_of_sigmaFinite` (Tier 1 cited axiom #2).
-- The placeholder had no callers. Removed per red-team finding M1.

end LevyStochCalc.Poisson
