/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.Probability.Independence.Basic

/-!
# Independence of the counts on disjoint regions, σ-algebra form

For a random measure `N` whose counts on pairwise disjoint measurable sets are independent,
the σ-algebra generated by the counts on all measurable regions disjoint from `D` is
independent of the count on `D`. The finitely many regions are first replaced by the cells
of the partition they generate, which are pairwise disjoint.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Poisson

variable {Ω : Type*} [MeasurableSpace Ω] {𝓨 : Type*} [MeasurableSpace 𝓨]
  {P : Measure Ω} [IsProbabilityMeasure P] {N : Ω → Measure 𝓨}

omit [IsProbabilityMeasure P] in
/-- The counts on finitely many measurable regions disjoint from `D` generate a σ-algebra
independent of the count on `D`. -/
theorem indep_iSup_comap_of_disjoint_of_indep
    (hN_meas : ∀ {B : Set 𝓨}, MeasurableSet B → Measurable (fun ω => N ω B))
    (hN_indep : ∀ {ι : Type} [Countable ι] (B : ι → Set 𝓨), (∀ i, MeasurableSet (B i)) →
      Pairwise (fun i j => Disjoint (B i) (B j)) → iIndepFun (fun i ω => N ω (B i)) P)
    {n : ℕ} {D : Set 𝓨} (hD : MeasurableSet D) (C : Fin n → Set 𝓨)
    (hC : ∀ i, MeasurableSet (C i)) (hCD : ∀ i, Disjoint (C i) D) :
    Indep (⨆ i, MeasurableSpace.comap (fun ω => N ω (C i)) inferInstance)
      (MeasurableSpace.comap (fun ω => N ω D) inferInstance) P := by
  classical
  -- the cells of the partition generated by the `C i`, inside their union
  let atom : Finset (Fin n) → Set 𝓨 := fun S => {x | ∀ i, x ∈ C i ↔ i ∈ S} ∩ ⋃ i, C i
  have hatom_meas : ∀ S, MeasurableSet (atom S) := by
    intro S
    refine MeasurableSet.inter ?_ (MeasurableSet.iUnion hC)
    have : {x | ∀ i, x ∈ C i ↔ i ∈ S} = ⋂ i, (if i ∈ S then C i else (C i)ᶜ) := by
      ext x
      simp only [Set.mem_setOf_eq, Set.mem_iInter]
      refine forall_congr' fun i => ?_
      by_cases h : i ∈ S <;> simp [h]
    rw [this]
    exact MeasurableSet.iInter fun i => by
      split_ifs
      · exact hC i
      · exact (hC i).compl
  have hatom_disj : Pairwise fun S T => Disjoint (atom S) (atom T) := by
    intro S T hST
    rw [Set.disjoint_left]
    rintro x ⟨hxS, -⟩ ⟨hxT, -⟩
    exact hST (Finset.ext fun i => (hxS i).symm.trans (hxT i))
  have hatom_D : ∀ S, Disjoint (atom S) D := fun S =>
    (Set.disjoint_iUnion_left.mpr hCD).mono_left Set.inter_subset_right
  -- each `C i` is the disjoint union of the cells containing `i`
  have hC_eq : ∀ i, C i = ⋃ S ∈ Finset.univ.filter (fun S : Finset (Fin n) => i ∈ S), atom S := by
    intro i
    ext x
    simp only [Set.mem_iUnion, Finset.mem_filter, Finset.mem_univ, true_and, exists_prop]
    constructor
    · intro hx
      refine ⟨Finset.univ.filter (fun j => x ∈ C j), by simpa using hx, ?_,
        Set.mem_iUnion.mpr ⟨i, hx⟩⟩
      intro j
      simp
    · rintro ⟨S, hiS, hxS, -⟩
      exact (hxS i).mpr hiS
  have hcount : ∀ i, (fun ω => N ω (C i))
      = fun ω => ∑ S ∈ Finset.univ.filter (fun S : Finset (Fin n) => i ∈ S), N ω (atom S) := by
    intro i
    funext ω
    conv_lhs => rw [hC_eq i]
    exact measure_biUnion_finset (fun S _ T _ hST => hatom_disj hST) (fun S _ => hatom_meas S)
  -- the cells together with `D` form a countable pairwise-disjoint family
  let F : Option (Finset (Fin n)) → Set 𝓨 := fun o => o.elim D atom
  have hF_meas : ∀ o, MeasurableSet (F o) := by
    rintro (_ | S)
    · exact hD
    · exact hatom_meas S
  have hF_disj : Pairwise fun o o' => Disjoint (F o) (F o') := by
    rintro (_ | S) (_ | T) h
    · exact absurd rfl h
    · exact (hatom_D T).symm
    · exact hatom_D S
    · exact hatom_disj fun hST => h (by rw [hST])
  have hind : iIndepFun (fun o ω => N ω (F o)) P := hN_indep F hF_meas hF_disj
  have hle : ∀ o, MeasurableSpace.comap (fun ω => N ω (F o)) inferInstance
      ≤ ‹MeasurableSpace Ω› := fun o => (hN_meas (hF_meas o)).comap_le
  have hsplit := indep_iSup_of_disjoint hle hind.iIndep
    (S := Set.range fun S : Finset (Fin n) => some S) (T := {none})
    (by simp [Set.disjoint_left])
  refine indep_of_indep_of_le_left (indep_of_indep_of_le_right hsplit ?_) ?_
  · exact le_iSup₂_of_le none rfl le_rfl
  · refine iSup_le fun i => ?_
    rw [hcount i]
    refine Measurable.comap_le ?_
    letI : MeasurableSpace Ω :=
      ⨆ o ∈ Set.range (fun S : Finset (Fin n) => some S),
        MeasurableSpace.comap (fun ω => N ω (F o)) inferInstance
    exact Finset.measurable_sum _ fun S _ =>
      Measurable.of_comap_le (le_iSup₂_of_le (some S) ⟨S, rfl⟩ le_rfl)

/-- The σ-algebra generated by the counts on all measurable regions disjoint from `D` is
independent of the count on `D`. -/
theorem indep_of_disjoint_region_of_indep
    (hN_meas : ∀ {B : Set 𝓨}, MeasurableSet B → Measurable (fun ω => N ω B))
    (hN_indep : ∀ {ι : Type} [Countable ι] (B : ι → Set 𝓨), (∀ i, MeasurableSet (B i)) →
      Pairwise (fun i j => Disjoint (B i) (B j)) → iIndepFun (fun i ω => N ω (B i)) P)
    {D : Set 𝓨} (hD : MeasurableSet D) :
    Indep (⨆ C ∈ {C : Set 𝓨 | Disjoint C D ∧ MeasurableSet C},
        MeasurableSpace.comap (fun ω => N ω C) inferInstance)
      (MeasurableSpace.comap (fun ω => N ω D) inferInstance) P := by
  classical
  set 𝒞 := {C : Set 𝓨 | Disjoint C D ∧ MeasurableSet C}
  -- the σ-algebra generated by a finite subfamily, enumerated through `Finset.equivFin`
  let m : Finset 𝒞 → MeasurableSpace Ω := fun G =>
    ⨆ i : Fin G.card,
      MeasurableSpace.comap (fun ω => N ω (G.equivFin.symm i).1.1) inferInstance
  have hm_indep : ∀ G, Indep (m G) (MeasurableSpace.comap (fun ω => N ω D) inferInstance) P :=
    fun G => indep_iSup_comap_of_disjoint_of_indep hN_meas hN_indep hD
      (fun i => (G.equivFin.symm i).1.1)
      (fun i => (G.equivFin.symm i).1.2.2) fun i => (G.equivFin.symm i).1.2.1
  have hm_le : ∀ G, m G ≤ ‹MeasurableSpace Ω› :=
    fun G => iSup_le fun i => (hN_meas (G.equivFin.symm i).1.2.2).comap_le
  have hmono : ∀ G G' : Finset 𝒞, G ⊆ G' → m G ≤ m G' := by
    intro G G' hGG'
    refine iSup_le fun i => ?_
    refine le_iSup_of_le
      (G'.equivFin ⟨(G.equivFin.symm i).1, hGG' (G.equivFin.symm i).2⟩) ?_
    simp
  have hdir : Directed (· ≤ ·) m := fun G G' =>
    ⟨G ∪ G', hmono _ _ Finset.subset_union_left, hmono _ _ Finset.subset_union_right⟩
  have hsup : (⨆ G, m G)
      = ⨆ C ∈ 𝒞, MeasurableSpace.comap (fun ω => N ω C) inferInstance := by
    apply le_antisymm
    · exact iSup_le fun G => iSup_le fun i =>
        le_iSup₂_of_le (G.equivFin.symm i).1.1 (G.equivFin.symm i).1.2 le_rfl
    · refine iSup₂_le fun C hC => le_iSup_of_le {⟨C, hC⟩} ?_
      refine le_iSup_of_le
        (({⟨C, hC⟩} : Finset 𝒞).equivFin ⟨⟨C, hC⟩, Finset.mem_singleton_self _⟩) ?_
      simp
  rw [← hsup]
  exact indep_iSup_of_directed_le hm_indep hm_le (hN_meas hD).comap_le hdir

end LevyStochCalc.Poisson
