/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.MeasureTheory.Measure.MeasureSpace

/-!
# The partition generated by a finite family of sets

The cells `{x | ∀ i, x ∈ C i ↔ i ∈ S} ∩ ⋃ i, C i`, indexed by `S : Finset (Fin n)`, are pairwise
disjoint, sit inside `⋃ i, C i`, and exhibit each `C i` as the disjoint union of the cells whose
index contains `i`. Replacing a finite family by its cells is what turns a statement about counts
on overlapping regions into one about counts on disjoint regions.

## Main statements

* `partitionAtom` — the cells.
* `eq_biUnion_partitionAtom` — `C i` is the union of the cells containing `i`.
* `measure_eq_sum_partitionAtom` — hence `μ (C i)` is the sum of their measures.
-/

open MeasureTheory

namespace LevyStochCalc.Poisson

variable {𝓨 : Type*} [MeasurableSpace 𝓨] {n : ℕ} {C : Fin n → Set 𝓨}

variable (C) in
/-- The cell of the partition generated by `C` whose members lie in exactly the `C i` with
`i ∈ S`. -/
def partitionAtom (S : Finset (Fin n)) : Set 𝓨 :=
  {x | ∀ i, x ∈ C i ↔ i ∈ S} ∩ ⋃ i, C i

/-- The cells are measurable. -/
theorem measurableSet_partitionAtom (hC : ∀ i, MeasurableSet (C i)) (S : Finset (Fin n)) :
    MeasurableSet (partitionAtom C S) := by
  classical
  refine MeasurableSet.inter ?_ (MeasurableSet.iUnion hC)
  have h : {x | ∀ i, x ∈ C i ↔ i ∈ S} = ⋂ i, (if i ∈ S then C i else (C i)ᶜ) := by
    ext x
    simp only [Set.mem_setOf_eq, Set.mem_iInter]
    refine forall_congr' fun i => ?_
    by_cases h : i ∈ S <;> simp [h]
  rw [h]
  exact MeasurableSet.iInter fun i => by split_ifs; exacts [hC i, (hC i).compl]

omit [MeasurableSpace 𝓨] in
/-- Distinct cells are disjoint. -/
theorem pairwise_disjoint_partitionAtom :
    Pairwise fun S T => Disjoint (partitionAtom C S) (partitionAtom C T) := by
  intro S T hST
  rw [Set.disjoint_left]
  rintro x ⟨hxS, -⟩ ⟨hxT, -⟩
  exact hST (Finset.ext fun i => (hxS i).symm.trans (hxT i))

omit [MeasurableSpace 𝓨] in
/-- Every cell lies inside the union of the family. -/
theorem partitionAtom_subset_iUnion (S : Finset (Fin n)) :
    partitionAtom C S ⊆ ⋃ i, C i := Set.inter_subset_right

omit [MeasurableSpace 𝓨] in
/-- Each set of the family is the union of the cells whose index contains it. -/
theorem eq_biUnion_partitionAtom (i : Fin n) :
    C i = ⋃ S ∈ Finset.univ.filter (fun S : Finset (Fin n) => i ∈ S), partitionAtom C S := by
  classical
  ext x
  simp only [Set.mem_iUnion, Finset.mem_filter, Finset.mem_univ, true_and, exists_prop]
  constructor
  · intro hx
    exact ⟨Finset.univ.filter (fun j => x ∈ C j), by simpa using hx,
      fun j => by simp, Set.mem_iUnion.mpr ⟨i, hx⟩⟩
  · rintro ⟨S, hiS, hxS, -⟩
    exact (hxS i).mpr hiS

/-- The measure of each set of the family is the sum of the measures of its cells. -/
theorem measure_eq_sum_partitionAtom (μ : Measure 𝓨) (hC : ∀ i, MeasurableSet (C i)) (i : Fin n) :
    μ (C i)
      = ∑ S ∈ Finset.univ.filter (fun S : Finset (Fin n) => i ∈ S), μ (partitionAtom C S) := by
  classical
  conv_lhs => rw [eq_biUnion_partitionAtom (C := C) i]
  exact measure_biUnion_finset (fun S _ T _ hST => pairwise_disjoint_partitionAtom hST)
    fun S _ => measurableSet_partitionAtom hC S

end LevyStochCalc.Poisson
