/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Poisson.CylinderCharacters
import LevyStochCalc.Poisson.ZeroIntensity
import LevyStochCalc.Poisson.FiniteActivity
import LevyStochCalc.Probability.AugmentationMeasurable

/-!
# The natural filtration is generated by the counts on finite-intensity windows

The reference intensity is a product with a σ-finite mark measure, so a set of times at most `T`
splits into the null part at nonpositive times and a countable increasing union of sets inside
windows `(0, T] × A` with `ν A` finite. The counts on those windows are almost surely finite, so
their real parts generate the natural filtration modulo null sets, and the characters of those
real counts separate.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped ENNReal NNReal Topology

namespace LevyStochCalc.Poisson

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

section Window

/-- A measurable time–mark set inside a window of finite mark measure before `T`. -/
def WindowSet (E : Type v) [MeasurableSpace E] (ν : Measure E) (T : ℝ) : Type v :=
  {D : Set (ℝ × E) // MeasurableSet D ∧ ∃ A : Set E, MeasurableSet A ∧ ν A ≠ ⊤ ∧
    D ⊆ Set.Ioc (0 : ℝ) T ×ˢ A}

instance : CoeOut (WindowSet E ν T) (Set (ℝ × E)) := ⟨Subtype.val⟩

theorem WindowSet.measurableSet (D : WindowSet E ν T) : MeasurableSet (D : Set (ℝ × E)) := D.2.1

theorem WindowSet.subset_Iic (D : WindowSet E ν T) :
    (D : Set (ℝ × E)) ⊆ Set.Iic T ×ˢ Set.univ := by
  obtain ⟨A, -, -, hsub⟩ := D.2.2
  exact fun p hp => ⟨(hsub hp).1.2, Set.mem_univ _⟩

theorem WindowSet.intensity_ne_top (D : WindowSet E ν T) :
    referenceIntensity ν (D : Set (ℝ × E)) ≠ ⊤ := by
  obtain ⟨A, -, hAν, hsub⟩ := D.2.2
  exact ne_top_of_le_ne_top (referenceIntensity_Ioc_prod_ne_top hAν T) (measure_mono hsub)

/-- The σ-algebra generated by the counts on the finite-intensity windows before `T`. -/
@[implicit_reducible]
noncomputable def windowSigma (N : PoissonRandomMeasure P ν) (T : ℝ) : MeasurableSpace Ω :=
  ⨆ D : WindowSet E ν T,
    MeasurableSpace.comap (fun ω => (N.N ω (D : Set (ℝ × E))).toReal) inferInstance

theorem measurable_windowCount (N : PoissonRandomMeasure P ν) {T : ℝ}
    (D : WindowSet E ν T) : Measurable fun ω => (N.N ω (D : Set (ℝ × E))).toReal :=
  ENNReal.measurable_toReal.comp (N.measurable_eval D.measurableSet)

theorem windowSigma_le_natural (N : PoissonRandomMeasure P ν) (T : ℝ) :
    windowSigma N T ≤ naturalFiltration N T := by
  refine iSup_le fun D => ?_
  rw [naturalFiltration_seq_eq]
  refine le_trans ?_ (le_iSup₂_of_le (D : Set (ℝ × E)) ⟨D.subset_Iic, D.measurableSet⟩ le_rfl)
  rintro _ ⟨U, hU, rfl⟩
  exact ⟨ENNReal.toReal ⁻¹' U, ENNReal.measurable_toReal hU, rfl⟩

/-- A comap is inside the augmentation whenever the variable has an almost-everywhere equal
version measurable for the smaller σ-algebra. -/
theorem comap_le_aug_of_ae_eq {Ω' : Type*} [mΩ : MeasurableSpace Ω'] {α : Type*}
    [MeasurableSpace α] {μ : Measure Ω'} {X Y : Ω' → α} (hX : Measurable X)
    {m : MeasurableSpace Ω'} (hY : Measurable[m] Y) (hxy : X =ᵐ[μ] Y) :
    MeasurableSpace.comap X inferInstance ≤ Probability.aug m mΩ μ := by
  rintro _ ⟨U, hU, rfl⟩
  refine ⟨hX hU, Y ⁻¹' U, hY hU, measure_mono_null ?_ (ae_iff.mp hxy)⟩
  intro ω hω
  rcases hω with hω | hω
  · exact fun hEq => hω.2 (by rw [Set.mem_preimage, ← hEq]; exact hω.1)
  · exact fun hEq => hω.2 (by rw [Set.mem_preimage, hEq]; exact hω.1)

end Window

end LevyStochCalc.Poisson
