/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.PredictableModification
import LevyStochCalc.Ito.JumpSplittingLeftLim

/-!
# Predictability of the jump coefficient read at the left limits of the path

An adapted process that is left-continuous is the pointwise limit of the elementary processes
freezing it at the left endpoints of a dyadic grid, hence measurable for the predictable
σ-algebra; the left limits of a path are the limit along the same grid of the path itself. On the
time–mark space the predictable σ-algebra is generated by rectangles carried by the positive
times, so a marked predictable process is constant at nonpositive times, and a jointly measurable
coefficient evaluated at a predictable state is marked predictable once it is cut to the
positive times.

## Main statements

* `LevyStochCalc.Probability.measurable_predictableSigma_of_leftContinuous` — an adapted,
  left-continuous process is measurable for the predictable σ-algebra.
* `LevyStochCalc.Probability.measurable_predictableSigma_ite_of_leftContinuous` — the same for a
  process adapted and left-continuous at the positive times, cut to those times.
* `LevyStochCalc.Probability.MarkedPredictable.eq_of_nonpos` — a marked predictable process takes
  one value at all nonpositive times.
* `LevyStochCalc.Probability.markedPredictable_of_predictable` — a jointly measurable function of
  the time, a predictable state and the mark, vanishing at nonpositive times, is marked
  predictable.
* `LevyStochCalc.Ito.JumpSplitting.tendsto_nhdsLT_leftLimPath_self` and
  `LevyStochCalc.Ito.JumpSplitting.measurable_leftLimPath` — the left limits of a path having
  left limits at the positive times are left-continuous there, and known at the current time
  when the path is adapted.
* `LevyStochCalc.Ito.JumpSplitting.markedPredictable_jumpCoeff_leftLimPath` — the jump
  coefficient of a jump diffusion, evaluated at the left limits of the path, is marked
  predictable.

## References

* Protter, *Stochastic Integration and Differential Equations*, 2005, §III.2.
* Ikeda–Watanabe, *SDEs and Diffusion Processes*, 1989, §II.3.
-/

open Filter MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal Topology

namespace LevyStochCalc.Probability

universe u v

section Grid

/-- The largest point of the dyadic grid of mesh `2 ^ (-k)` lying strictly below a time. -/
noncomputable def leftGridPoint (k : ℕ) (s : ℝ) : ℝ := ((⌈s * 2 ^ k⌉ - 1 : ℤ) : ℝ) / 2 ^ k

/-- A time lies in the dyadic cell with left endpoint indexed by `j` exactly when `j` indexes the
grid point below it. -/
theorem mem_Ioc_iff_ceil_sub_one_eq (k : ℕ) (s : ℝ) (j : ℤ) :
    s ∈ Set.Ioc ((j : ℝ) / 2 ^ k) (((j : ℝ) + 1) / 2 ^ k) ↔ ⌈s * 2 ^ k⌉ - 1 = j := by
  have hk : (0 : ℝ) < 2 ^ k := by positivity
  rw [Set.mem_Ioc, div_lt_iff₀ hk, le_div_iff₀ hk, sub_eq_iff_eq_add, Int.ceil_eq_iff]
  push_cast
  constructor
  · rintro ⟨h1, h2⟩
    exact ⟨by linarith, by linarith⟩
  · rintro ⟨h1, h2⟩
    exact ⟨by linarith, by linarith⟩

/-- A time lies in the dyadic cell opening at the grid point below it. -/
theorem mem_Ioc_leftGridPoint (k : ℕ) (s : ℝ) :
    s ∈ Set.Ioc (leftGridPoint k s) (leftGridPoint k s + 1 / 2 ^ k) := by
  have h := (mem_Ioc_iff_ceil_sub_one_eq k s (⌈s * 2 ^ k⌉ - 1)).mpr rfl
  have hrw : leftGridPoint k s + 1 / 2 ^ k = (((⌈s * 2 ^ k⌉ - 1 : ℤ) : ℝ) + 1) / 2 ^ k := by
    rw [leftGridPoint, add_div]
  rw [hrw]
  exact h

/-- The dyadic grid point below a time is strictly below it. -/
theorem leftGridPoint_lt (k : ℕ) (s : ℝ) : leftGridPoint k s < s := (mem_Ioc_leftGridPoint k s).1

/-- The dyadic grid point below a time is within the mesh of it. -/
theorem sub_leftGridPoint_le (k : ℕ) (s : ℝ) : s - leftGridPoint k s ≤ 1 / 2 ^ k := by
  have h := (mem_Ioc_leftGridPoint k s).2
  linarith

/-- The dyadic grid points below a time converge to it from the left. -/
theorem tendsto_leftGridPoint (s : ℝ) :
    Tendsto (fun k : ℕ => leftGridPoint k s) atTop (𝓝[<] s) := by
  refine tendsto_nhdsWithin_of_tendsto_nhds_of_eventually_within _ ?_
    (Eventually.of_forall fun k => leftGridPoint_lt k s)
  have hz : Tendsto (fun k : ℕ => (1 : ℝ) / 2 ^ k) atTop (𝓝 0) := by
    have h : (fun k : ℕ => (1 : ℝ) / 2 ^ k) = fun k : ℕ => ((1 : ℝ) / 2) ^ k := by
      funext k
      rw [div_pow, one_pow]
    rw [h]
    exact tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num) (by norm_num)
  have hlow : Tendsto (fun k : ℕ => s - 1 / 2 ^ k) atTop (𝓝 s) := by
    simpa using (tendsto_const_nhds (x := s) (f := (atTop : Filter ℕ))).sub hz
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le hlow tendsto_const_nhds
    (fun k => by have := sub_leftGridPoint_le k s; linarith)
    (fun k => (leftGridPoint_lt k s).le)

end Grid

section Predictable

variable {Ω : Type u} {mΩ : MeasurableSpace Ω} {ℱ : Filtration ℝ mΩ}

/-- An adapted process frozen at the dyadic grid point below the time is predictable. -/
theorem measurable_predictableSigma_comp_leftGridPoint {Z : ℝ → Ω → ℝ}
    (hZ : ∀ t : ℝ, Measurable[ℱ t] (Z t)) (k : ℕ) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => Z (leftGridPoint k p.1) p.2 := by
  intro U hU
  have hpre : (fun p : ℝ × Ω => Z (leftGridPoint k p.1) p.2) ⁻¹' U
      = ⋃ j : ℤ, Set.Ioc ((j : ℝ) / 2 ^ k) (((j : ℝ) + 1) / 2 ^ k) ×ˢ
          (Z ((j : ℝ) / 2 ^ k) ⁻¹' U) := by
    ext p
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_prod]
    constructor
    · intro hs
      exact ⟨⌈p.1 * 2 ^ k⌉ - 1, (mem_Ioc_iff_ceil_sub_one_eq k p.1 _).mpr rfl, hs⟩
    · rintro ⟨j, hj, hzu⟩
      have hg : leftGridPoint k p.1 = (j : ℝ) / 2 ^ k := by
        rw [leftGridPoint, (mem_Ioc_iff_ceil_sub_one_eq k p.1 j).mp hj]
      rw [hg]
      exact hzu
  rw [hpre]
  refine MeasurableSet.iUnion fun j => ?_
  have hk : (0 : ℝ) < 2 ^ k := by positivity
  have hle : (j : ℝ) / 2 ^ k ≤ ((j : ℝ) + 1) / 2 ^ k := by
    rw [div_le_div_iff_of_pos_right hk]
    linarith
  exact measurableSet_predictableSigma_Ioc_prod hle (hZ _ hU)

/-- A process that is the pointwise limit of an adapted process read along the dyadic grid points
below the time is predictable. -/
theorem measurable_predictableSigma_of_tendsto_leftGridPoint {Z Y : ℝ → Ω → ℝ}
    (hZ : ∀ t : ℝ, Measurable[ℱ t] (Z t))
    (hlim : ∀ (s : ℝ) (ω : Ω),
      Tendsto (fun k : ℕ => Z (leftGridPoint k s) ω) atTop (𝓝 (Y s ω))) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => Y p.1 p.2 := by
  have hrw : (fun p : ℝ × Ω => Y p.1 p.2)
      = fun p : ℝ × Ω => limsup (fun k : ℕ => Z (leftGridPoint k p.1) p.2) atTop := by
    funext p
    exact ((hlim p.1 p.2).limsup_eq).symm
  rw [hrw]
  exact Measurable.limsup fun k => measurable_predictableSigma_comp_leftGridPoint hZ k

/-- **An adapted, left-continuous process is predictable.** -/
theorem measurable_predictableSigma_of_leftContinuous {Y : ℝ → Ω → ℝ}
    (hY : ∀ t : ℝ, Measurable[ℱ t] (Y t))
    (hleft : ∀ (t : ℝ) (ω : Ω), Tendsto (fun s => Y s ω) (𝓝[<] t) (𝓝 (Y t ω))) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => Y p.1 p.2 :=
  measurable_predictableSigma_of_tendsto_leftGridPoint hY fun s ω =>
    (hleft s ω).comp (tendsto_leftGridPoint s)

/-- **An adapted process that is left-continuous at the positive times is predictable after being
cut to those times.** -/
theorem measurable_predictableSigma_ite_of_leftContinuous {Y : ℝ → Ω → ℝ}
    (hY : ∀ t : ℝ, 0 < t → Measurable[ℱ t] (Y t))
    (hleft : ∀ t : ℝ, 0 < t → ∀ ω : Ω, Tendsto (fun s => Y s ω) (𝓝[<] t) (𝓝 (Y t ω))) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => if 0 < p.1 then Y p.1 p.2 else 0 := by
  classical
  refine measurable_predictableSigma_of_tendsto_leftGridPoint
    (Z := fun t ω => if 0 < t then Y t ω else 0)
    (Y := fun t ω => if 0 < t then Y t ω else 0) (fun t => ?_) (fun s ω => ?_)
  · by_cases h : (0 : ℝ) < t
    · simpa [h] using hY t h
    · simp only [if_neg h]
      exact measurable_const
  · by_cases hs : (0 : ℝ) < s
    · have hnhds : Tendsto (fun k : ℕ => leftGridPoint k s) atTop (𝓝 s) :=
        (tendsto_leftGridPoint s).mono_right nhdsWithin_le_nhds
      have hev : ∀ᶠ k : ℕ in atTop, 0 < leftGridPoint k s := hnhds.eventually (lt_mem_nhds hs)
      have hconv : Tendsto (fun k : ℕ => Y (leftGridPoint k s) ω) atTop (𝓝 (Y s ω)) :=
        (hleft s hs ω).comp (tendsto_leftGridPoint s)
      have hcong : (fun k : ℕ => Y (leftGridPoint k s) ω)
          =ᶠ[atTop] fun k : ℕ => if 0 < leftGridPoint k s then Y (leftGridPoint k s) ω else 0 := by
        filter_upwards [hev] with k hk
        rw [if_pos hk]
      simpa [hs] using hconv.congr' hcong
    · have h0 : ∀ k : ℕ, ¬(0 < leftGridPoint k s) := by
        intro k hk
        have h1 := leftGridPoint_lt k s
        exact hs (lt_trans hk h1)
      have hzero : (fun k : ℕ => if 0 < leftGridPoint k s then Y (leftGridPoint k s) ω else 0)
          = fun _ : ℕ => (0 : ℝ) := by
        funext k
        exact if_neg (h0 k)
      rw [hzero]
      simp [hs]

end Predictable

section Marked

variable {Ω : Type u} {mΩ : MeasurableSpace Ω} {ℱ : Filtration ℝ mΩ}
  {E : Type v} [MeasurableSpace E] {ν : Measure E}

/-- A left-open half-line of times above a nonnegative time, carrying an event known there and
all marks, is marked predictable. -/
theorem measurableSet_markedPredictableSigma_prod_Ioi [SigmaFinite ν] {r : ℝ} (hr : 0 ≤ r)
    {A : Set Ω} (hA : MeasurableSet[ℱ r] A) :
    MeasurableSet[markedPredictableSigma ℱ ν] (A ×ˢ (Set.Ioi r ×ˢ (Set.univ : Set E))) := by
  have hrw : A ×ˢ (Set.Ioi r ×ˢ (Set.univ : Set E))
      = ⋃ m : ℕ, ⋃ j : ℕ, A ×ˢ (Set.Ioc r (r + (m : ℝ)) ×ˢ spanningSets ν j) := by
    ext p
    simp only [Set.mem_prod, Set.mem_iUnion, Set.mem_Ioi, Set.mem_Ioc, Set.mem_univ, and_true]
    constructor
    · rintro ⟨hA', hr'⟩
      obtain ⟨m, hm⟩ := exists_nat_ge (p.2.1 - r)
      have hcov : p.2.2 ∈ ⋃ j, spanningSets ν j := by
        rw [iUnion_spanningSets ν]
        trivial
      obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hcov
      exact ⟨m, j, hA', ⟨hr', by linarith⟩, hj⟩
    · rintro ⟨m, j, hA', ⟨h1, -⟩, -⟩
      exact ⟨hA', h1⟩
  rw [hrw]
  exact MeasurableSet.iUnion fun m => MeasurableSet.iUnion fun j =>
    MeasurableSpace.measurableSet_generateFrom
      ⟨r, r + (m : ℝ), A, spanningSets ν j, hr, hA, measurableSet_spanningSets ν j,
        (measure_spanningSets_lt_top ν j).ne, rfl⟩

/-- The positive times of the time–mark space are marked predictable. -/
theorem measurableSet_markedPredictableSigma_pos (ℱ : Filtration ℝ mΩ) (ν : Measure E)
    [SigmaFinite ν] :
    MeasurableSet[markedPredictableSigma ℱ ν] {p : Ω × ℝ × E | 0 < p.2.1} := by
  have h := measurableSet_markedPredictableSigma_prod_Ioi (ℱ := ℱ) (ν := ν) (r := 0) le_rfl
    (A := (Set.univ : Set Ω)) MeasurableSet.univ
  have hrw : {p : Ω × ℝ × E | 0 < p.2.1}
      = (Set.univ : Set Ω) ×ˢ (Set.Ioi (0 : ℝ) ×ˢ (Set.univ : Set E)) := by
    ext p
    simp
  rw [hrw]
  exact h

/-- Every measurable time–mark set, cut to the positive times, is marked predictable. -/
theorem measurableSet_markedPredictableSigma_univ_prod_pos [SigmaFinite ν] {D : Set (ℝ × E)}
    (hD : MeasurableSet D) :
    MeasurableSet[markedPredictableSigma ℱ ν]
      ((Set.univ : Set Ω) ×ˢ (D ∩ Set.Ioi (0 : ℝ) ×ˢ (Set.univ : Set E))) := by
  have hrw : (Set.univ : Set Ω) ×ˢ (D ∩ Set.Ioi (0 : ℝ) ×ˢ (Set.univ : Set E))
      = ⋃ m : ℕ, ⋃ j : ℕ,
        (Set.univ : Set Ω) ×ˢ (D ∩ Set.Ioc (0 : ℝ) (m : ℝ) ×ˢ spanningSets ν j) := by
    ext p
    simp only [Set.mem_prod, Set.mem_univ, true_and, Set.mem_iUnion, Set.mem_inter_iff,
      Set.mem_Ioi, Set.mem_Ioc, and_true]
    constructor
    · rintro ⟨hD', hpos⟩
      obtain ⟨m, hm⟩ := exists_nat_ge p.2.1
      have hcov : p.2.2 ∈ ⋃ j, spanningSets ν j := by
        rw [iUnion_spanningSets ν]
        trivial
      obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hcov
      exact ⟨m, j, hD', ⟨hpos, hm⟩, hj⟩
    · rintro ⟨m, j, hD', ⟨h1, -⟩, -⟩
      exact ⟨hD', h1⟩
  rw [hrw]
  exact MeasurableSet.iUnion fun m => MeasurableSet.iUnion fun j =>
    measurableSet_univ_prod_window (measurableSet_spanningSets ν j)
      (measure_spanningSets_lt_top ν j).ne hD

/-- **A predictable set of times and sample points, cut to the positive times and carrying all
marks, is marked predictable.** -/
theorem measurableSet_markedPredictableSigma_of_predictableSigma [SigmaFinite ν]
    {S : Set (ℝ × Ω)} (hS : MeasurableSet[predictableSigma ℱ] S) :
    MeasurableSet[markedPredictableSigma ℱ ν]
      ({p : Ω × ℝ × E | (p.2.1, p.1) ∈ S} ∩ {p : Ω × ℝ × E | 0 < p.2.1}) := by
  have hpos := measurableSet_markedPredictableSigma_pos (Ω := Ω) (E := E) ℱ ν
  induction hS with
  | basic S hS =>
    rcases hS with ⟨A, hA, rfl⟩ | ⟨r, A, hA, rfl⟩
    · have hz : {p : Ω × ℝ × E | (p.2.1, p.1) ∈ Set.Iic (0 : ℝ) ×ˢ A}
          ∩ {p : Ω × ℝ × E | 0 < p.2.1} = ∅ := by
        ext p
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_prod, Set.mem_Iic,
          Set.mem_empty_iff_false, iff_false, not_and]
        rintro ⟨h1, -⟩ h2
        exact absurd h2 (not_lt.mpr h1)
      rw [hz]
      exact @MeasurableSet.empty _ (markedPredictableSigma ℱ ν)
    · have hz : {p : Ω × ℝ × E | (p.2.1, p.1) ∈ Set.Ioi r ×ˢ A}
          ∩ {p : Ω × ℝ × E | 0 < p.2.1}
          = A ×ˢ (Set.Ioi (max r 0) ×ˢ (Set.univ : Set E)) := by
        ext p
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_prod, Set.mem_Ioi,
          Set.mem_univ, and_true, max_lt_iff]
        tauto
      rw [hz]
      exact measurableSet_markedPredictableSigma_prod_Ioi (le_max_right r 0)
        (ℱ.mono (le_max_left r 0) _ hA)
  | empty =>
    have hz : {p : Ω × ℝ × E | (p.2.1, p.1) ∈ (∅ : Set (ℝ × Ω))}
        ∩ {p : Ω × ℝ × E | 0 < p.2.1} = ∅ := by
      ext p
      simp
    rw [hz]
    exact @MeasurableSet.empty _ (markedPredictableSigma ℱ ν)
  | compl S _ ih =>
    have hz : {p : Ω × ℝ × E | (p.2.1, p.1) ∈ Sᶜ} ∩ {p : Ω × ℝ × E | 0 < p.2.1}
        = {p : Ω × ℝ × E | 0 < p.2.1}
          \ ({p : Ω × ℝ × E | (p.2.1, p.1) ∈ S} ∩ {p : Ω × ℝ × E | 0 < p.2.1}) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_compl_iff, Set.mem_sdiff, not_and]
      tauto
    rw [hz]
    exact hpos.diff ih
  | iUnion g _ ih =>
    have hz : {p : Ω × ℝ × E | (p.2.1, p.1) ∈ ⋃ k, g k} ∩ {p : Ω × ℝ × E | 0 < p.2.1}
        = ⋃ k, ({p : Ω × ℝ × E | (p.2.1, p.1) ∈ g k} ∩ {p : Ω × ℝ × E | 0 < p.2.1}) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion]
      tauto
    rw [hz]
    exact MeasurableSet.iUnion ih

/-- The σ-algebra whose measurable sets are those meeting a fixed measurable set in a measurable
set. -/
@[implicit_reducible]
def traceSigma {α : Type*} (m : MeasurableSpace α) {s : Set α} (hs : MeasurableSet[m] s) :
    MeasurableSpace α where
  MeasurableSet' T := MeasurableSet[m] (T ∩ s)
  measurableSet_empty := by
    simp
  measurableSet_compl T hT := by
    have hrw : Tᶜ ∩ s = s \ (T ∩ s) := by
      ext x
      simp only [Set.mem_inter_iff, Set.mem_compl_iff, Set.mem_sdiff, not_and]
      tauto
    rw [hrw]
    exact hs.diff hT
  measurableSet_iUnion g hg := by
    rw [Set.iUnion_inter]
    exact MeasurableSet.iUnion hg

/-- A marked predictable set either misses the nonpositive times or contains all of them. -/
theorem markedPredictableSigma_disjoint_or_subset {S : Set (Ω × ℝ × E)}
    (hS : MeasurableSet[markedPredictableSigma ℱ ν] S) :
    S ∩ {p : Ω × ℝ × E | p.2.1 ≤ 0} = ∅ ∨ {p : Ω × ℝ × E | p.2.1 ≤ 0} ⊆ S := by
  induction hS with
  | basic S hS =>
    obtain ⟨r, q, F, B, hr, -, -, -, rfl⟩ := hS
    refine Or.inl ?_
    ext p
    simp only [Set.mem_inter_iff, Set.mem_prod, Set.mem_setOf_eq, Set.mem_Ioc,
      Set.mem_empty_iff_false, iff_false, not_and]
    rintro ⟨-, ⟨h1, -⟩, -⟩ h2
    exact absurd (lt_of_le_of_lt hr h1) (not_lt.mpr h2)
  | empty => exact Or.inl (by simp)
  | compl S _ ih =>
    rcases ih with h | h
    · refine Or.inr fun p hp => ?_
      exact fun hpS => (Set.eq_empty_iff_forall_notMem.mp h p) ⟨hpS, hp⟩
    · refine Or.inl ?_
      ext p
      simp only [Set.mem_inter_iff, Set.mem_compl_iff, Set.mem_setOf_eq,
        Set.mem_empty_iff_false, iff_false, not_and]
      exact fun hpS hle => hpS (h hle)
  | iUnion g _ ih =>
    by_cases hc : ∃ k, {p : Ω × ℝ × E | p.2.1 ≤ 0} ⊆ g k
    · obtain ⟨k, hk⟩ := hc
      exact Or.inr (hk.trans (Set.subset_iUnion g k))
    · simp only [not_exists] at hc
      refine Or.inl ?_
      rw [Set.iUnion_inter]
      refine Set.iUnion_eq_empty.mpr fun k => ?_
      rcases ih k with h | h
      · exact h
      · exact absurd h (hc k)

/-- **A marked predictable process takes a single value at all nonpositive times.** -/
theorem MarkedPredictable.eq_of_nonpos {ψ : Ω → ℝ → E → ℝ} (h : MarkedPredictable ℱ ν ψ)
    {ω ω' : Ω} {s s' : ℝ} {e e' : E} (hs : s ≤ 0) (hs' : s' ≤ 0) :
    ψ ω s e = ψ ω' s' e' := by
  have key : ∀ q : ℝ, (ψ ω s e < q ↔ ψ ω' s' e' < q) := by
    intro q
    rcases markedPredictableSigma_disjoint_or_subset (h (measurableSet_Iio (a := q))) with
      hd | hsub
    · have h1 : ¬ψ ω s e < q := fun hx =>
        (Set.eq_empty_iff_forall_notMem.mp hd (ω, s, e)) ⟨hx, hs⟩
      have h2 : ¬ψ ω' s' e' < q := fun hx =>
        (Set.eq_empty_iff_forall_notMem.mp hd (ω', s', e')) ⟨hx, hs'⟩
      exact iff_of_false h1 h2
    · exact iff_of_true (hsub (show (ω, s, e) ∈ {p : Ω × ℝ × E | p.2.1 ≤ 0} from hs))
        (hsub (show (ω', s', e') ∈ {p : Ω × ℝ × E | p.2.1 ≤ 0} from hs'))
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hgt
  · exact absurd ((key (ψ ω' s' e')).mp hlt) (lt_irrefl _)
  · exact absurd ((key (ψ ω s e)).mpr hgt) (lt_irrefl _)

/-- **A jointly measurable function of the time, a predictable state and the mark is marked
predictable once it is cut to the positive times.** -/
theorem markedPredictable_ite_of_predictable [SigmaFinite ν] {n : ℕ} {Λ : ℝ → Ω → Fin n → ℝ}
    (hΛ : Measurable[predictableSigma ℱ] fun p : ℝ × Ω => Λ p.1 p.2)
    {f : ℝ → (Fin n → ℝ) → E → ℝ}
    (hf : Measurable fun q : ℝ × (Fin n → ℝ) × E => f q.1 q.2.1 q.2.2) :
    MarkedPredictable ℱ ν fun (ω : Ω) (s : ℝ) (e : E) => if 0 < s then f s (Λ s ω) e else 0 := by
  classical
  have hpos := measurableSet_markedPredictableSigma_pos (Ω := Ω) (E := E) ℱ ν
  have h1 : Measurable[traceSigma (markedPredictableSigma ℱ ν) hpos]
      fun p : Ω × ℝ × E => p.2.1 := by
    intro D hD
    have hrw : ((fun p : Ω × ℝ × E => p.2.1) ⁻¹' D) ∩ {p : Ω × ℝ × E | 0 < p.2.1}
        = (Set.univ : Set Ω) ×ˢ ((D ×ˢ (Set.univ : Set E))
            ∩ Set.Ioi (0 : ℝ) ×ˢ (Set.univ : Set E)) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_setOf_eq, Set.mem_prod,
        Set.mem_univ, true_and, and_true, Set.mem_Ioi]
    show MeasurableSet[markedPredictableSigma ℱ ν] (_ ∩ _)
    rw [hrw]
    exact measurableSet_markedPredictableSigma_univ_prod_pos (hD.prod MeasurableSet.univ)
  have h2 : Measurable[traceSigma (markedPredictableSigma ℱ ν) hpos]
      fun p : Ω × ℝ × E => p.2.2 := by
    intro D hD
    have hrw : ((fun p : Ω × ℝ × E => p.2.2) ⁻¹' D) ∩ {p : Ω × ℝ × E | 0 < p.2.1}
        = (Set.univ : Set Ω) ×ˢ (((Set.univ : Set ℝ) ×ˢ D)
            ∩ Set.Ioi (0 : ℝ) ×ˢ (Set.univ : Set E)) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_setOf_eq, Set.mem_prod,
        Set.mem_univ, true_and, and_true, Set.mem_Ioi]
    show MeasurableSet[markedPredictableSigma ℱ ν] (_ ∩ _)
    rw [hrw]
    exact measurableSet_markedPredictableSigma_univ_prod_pos (MeasurableSet.univ.prod hD)
  have h3 : Measurable[traceSigma (markedPredictableSigma ℱ ν) hpos]
      fun p : Ω × ℝ × E => Λ p.2.1 p.1 := fun D hD =>
    measurableSet_markedPredictableSigma_of_predictableSigma (E := E) (ν := ν) (hΛ hD)
  have hcomp : Measurable[traceSigma (markedPredictableSigma ℱ ν) hpos]
      fun p : Ω × ℝ × E => f p.2.1 (Λ p.2.1 p.1) p.2.2 :=
    hf.comp (h1.prodMk (h3.prodMk h2))
  intro U hU
  have hkey : MeasurableSet[markedPredictableSigma ℱ ν]
      (((fun p : Ω × ℝ × E => f p.2.1 (Λ p.2.1 p.1) p.2.2) ⁻¹' U)
        ∩ {p : Ω × ℝ × E | 0 < p.2.1}) := hcomp hU
  show MeasurableSet[markedPredictableSigma ℱ ν]
    ((fun p : Ω × ℝ × E => if 0 < p.2.1 then f p.2.1 (Λ p.2.1 p.1) p.2.2 else 0) ⁻¹' U)
  by_cases h0 : (0 : ℝ) ∈ U
  · have hrw : (fun p : Ω × ℝ × E =>
        if 0 < p.2.1 then f p.2.1 (Λ p.2.1 p.1) p.2.2 else 0) ⁻¹' U
        = (((fun p : Ω × ℝ × E => f p.2.1 (Λ p.2.1 p.1) p.2.2) ⁻¹' U)
            ∩ {p : Ω × ℝ × E | 0 < p.2.1}) ∪ {p : Ω × ℝ × E | 0 < p.2.1}ᶜ := by
      ext p
      by_cases hp : 0 < p.2.1 <;> simp [hp, h0]
    rw [hrw]
    exact hkey.union hpos.compl
  · have hrw : (fun p : Ω × ℝ × E =>
        if 0 < p.2.1 then f p.2.1 (Λ p.2.1 p.1) p.2.2 else 0) ⁻¹' U
        = ((fun p : Ω × ℝ × E => f p.2.1 (Λ p.2.1 p.1) p.2.2) ⁻¹' U)
            ∩ {p : Ω × ℝ × E | 0 < p.2.1} := by
      ext p
      by_cases hp : 0 < p.2.1 <;> simp [hp, h0]
    rw [hrw]
    exact hkey

/-- **A jointly measurable function of the time, a predictable state and the mark, vanishing at
nonpositive times, is marked predictable.** -/
theorem markedPredictable_of_predictable [SigmaFinite ν] {n : ℕ} {Λ : ℝ → Ω → Fin n → ℝ}
    (hΛ : Measurable[predictableSigma ℱ] fun p : ℝ × Ω => Λ p.1 p.2)
    {f : ℝ → (Fin n → ℝ) → E → ℝ}
    (hf : Measurable fun q : ℝ × (Fin n → ℝ) × E => f q.1 q.2.1 q.2.2)
    (hf0 : ∀ s : ℝ, s ≤ 0 → ∀ (x : Fin n → ℝ) (e : E), f s x e = 0) :
    MarkedPredictable ℱ ν fun (ω : Ω) (s : ℝ) (e : E) => f s (Λ s ω) e := by
  classical
  have h := markedPredictable_ite_of_predictable (ν := ν) hΛ hf
  have hrw : (fun (ω : Ω) (s : ℝ) (e : E) => if 0 < s then f s (Λ s ω) e else 0)
      = fun (ω : Ω) (s : ℝ) (e : E) => f s (Λ s ω) e := by
    funext ω s e
    by_cases hs : 0 < s
    · rw [if_pos hs]
    · rw [if_neg hs, hf0 s (not_lt.mp hs)]
  rwa [hrw] at h

end Marked

end LevyStochCalc.Probability

namespace LevyStochCalc.Ito.JumpSplitting

open LevyStochCalc.Probability

universe u v

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]
  {n d : ℕ}
  {W : LevyStochCalc.Brownian.Multidim.MultidimBrownianMotion P d}
  {N : LevyStochCalc.Poisson.PoissonRandomMeasure P ν}
  {coeffs : Setting.JumpDiffusionCoeffs n d E} {x₀ : Fin n → ℝ}

/-- The left limits of the path of a jump diffusion, cut to the positive times. -/
noncomputable def leftLimPathPos (X : Setting.JumpDiffusion W N coeffs x₀) (s : ℝ) (ω : Ω) :
    Fin n → ℝ := if 0 < s then leftLimPath X s ω else 0

/-- The left limits at a time of an adapted path having left limits there are known at that
time. -/
theorem measurable_leftLimPath (X : Setting.JumpDiffusion W N coeffs x₀)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (X.X t)) {t : ℝ}
    (hleft : ∀ (ω : Ω) (i : Fin n), ∃ L : ℝ, Tendsto (fun s => X.X s ω i) (𝓝[<] t) (𝓝 L)) :
    Measurable[ℱ t] (leftLimPath X t) := by
  refine (@measurable_pi_iff Ω (Fin n) (fun _ => ℝ) (ℱ t) inferInstance
    (leftLimPath X t)).mpr fun i => ?_
  have hrw : (fun ω => leftLimPath X t ω i)
      = fun ω => limsup (fun k : ℕ => X.X (leftGridPoint k t) ω i) atTop := by
    funext ω
    exact (((tendsto_nhdsLT_leftLimPath (fun j => hleft ω j) i).comp
      (tendsto_leftGridPoint t)).limsup_eq).symm
  rw [hrw]
  refine Measurable.limsup fun k => ?_
  have hm : Measurable[ℱ (leftGridPoint k t)] fun ω => X.X (leftGridPoint k t) ω i :=
    (measurable_pi_apply i).comp (hXadapt (leftGridPoint k t))
  exact hm.mono (ℱ.mono (leftGridPoint_lt k t).le) le_rfl

/-- **The left limits of a path having left limits at the positive times are left-continuous
there.** -/
theorem tendsto_nhdsLT_leftLimPath_self (X : Setting.JumpDiffusion W N coeffs x₀) {ω : Ω}
    (hleft : ∀ t : ℝ, 0 < t → ∀ i : Fin n,
      ∃ L : ℝ, Tendsto (fun s => X.X s ω i) (𝓝[<] t) (𝓝 L))
    {t : ℝ} (ht : 0 < t) :
    Tendsto (fun u => leftLimPath X u ω) (𝓝[<] t) (𝓝 (leftLimPath X t ω)) := by
  refine tendsto_pi_nhds.mpr fun i => ?_
  refine Metric.tendsto_nhdsWithin_nhds.mpr fun ε hε => ?_
  obtain ⟨δ, hδ, hδ'⟩ := Metric.tendsto_nhdsWithin_nhds.mp
    (tendsto_nhdsLT_leftLimPath (hleft t ht) i) (ε / 2) (by linarith)
  refine ⟨min δ t, lt_min hδ ht, fun {u} hu hdu => ?_⟩
  have hut : u < t := hu
  have hdist : dist u t = t - u := by
    rw [Real.dist_eq, abs_of_nonpos (by linarith : u - t ≤ 0)]
    ring
  rw [hdist] at hdu
  have hupos : 0 < u := by
    have h := lt_of_lt_of_le hdu (min_le_right δ t)
    linarith
  have hδu : t - δ < u := by
    have h := lt_of_lt_of_le hdu (min_le_left δ t)
    linarith
  have hconv : Tendsto (fun s => X.X s ω i) (𝓝[<] u) (𝓝 (leftLimPath X u ω i)) :=
    tendsto_nhdsLT_leftLimPath (hleft u hupos) i
  have hev : ∀ᶠ x in 𝓝[<] u, dist (X.X x ω i) (leftLimPath X t ω i) ≤ ε / 2 := by
    filter_upwards [Ioo_mem_nhdsLT hδu] with x hx
    have hxt : x < t := lt_trans hx.2 hut
    have hdx : dist x t < δ := by
      rw [Real.dist_eq, abs_of_nonpos (by linarith : x - t ≤ 0)]
      linarith [hx.1]
    exact (hδ' (Set.mem_Iio.mpr hxt) hdx).le
  have hle : dist (leftLimPath X u ω i) (leftLimPath X t ω i) ≤ ε / 2 :=
    le_of_tendsto (hconv.dist tendsto_const_nhds) hev
  linarith

/-- **The left limits of an adapted path having left limits at the positive times, cut to those
times, are predictable.** -/
theorem measurable_predictableSigma_leftLimPathPos (X : Setting.JumpDiffusion W N coeffs x₀)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (X.X t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ i : Fin n,
      ∃ L : ℝ, Tendsto (fun s => X.X s ω i) (𝓝[<] t) (𝓝 L)) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => leftLimPathPos X p.1 p.2 := by
  classical
  refine (@measurable_pi_iff (ℝ × Ω) (Fin n) (fun _ => ℝ) (predictableSigma ℱ) inferInstance
    (fun p : ℝ × Ω => leftLimPathPos X p.1 p.2)).mpr fun i => ?_
  refine measurable_predictableSigma_of_tendsto_leftGridPoint
    (Z := fun t ω => if 0 < t then X.X t ω i else 0)
    (Y := fun t ω => leftLimPathPos X t ω i) (fun t => ?_) (fun s ω => ?_)
  · by_cases h : (0 : ℝ) < t
    · have hm : Measurable[ℱ t] fun ω => X.X t ω i := (measurable_pi_apply i).comp (hXadapt t)
      simpa [h] using hm
    · simp only [if_neg h]
      exact measurable_const
  · by_cases hs : (0 : ℝ) < s
    · have hnhds : Tendsto (fun k : ℕ => leftGridPoint k s) atTop (𝓝 s) :=
        (tendsto_leftGridPoint s).mono_right nhdsWithin_le_nhds
      have hev : ∀ᶠ k : ℕ in atTop, 0 < leftGridPoint k s := hnhds.eventually (lt_mem_nhds hs)
      have hconv : Tendsto (fun k : ℕ => X.X (leftGridPoint k s) ω i) atTop
          (𝓝 (leftLimPath X s ω i)) :=
        (tendsto_nhdsLT_leftLimPath (hleft ω s hs) i).comp (tendsto_leftGridPoint s)
      have hcong : (fun k : ℕ => X.X (leftGridPoint k s) ω i)
          =ᶠ[atTop] fun k : ℕ =>
            if 0 < leftGridPoint k s then X.X (leftGridPoint k s) ω i else 0 := by
        filter_upwards [hev] with k hk
        rw [if_pos hk]
      simpa [leftLimPathPos, hs] using hconv.congr' hcong
    · have h0 : ∀ k : ℕ, ¬(0 < leftGridPoint k s) := fun k hk =>
        hs (lt_trans hk (leftGridPoint_lt k s))
      have hzero : (fun k : ℕ =>
          if 0 < leftGridPoint k s then X.X (leftGridPoint k s) ω i else 0)
          = fun _ : ℕ => (0 : ℝ) := by
        funext k
        exact if_neg (h0 k)
      rw [hzero]
      simp [leftLimPathPos, hs]

/-- **The jump coefficient of a jump diffusion, evaluated at the left limits of the path, is
predictable on the time–mark space.** -/
theorem markedPredictable_jumpCoeff_leftLimPath (X : Setting.JumpDiffusion W N coeffs x₀)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›) (i : Fin n)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (X.X t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ j : Fin n,
      ∃ L : ℝ, Tendsto (fun s => X.X s ω j) (𝓝[<] t) (𝓝 L))
    (hγ : Measurable fun q : ℝ × (Fin n → ℝ) × E => coeffs.γ q.1 q.2.1 q.2.2 i)
    (hγ0 : ∀ s : ℝ, s ≤ 0 → ∀ (x : Fin n → ℝ) (e : E), coeffs.γ s x e i = 0) :
    MarkedPredictable ℱ ν fun ω s e => coeffs.γ s (leftLimPath X s ω) e i := by
  classical
  have h := markedPredictable_ite_of_predictable (ν := ν)
    (measurable_predictableSigma_leftLimPathPos X ℱ hXadapt hleft)
    (f := fun s x e => coeffs.γ s x e i) hγ
  have hrw : (fun (ω : Ω) (s : ℝ) (e : E) =>
      if 0 < s then coeffs.γ s (leftLimPathPos X s ω) e i else 0)
      = fun (ω : Ω) (s : ℝ) (e : E) => coeffs.γ s (leftLimPath X s ω) e i := by
    funext ω s e
    by_cases hs : 0 < s
    · simp only [if_pos hs, leftLimPathPos]
    · rw [if_neg hs, hγ0 s (not_lt.mp hs)]
  rwa [hrw] at h

/-- **The jump coefficients of a regular jump-diffusion coefficient bundle, evaluated at the left
limits of the path, are predictable on the time–mark space.** -/
theorem markedPredictable_forall_jumpCoeff_leftLimPath (X : Setting.JumpDiffusion W N coeffs x₀)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (X.X t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ j : Fin n,
      ∃ L : ℝ, Tendsto (fun s => X.X s ω j) (𝓝[<] t) (𝓝 L))
    (hreg : coeffs.IsRegular ν)
    (hγ0 : ∀ s : ℝ, s ≤ 0 → ∀ (x : Fin n → ℝ) (e : E), coeffs.γ s x e = 0) :
    ∀ i : Fin n, MarkedPredictable ℱ ν fun ω s e => coeffs.γ s (leftLimPath X s ω) e i :=
  fun i => markedPredictable_jumpCoeff_leftLimPath X ℱ i hXadapt hleft
    ((measurable_pi_apply i).comp hreg.2.2.1)
    (fun s hs x e => by rw [hγ0 s hs x e]; rfl)

end LevyStochCalc.Ito.JumpSplitting

