/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Ito.JumpCoefficientPredictableCriteria
import LevyStochCalc.Ito.JumpCoefficientPredictableLeftLim

/-!
# Predictability of the jump coefficient read at the left limits of the path

An adapted process that is left-continuous is the pointwise limit of the elementary processes
freezing it at the left endpoints of a dyadic grid, hence measurable for the predictable
σ-algebra; the left limits of a path are the limit along the same grid of the path itself. On the
time–mark space the predictable σ-algebra is generated by rectangles carried by the positive
times, so a marked predictable process is constant at nonpositive times, and a jointly measurable
coefficient evaluated at a predictable state is marked predictable once it is cut to the
positive times.

## Contents

* `LevyStochCalc.Ito.JumpCoefficientPredictableCriteria` — predictability criteria on the time
  line and on the time–mark space.
* `LevyStochCalc.Ito.JumpCoefficientPredictableLeftLim` — the left limits of the path of a jump
  diffusion and the jump coefficient read at them.

## Main statements

* `LevyStochCalc.Probability.measurable_predictableSigma_of_leftContinuous` — an adapted,
  left-continuous process is measurable for the predictable σ-algebra.
* `LevyStochCalc.Probability.measurable_predictableSigma_ite_of_leftContinuous` — the same for a
  process adapted and left-continuous at the positive times, cut to those times.
* `LevyStochCalc.Probability.MarkedPredictable.eq_of_nonpos` — a marked predictable process takes
  one value at all nonpositive times.
* `LevyStochCalc.Probability.markedPredictable_of_predictable` — a jointly measurable function of
  the time, a predictable state and the mark, vanishing at nonpositive times, is marked
  predictable.
* `LevyStochCalc.Ito.JumpSplitting.tendsto_nhdsLT_leftLimPath_self` and
  `LevyStochCalc.Ito.JumpSplitting.measurable_leftLimPath` — the left limits of a path having
  left limits at the positive times are left-continuous there, and known at the current time
  when the path is adapted.
* `LevyStochCalc.Ito.JumpSplitting.markedPredictable_jumpCoeff_leftLimPath` — the jump
  coefficient of a jump diffusion, evaluated at the left limits of the path, is marked
  predictable.

## References

* Protter, *Stochastic Integration and Differential Equations*, 2005, §III.2.
* Ikeda–Watanabe, *SDEs and Diffusion Processes*, 1989, §II.3.
-/
