/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Ito.JumpCoefficientPredictable
import LevyStochCalc.Ito.JumpFormulaClosure
import LevyStochCalc.Ito.JumpSplittingPath

/-!
# The zero-extension convention for marked predictability

The marked predictable σ-algebra is generated by rectangles carried by the positive times, so the
nonpositive times form a single atom on which every marked predictable process is constant.
Rather than asking a jump integrand to vanish at nonpositive times, one extends it by zero below
the time domain: the extension has the same energy class as the integrand, and it is marked
predictable exactly when the integrand is predictable on the positive times. The jump coefficient
of a coefficient bundle read at the left limits of an adapted path with left limits is of this
kind, whether or not the path solves an equation, and the mark cut of a zero-extended integrand
is the zero extension of the mark cut.

## Main definitions

* `LevyStochCalc.Ito.JumpSplitting.leftLimPathAtPos` — the left limits of a path, cut to the
  positive times.

## Main statements

* `LevyStochCalc.Ito.JumpFormula.markCut_zeroExtPos_comm` — the mark cut and the zero extension
  commute.
* `LevyStochCalc.Ito.JumpFormula.markedPredictable_markCut_zeroExtPos`,
  `LevyStochCalc.Ito.JumpFormula.markedPredictable_zeroExtPos_markCut` — the mark cut of a
  marked predictable zero-extended integrand is marked predictable, in either order.
* `LevyStochCalc.Ito.JumpSplitting.measurable_predictableSigma_leftLimPathAtPos` — the left
  limits of an adapted path having left limits at the positive times, cut to those times, are
  predictable.
* `LevyStochCalc.Ito.JumpSplitting.markedPredictable_zeroExtPos_jumpCoeff_leftLimPathAt`,
  `LevyStochCalc.Ito.JumpSplitting.markedPredictable_zeroExtPos_jumpCoeff_leftLimPath` — the
  zero extension of the jump coefficient read at the left limits of an adapted path, or of the
  path of a jump diffusion, is marked predictable.

## References

* Protter, *Stochastic Integration and Differential Equations*, 2005, §III.2.
* Ikeda–Watanabe, *SDEs and Diffusion Processes*, 1989, §II.3.
-/

open Filter MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal Topology

namespace LevyStochCalc.Ito.JumpFormula

open LevyStochCalc.Probability LevyStochCalc.Poisson.Compensated

universe u v

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {ν : Measure E} [SigmaFinite ν] {ℱ : Filtration ℝ ‹MeasurableSpace Ω›}

omit [MeasurableSpace Ω] [MeasurableSpace E] in
/-- The mark cut of a zero-extended integrand is the zero extension of its mark cut. -/
theorem markCut_zeroExtPos_comm (A : Set E) (φ : Ω → ℝ → E → ℝ) :
    markCut A (zeroExtPos φ) = zeroExtPos (markCut A φ) := by
  funext ω s e
  by_cases hs : (0 : ℝ) < s
  · rw [markCut_apply, zeroExtPos_of_pos φ ω hs e, zeroExtPos_of_pos (markCut A φ) ω hs e,
      markCut_apply]
  · have hs' : s ≤ 0 := not_lt.mp hs
    rw [markCut_apply, zeroExtPos_of_nonpos φ ω hs' e, zeroExtPos_of_nonpos (markCut A φ) ω hs' e]
    by_cases he : e ∈ A
    · rw [Set.indicator_of_mem he]
    · rw [Set.indicator_of_notMem he]

/-- The mark cut of a marked predictable zero-extended integrand is marked predictable. -/
theorem markedPredictable_markCut_zeroExtPos {φ : Ω → ℝ → E → ℝ}
    (hφ : MarkedPredictable ℱ ν (zeroExtPos φ)) {A : Set E} (hA : MeasurableSet A) :
    MarkedPredictable ℱ ν (markCut A (zeroExtPos φ)) :=
  markedPredictable_markCut hφ (fun ω _ e hs => zeroExtPos_of_nonpos φ ω hs e) hA

/-- The zero extension of the mark cut of an integrand is marked predictable whenever the zero
extension of the integrand is. -/
theorem markedPredictable_zeroExtPos_markCut {φ : Ω → ℝ → E → ℝ}
    (hφ : MarkedPredictable ℱ ν (zeroExtPos φ)) {A : Set E} (hA : MeasurableSet A) :
    MarkedPredictable ℱ ν (zeroExtPos (markCut A φ)) := by
  rw [← markCut_zeroExtPos_comm]
  exact markedPredictable_markCut_zeroExtPos hφ hA

end LevyStochCalc.Ito.JumpFormula

namespace LevyStochCalc.Ito.JumpSplitting

open LevyStochCalc.Probability LevyStochCalc.Ito.JumpFormula

universe u v

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {ν : Measure E} [SigmaFinite ν] {n d : ℕ} {coeffs : Setting.JumpDiffusionCoeffs n d E}

/-- The left limits of a path, cut to the positive times. -/
noncomputable def leftLimPathAtPos (Xp : ℝ → Ω → Fin n → ℝ) (s : ℝ) (ω : Ω) : Fin n → ℝ :=
  if 0 < s then leftLimPathAt Xp s ω else 0

/-- **The left limits of an adapted path having left limits at the positive times, cut to those
times, are predictable.** -/
theorem measurable_predictableSigma_leftLimPathAtPos (Xp : ℝ → Ω → Fin n → ℝ)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (Xp t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ i : Fin n,
      ∃ L : ℝ, Tendsto (fun s => Xp s ω i) (𝓝[<] t) (𝓝 L)) :
    Measurable[predictableSigma ℱ] fun p : ℝ × Ω => leftLimPathAtPos Xp p.1 p.2 := by
  classical
  refine (@measurable_pi_iff (ℝ × Ω) (Fin n) (fun _ => ℝ) (predictableSigma ℱ) inferInstance
    (fun p : ℝ × Ω => leftLimPathAtPos Xp p.1 p.2)).mpr fun i => ?_
  refine measurable_predictableSigma_of_tendsto_leftGridPoint
    (Z := fun t ω => if 0 < t then Xp t ω i else 0)
    (Y := fun t ω => leftLimPathAtPos Xp t ω i) (fun t => ?_) (fun s ω => ?_)
  · by_cases h : (0 : ℝ) < t
    · have hm : Measurable[ℱ t] fun ω => Xp t ω i := (measurable_pi_apply i).comp (hXadapt t)
      simpa [h] using hm
    · simp only [if_neg h]
      exact measurable_const
  · by_cases hs : (0 : ℝ) < s
    · have hnhds : Tendsto (fun k : ℕ => leftGridPoint k s) atTop (𝓝 s) :=
        (tendsto_leftGridPoint s).mono_right nhdsWithin_le_nhds
      have hev : ∀ᶠ k : ℕ in atTop, 0 < leftGridPoint k s := hnhds.eventually (lt_mem_nhds hs)
      have hconv : Tendsto (fun k : ℕ => Xp (leftGridPoint k s) ω i) atTop
          (𝓝 (leftLimPathAt Xp s ω i)) :=
        (tendsto_nhdsLT_leftLimPathAt (hleft ω s hs) i).comp (tendsto_leftGridPoint s)
      have hcong : (fun k : ℕ => Xp (leftGridPoint k s) ω i)
          =ᶠ[atTop] fun k : ℕ =>
            if 0 < leftGridPoint k s then Xp (leftGridPoint k s) ω i else 0 := by
        filter_upwards [hev] with k hk
        rw [if_pos hk]
      simpa [leftLimPathAtPos, hs] using hconv.congr' hcong
    · have h0 : ∀ k : ℕ, ¬(0 < leftGridPoint k s) := fun k hk =>
        hs (lt_trans hk (leftGridPoint_lt k s))
      have hzero : (fun k : ℕ =>
          if 0 < leftGridPoint k s then Xp (leftGridPoint k s) ω i else 0)
          = fun _ : ℕ => (0 : ℝ) := by
        funext k
        exact if_neg (h0 k)
      rw [hzero]
      simp [leftLimPathAtPos, hs]

/-- **The zero extension of the jump coefficient of a coefficient bundle, read at the left limits
of an adapted path having left limits at the positive times, is marked predictable.** -/
theorem markedPredictable_zeroExtPos_jumpCoeff_leftLimPathAt (Xp : ℝ → Ω → Fin n → ℝ)
    (ℱ : Filtration ℝ ‹MeasurableSpace Ω›) (i : Fin n)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (Xp t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ j : Fin n,
      ∃ L : ℝ, Tendsto (fun s => Xp s ω j) (𝓝[<] t) (𝓝 L))
    (hγ : Measurable fun q : ℝ × (Fin n → ℝ) × E => coeffs.γ q.1 q.2.1 q.2.2 i) :
    MarkedPredictable ℱ ν (zeroExtPos fun ω s e => coeffs.γ s (leftLimPathAt Xp s ω) e i) := by
  classical
  have h := markedPredictable_ite_of_predictable (ν := ν)
    (measurable_predictableSigma_leftLimPathAtPos Xp ℱ hXadapt hleft)
    (f := fun s x e => coeffs.γ s x e i) hγ
  have hrw : (fun (ω : Ω) (s : ℝ) (e : E) =>
      if 0 < s then coeffs.γ s (leftLimPathAtPos Xp s ω) e i else 0)
      = zeroExtPos fun ω s e => coeffs.γ s (leftLimPathAt Xp s ω) e i := by
    funext ω s e
    by_cases hs : (0 : ℝ) < s
    · rw [if_pos hs, zeroExtPos_of_pos _ ω hs e]
      simp only [leftLimPathAtPos, if_pos hs]
    · rw [if_neg hs, zeroExtPos_of_nonpos _ ω (not_lt.mp hs) e]
  rwa [hrw] at h

variable {P : Measure Ω} [IsProbabilityMeasure P]
  {W : LevyStochCalc.Brownian.Multidim.MultidimBrownianMotion P d}
  {N : LevyStochCalc.Poisson.PoissonRandomMeasure P ν} {x₀ : Fin n → ℝ}

/-- **The zero extension of the jump coefficient of a jump diffusion, read at the left limits of
its path, is marked predictable.** -/
theorem markedPredictable_zeroExtPos_jumpCoeff_leftLimPath
    (X : Setting.JumpDiffusion W N coeffs x₀) (ℱ : Filtration ℝ ‹MeasurableSpace Ω›) (i : Fin n)
    (hXadapt : ∀ t : ℝ, Measurable[ℱ t] (X.X t))
    (hleft : ∀ (ω : Ω) (t : ℝ), 0 < t → ∀ j : Fin n,
      ∃ L : ℝ, Tendsto (fun s => X.X s ω j) (𝓝[<] t) (𝓝 L))
    (hγ : Measurable fun q : ℝ × (Fin n → ℝ) × E => coeffs.γ q.1 q.2.1 q.2.2 i) :
    MarkedPredictable ℱ ν (zeroExtPos fun ω s e => coeffs.γ s (leftLimPath X s ω) e i) :=
  markedPredictable_zeroExtPos_jumpCoeff_leftLimPathAt X.X ℱ i hXadapt hleft hγ

end LevyStochCalc.Ito.JumpSplitting
