/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Ito.JumpFormulaClosure
import LevyStochCalc.Poisson.CompensatedCongr
import LevyStochCalc.Poisson.PathwiseIdentity

/-!
# Transfer of the window identities along the zero extension

The marked predictable σ-algebra is generated by rectangles carried by the positive times, so a
marked integrand that does not vanish below zero is never marked predictable; its zero extension
`zeroExtPos` can be. Every quantity the window identities form from a marked integrand — the
pathwise integral over `Set.Ioc 0 T ×ˢ A`, the integral against the reference intensity over the
same window, and the compensated integral — is insensitive to the values at nonpositive times, so
those identities hold for an integrand whose zero extension is marked predictable.

## Main statements

* `LevyStochCalc.Ito.JumpFormula.measurable_zeroExtPos`,
  `LevyStochCalc.Ito.JumpFormula.markedProgressivelyMeasurable_zeroExtPos`,
  `LevyStochCalc.Ito.JumpFormula.energy_zeroExtPos_lt_top` — the zero extension inherits joint
  measurability, marked progressive measurability and finite energy.
* `LevyStochCalc.Ito.JumpFormula.setIntegral_window_zeroExtPos` — the integral over a window of
  positive times is unchanged by the zero extension.
* `LevyStochCalc.Ito.JumpFormula.compensated_zeroExtPos_congr` — the compensated integrals of an
  integrand and of its zero extension agree almost surely.
* `LevyStochCalc.Ito.JumpFormula.ae_integrableOn_window_of_zeroExtPos`,
  `LevyStochCalc.Ito.JumpFormula.stochasticIntegral_ae_eq_pathwise_of_zeroExtPos` — the window
  integrability and the pathwise form of the compensated integral, under predictability of the
  zero extension.

## References

* Protter, *Stochastic Integration and Differential Equations*, 2005, §III.2.
* Ikeda–Watanabe, *SDEs and Diffusion Processes*, 1989, §II.3.
-/

open Filter MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal Topology

namespace LevyStochCalc.Ito.JumpFormula

open LevyStochCalc.Probability LevyStochCalc.Poisson LevyStochCalc.Poisson.Compensated

universe u v

section Pointwise

variable {Ω : Type u} {E : Type v}

/-- The zero extension is the indicator of the positive times. -/
theorem zeroExtPos_eq_indicator (φ : Ω → ℝ → E → ℝ) (ω : Ω) (s : ℝ) (e : E) :
    zeroExtPos φ ω s e = (Set.Ioi (0 : ℝ)).indicator (fun _ => φ ω s e) s := by
  by_cases hs : (0 : ℝ) < s
  · rw [zeroExtPos_of_pos φ ω hs e, Set.indicator_of_mem (Set.mem_Ioi.mpr hs)]
  · rw [zeroExtPos_of_nonpos φ ω (not_lt.mp hs) e,
      Set.indicator_of_notMem (by simpa using hs)]

/-- The zero extension of an integrand carried by a mark set is carried by that mark set. -/
theorem zeroExtPos_eq_zero_of_notMem {φ : Ω → ℝ → E → ℝ} {A : Set E}
    (hsupp : ∀ (ω : Ω) (s : ℝ) (e : E), e ∉ A → φ ω s e = 0) (ω : Ω) (s : ℝ) (e : E)
    (he : e ∉ A) : zeroExtPos φ ω s e = 0 := by
  by_cases hs : (0 : ℝ) < s
  · rw [zeroExtPos_of_pos φ ω hs e, hsupp ω s e he]
  · rw [zeroExtPos_of_nonpos φ ω (not_lt.mp hs) e]

/-- The zero extension is bounded in norm by the integrand. -/
theorem nnnorm_zeroExtPos_le (φ : Ω → ℝ → E → ℝ) (ω : Ω) (s : ℝ) (e : E) :
    ‖zeroExtPos φ ω s e‖₊ ≤ ‖φ ω s e‖₊ := by
  by_cases hs : (0 : ℝ) < s
  · rw [zeroExtPos_of_pos φ ω hs e]
  · rw [zeroExtPos_of_nonpos φ ω (not_lt.mp hs) e]
    simp

/-- The zero extension is bounded in extended norm by the integrand. -/
theorem enorm_zeroExtPos_le (φ : Ω → ℝ → E → ℝ) (ω : Ω) (s : ℝ) (e : E) :
    ‖zeroExtPos φ ω s e‖ₑ ≤ ‖φ ω s e‖ₑ := by
  by_cases hs : (0 : ℝ) < s
  · rw [zeroExtPos_of_pos φ ω hs e]
  · rw [zeroExtPos_of_nonpos φ ω (not_lt.mp hs) e]
    simp

end Pointwise

section Regularity

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} {ν : Measure E} {ℱ : Filtration ℝ ‹MeasurableSpace Ω›} {φ : Ω → ℝ → E → ℝ}

/-- The zero extension of a jointly measurable marked integrand is jointly measurable. -/
theorem measurable_zeroExtPos (hm : Measurable fun p : Ω × ℝ × E => φ p.1 p.2.1 p.2.2) :
    Measurable fun p : Ω × ℝ × E => zeroExtPos φ p.1 p.2.1 p.2.2 := by
  have hS : MeasurableSet {p : Ω × ℝ × E | 0 < p.2.1} :=
    measurableSet_lt measurable_const (measurable_fst.comp measurable_snd)
  have hrw : (fun p : Ω × ℝ × E => zeroExtPos φ p.1 p.2.1 p.2.2)
      = {p : Ω × ℝ × E | 0 < p.2.1}.indicator fun p => φ p.1 p.2.1 p.2.2 := by
    funext p
    by_cases hs : (0 : ℝ) < p.2.1
    · rw [zeroExtPos_of_pos φ p.1 hs p.2.2,
        Set.indicator_of_mem (show p ∈ {p : Ω × ℝ × E | 0 < p.2.1} from hs)]
    · rw [zeroExtPos_of_nonpos φ p.1 (not_lt.mp hs) p.2.2,
        Set.indicator_of_notMem (show p ∉ {p : Ω × ℝ × E | 0 < p.2.1} from hs)]
  rw [hrw]
  exact hm.indicator hS

/-- The zero extension of a marked progressively measurable integrand is marked progressively
measurable. -/
theorem markedProgressivelyMeasurable_zeroExtPos
    (hp : MarkedProgressivelyMeasurable ℱ φ) :
    MarkedProgressivelyMeasurable ℱ (zeroExtPos φ) := by
  have h := hp.indicator_time (S := Set.Ioi (0 : ℝ)) measurableSet_Ioi
  have hrw : (fun (ω : Ω) (s : ℝ) (e : E) => (Set.Ioi (0 : ℝ)).indicator (fun _ => φ ω s e) s)
      = zeroExtPos φ := by
    funext ω s e
    rw [zeroExtPos_eq_indicator]
  rwa [hrw] at h

/-- The energy of the zero extension is at most the energy of the integrand. -/
theorem energy_zeroExtPos_le (φ : Ω → ℝ → E → ℝ) (T : ℝ) :
    (∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e,
        (‖zeroExtPos φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P)
      ≤ ∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e, (‖φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P := by
  refine lintegral_mono fun ω => lintegral_mono fun s => lintegral_mono fun e => ?_
  gcongr
  exact nnnorm_zeroExtPos_le φ ω s e

/-- The zero extension of an integrand of finite energy has finite energy. -/
theorem energy_zeroExtPos_lt_top
    (hq : ∀ T : ℝ, 0 < T → ∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e,
      (‖φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P < ⊤) :
    ∀ T : ℝ, 0 < T → ∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e,
      (‖zeroExtPos φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P < ⊤ :=
  fun T hT => lt_of_le_of_lt (energy_zeroExtPos_le φ T) (hq T hT)

end Regularity

section Window

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]
  {ℱ : Filtration ℝ ‹MeasurableSpace Ω›} {φ : Ω → ℝ → E → ℝ}

omit [MeasurableSpace Ω] [MeasurableSpace E] in
/-- The zero extension agrees with the integrand on a window of positive times. -/
theorem eqOn_window_zeroExtPos (φ : Ω → ℝ → E → ℝ) (ω : Ω) (A : Set E) (T : ℝ) :
    Set.EqOn (fun q : ℝ × E => zeroExtPos φ ω q.1 q.2) (fun q : ℝ × E => φ ω q.1 q.2)
      (Set.Ioc (0 : ℝ) T ×ˢ A) := by
  intro q hq
  exact zeroExtPos_of_pos φ ω hq.1.1 q.2

omit [MeasurableSpace Ω] in
/-- The integral over a window of positive times is unchanged by the zero extension. -/
theorem setIntegral_window_zeroExtPos (φ : Ω → ℝ → E → ℝ) (ω : Ω) {A : Set E}
    (hA : MeasurableSet A) (T : ℝ) (κ : Measure (ℝ × E)) :
    ∫ q in Set.Ioc (0 : ℝ) T ×ˢ A, zeroExtPos φ ω q.1 q.2 ∂κ
      = ∫ q in Set.Ioc (0 : ℝ) T ×ˢ A, φ ω q.1 q.2 ∂κ :=
  setIntegral_congr_fun (measurableSet_Ioc.prod hA) (eqOn_window_zeroExtPos φ ω A T)

omit [IsProbabilityMeasure P] [SigmaFinite ν] in
/-- The window energy is bounded by the window energy of the integrand. -/
theorem window_energy_zeroExtPos_le (φ : Ω → ℝ → E → ℝ) {A : Set E} (T : ℝ) :
    (∫⁻ ω, ∫⁻ q in Set.Ioc (0 : ℝ) T ×ˢ A,
        ‖zeroExtPos φ ω q.1 q.2‖ₑ ^ 2 ∂(referenceIntensity ν) ∂P)
      ≤ ∫⁻ ω, ∫⁻ q in Set.Ioc (0 : ℝ) T ×ˢ A,
          ‖φ ω q.1 q.2‖ₑ ^ 2 ∂(referenceIntensity ν) ∂P := by
  refine lintegral_mono fun ω => lintegral_mono fun q => ?_
  gcongr
  exact enorm_zeroExtPos_le φ ω q.1 q.2

variable (N : PoissonRandomMeasure P ν)

/-- **The compensated integrals of an integrand and of its zero extension agree almost surely.**
The two differ only at nonpositive times, which carry no energy. -/
theorem compensated_zeroExtPos_congr (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hℱ : IsPoissonFiltration N ℱ) (φ : Ω → ℝ → E → ℝ)
    (hm : Measurable fun p : Ω × ℝ × E => φ p.1 p.2.1 p.2.2)
    (hp : MarkedProgressivelyMeasurable ℱ φ)
    (hq : ∀ T : ℝ, 0 < T → ∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e,
      (‖φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P < ⊤)
    {T : ℝ} (hT : 0 < T) :
    stochasticIntegral N ℱ hℱ φ hm hp hq T
      =ᵐ[P] stochasticIntegral N ℱ hℱ (zeroExtPos φ) (measurable_zeroExtPos hm)
        (markedProgressivelyMeasurable_zeroExtPos hp) (energy_zeroExtPos_lt_top hq) T :=
  stochasticIntegral_congr_ae N hℱ φ (zeroExtPos φ) hm (measurable_zeroExtPos hm) hp
    (markedProgressivelyMeasurable_zeroExtPos hp) hq (energy_zeroExtPos_lt_top hq) hT
    (zeroExtPos_ae_eq φ T)

/-- **A marked integrand whose zero extension is predictable and whose energy is finite is
almost surely integrable on a window of finite intensity**, both against the random measure and
against the reference intensity. -/
theorem ae_integrableOn_window_of_zeroExtPos {ℱ : Filtration ℝ ‹MeasurableSpace Ω›}
    (hℱ : IsPoissonFiltration N ℱ) {A : Set E} (hA : MeasurableSet A) (hAν : ν A ≠ ⊤) (T : ℝ)
    {φ : Ω → ℝ → E → ℝ} (hpred : MarkedPredictable ℱ ν (zeroExtPos φ))
    (hm : Measurable fun p : Ω × ℝ × E => φ p.1 p.2.1 p.2.2)
    (hen : ∫⁻ ω, ∫⁻ q in Set.Ioc (0 : ℝ) T ×ˢ A,
      ‖φ ω q.1 q.2‖ₑ ^ 2 ∂(referenceIntensity ν) ∂P ≠ ⊤) :
    ∀ᵐ ω ∂P, IntegrableOn (fun q : ℝ × E => φ ω q.1 q.2) (Set.Ioc (0 : ℝ) T ×ˢ A) (N.N ω)
      ∧ IntegrableOn (fun q : ℝ × E => φ ω q.1 q.2) (Set.Ioc (0 : ℝ) T ×ˢ A)
          (referenceIntensity ν) := by
  have hen' : ∫⁻ ω, ∫⁻ q in Set.Ioc (0 : ℝ) T ×ˢ A,
      ‖zeroExtPos φ ω q.1 q.2‖ₑ ^ 2 ∂(referenceIntensity ν) ∂P ≠ ⊤ :=
    ne_top_of_le_ne_top hen (window_energy_zeroExtPos_le (P := P) (ν := ν) φ (A := A) T)
  have hW : MeasurableSet (Set.Ioc (0 : ℝ) T ×ˢ A) := measurableSet_Ioc.prod hA
  filter_upwards [ae_integrableOn_window N hℱ hA hAν T hpred (measurable_zeroExtPos hm) hen']
    with ω hω
  exact ⟨hω.1.congr_fun (eqOn_window_zeroExtPos φ ω A T) hW,
    hω.2.congr_fun (eqOn_window_zeroExtPos φ ω A T) hW⟩

/-- **The compensated integral of a marked integrand whose zero extension is predictable and
which is carried by a window of finite intensity is pathwise.** -/
theorem stochasticIntegral_ae_eq_pathwise_of_zeroExtPos (ℱ : Filtration ℝ ‹MeasurableSpace Ω›)
    (hℱ : IsPoissonFiltration N ℱ) (φ : Ω → ℝ → E → ℝ)
    (hm : Measurable fun p : Ω × ℝ × E => φ p.1 p.2.1 p.2.2)
    (hp : MarkedProgressivelyMeasurable ℱ φ)
    (hq : ∀ T : ℝ, 0 < T → ∫⁻ ω, ∫⁻ s in Set.Icc (0 : ℝ) T, ∫⁻ e,
      (‖φ ω s e‖₊ : ℝ≥0∞) ^ 2 ∂ν ∂volume ∂P < ⊤)
    {A : Set E} (hA : MeasurableSet A) (hpred : MarkedPredictable ℱ ν (zeroExtPos φ))
    (hAν : ν A ≠ ⊤) (hsupp : ∀ (ω : Ω) (s : ℝ) (e : E), e ∉ A → φ ω s e = 0) {T : ℝ}
    (hT : 0 < T) :
    stochasticIntegral N ℱ hℱ φ hm hp hq T
      =ᵐ[P] fun ω => (∫ q in Set.Ioc (0 : ℝ) T ×ˢ A, φ ω q.1 q.2 ∂(N.N ω))
        - ∫ q in Set.Ioc (0 : ℝ) T ×ˢ A, φ ω q.1 q.2 ∂(referenceIntensity ν) := by
  have hpath := stochasticIntegral_ae_eq_pathwise N ℱ hℱ (zeroExtPos φ) (measurable_zeroExtPos hm)
    (markedProgressivelyMeasurable_zeroExtPos hp) (energy_zeroExtPos_lt_top hq) hA hpred hAν
    (zeroExtPos_eq_zero_of_notMem hsupp) hT
  filter_upwards [compensated_zeroExtPos_congr N ℱ hℱ φ hm hp hq hT, hpath] with ω h1 h2
  rw [h1, h2, setIntegral_window_zeroExtPos φ ω hA T, setIntegral_window_zeroExtPos φ ω hA T]

end Window

end LevyStochCalc.Ito.JumpFormula
