name = "LevyStochCalc"
version = "0.1.0"
keywords = ["math", "stochastic-calculus", "levy-processes"]
defaultTargets = ["LevyStochCalc"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "0e208554a6143756c125878a8fe8b17a331d39f7"

[[lean_lib]]
name = "LevyStochCalc"
