/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.CharCylinder
import LevyStochCalc.Brownian.MultidimFiltered

/-!
# Cylinder characters of a multidimensional Brownian motion

The natural filtration of a multidimensional Brownian motion at a time `T` is generated by the
values of its coordinates at the times of `Set.Iic T`, so the characters of those finitely many
values separate the integrable variables it measures.
-/

open MeasureTheory Complex
open scoped RealInnerProductSpace

namespace LevyStochCalc.Brownian.Multidim.MultidimBrownianMotion

universe u

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P] {d : ℕ}

/-- The natural filtration at `T` is generated by the coordinate values at the times of
`Set.Iic T`. -/
theorem naturalFiltration_eq_iSup_comap (W : MultidimBrownianMotion P d) (T : ℝ) :
    W.naturalFiltration T
      = ⨆ p : Fin d × Set.Iic T,
          MeasurableSpace.comap ((W.W p.1).W (p.2 : ℝ)) inferInstance := by
  rw [naturalFiltration_apply, iSup_prod]
  refine iSup_congr fun i => ?_
  rw [iSup_subtype'' (Set.Iic T) fun t => MeasurableSpace.comap ((W.W i).W t) inferInstance]
  simp only [Set.mem_Iic]
  rfl

/-- **Cylinder characters of a Brownian motion separate.** An integrable weight measurable for
the natural filtration at `T`, integrating to zero against every character of every finite family
of coordinate values before `T`, vanishes almost everywhere. -/
theorem ae_eq_zero_of_integral_char_cylinder (W : MultidimBrownianMotion P d) (T : ℝ)
    {Z : Ω → ℂ} (hZ : Integrable Z P)
    (hZm : StronglyMeasurable[W.naturalFiltration T] Z)
    (h : ∀ (F : Finset (Fin d × Set.Iic T)) (w : F → ℝ),
      ∫ ω, Complex.exp
          ((∑ p : F, (W.W (p : Fin d × Set.Iic T).1).W ((p : Fin d × Set.Iic T).2 : ℝ) ω * w p
            : ℝ) * Complex.I) * Z ω ∂P = 0) :
    Z =ᵐ[P] 0 := by
  refine Probability.ae_eq_zero_of_integral_char_cylinder_eq_zero
    (Y := fun p : Fin d × Set.Iic T => (W.W p.1).W (p.2 : ℝ))
    (fun p => (W.W p.1).measurable_eval _) (W.naturalFiltration.le T)
    (naturalFiltration_eq_iSup_comap W T) hZ hZm ?_
  intro F w
  refine Eq.trans ?_ (h F w)
  refine integral_congr_ae (Filter.Eventually.of_forall fun ω => ?_)
  simp [RCLike.inner_apply, mul_comm]

end LevyStochCalc.Brownian.Multidim.MultidimBrownianMotion
