/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.FutureIndependence
import LevyStochCalc.Brownian.MartingaleCondExp
import LevyStochCalc.Probability.ComapTuple
import LevyStochCalc.Probability.IndepJoin
import LevyStochCalc.Probability.IndepLimit

/-!
# Brownian motion with respect to a filtration

`IsBrownianFiltration W ℱ` says that the Brownian motion `W` is adapted to the filtration `ℱ`
and that, for `0 ≤ s`, the σ-algebra `ℱ s` is independent of the σ-algebra generated by *all*
the increments `W t − W s`, `t > s`. Independence of `ℱ s` from a single increment is the
special case `IsBrownianFiltration.indep`. The natural filtration of `W` is an instance, a
smaller filtration to which `W` is adapted is one, and so is the right-continuous version `ℱ₊`,
since for a finite family of times `t₁, …, tₙ > s` the increments `W tᵢ − W r`, jointly
independent of `ℱ r ⊇ ℱ₊ s`, converge to `W tᵢ − W s` along the continuous paths as `r ↓ s`.
-/

open MeasureTheory ProbabilityTheory Filter Topology

namespace LevyStochCalc.Brownian

universe u

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]

/-- `W` is a Brownian motion for the filtration `ℱ`: it is adapted, and for `0 ≤ s` the
σ-algebra `ℱ s` is independent of the σ-algebra generated by the increments `W t − W s`,
`t > s`. -/
structure IsBrownianFiltration (W : BrownianMotion P) (ℱ : Filtration ℝ ‹MeasurableSpace Ω›) :
    Prop where
  measurable : ∀ t, Measurable[ℱ t] (W.W t)
  indep_future : ∀ ⦃s : ℝ⦄, 0 ≤ s →
    Indep (ℱ s) (⨆ t ∈ Set.Ioi s,
      MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) P

/-- The σ-algebra `ℱ s` is independent of a single increment `W t − W s`, `0 ≤ s < t`. -/
theorem IsBrownianFiltration.indep {W : BrownianMotion P}
    {ℱ : Filtration ℝ ‹MeasurableSpace Ω›} (h : IsBrownianFiltration W ℱ) :
    ∀ ⦃s t : ℝ⦄, 0 ≤ s → s < t →
      Indep (ℱ s) (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) P :=
  fun _ t hs hst => indep_of_indep_of_le_right (h.indep_future hs)
    (le_iSup₂_of_le t (Set.mem_Ioi.mpr hst) le_rfl)

/-- A Brownian motion is a Brownian motion for its natural filtration. -/
theorem isBrownianFiltration_natural (W : BrownianMotion P) :
    IsBrownianFiltration W (Martingale.naturalFiltration W) where
  measurable t := by
    refine Measurable.of_comap_le ?_
    change MeasurableSpace.comap (W.W t) inferInstance
      ≤ ⨆ j ≤ t, MeasurableSpace.comap (W.W j) inferInstance
    exact le_iSup₂_of_le t le_rfl le_rfl
  indep_future _ hs := W.indep_naturalFiltration_future hs

/-- A Brownian motion for `ℱ` is one for any smaller filtration to which it is adapted. -/
theorem IsBrownianFiltration.of_le {W : BrownianMotion P} {ℱ 𝒢 : Filtration ℝ ‹MeasurableSpace Ω›}
    (h : IsBrownianFiltration W ℱ) (hle : 𝒢 ≤ ℱ) (hadapted : ∀ t, Measurable[𝒢 t] (W.W t)) :
    IsBrownianFiltration W 𝒢 where
  measurable := hadapted
  indep_future _ hs := indep_of_indep_of_le_left (h.indep_future hs) (hle _)

/-- A Brownian motion for `ℱ` is one for the right-continuous filtration `ℱ₊`. -/
theorem IsBrownianFiltration.rightCont {W : BrownianMotion P} {ℱ : Filtration ℝ ‹MeasurableSpace Ω›}
    (h : IsBrownianFiltration W ℱ) : IsBrownianFiltration W ℱ.rightCont where
  measurable t := (h.measurable t).mono (ℱ.le_rightCont t) le_rfl
  indep_future := by
    classical
    intro s hs
    obtain ⟨r, hr_anti, hr_gt, hr_tend⟩ := exists_seq_strictAnti_tendsto s
    have hle : ∀ k, ℱ.rightCont s ≤ ℱ (r k) := fun k => by
      rw [Filtration.rightCont_eq_of_neBot_nhdsGT ℱ s]
      exact iInf₂_le (r k) (hr_gt k)
    have hfin : ∀ (n : ℕ) (u : Fin n → ℝ), (∀ i, s < u i) →
        Indep (ℱ.rightCont s)
          (⨆ i, MeasurableSpace.comap (fun ω => W.W (u i) ω - W.W s ω) inferInstance) P := by
      intro n u hu
      obtain ⟨K, hK⟩ := Filter.eventually_atTop.mp
        (Filter.eventually_all.2 fun i => hr_tend.eventually (eventually_lt_nhds (hu i)))
      have hq_lt : ∀ (k : ℕ) (i : Fin n), r (k + K) < u i := fun k i =>
        hK (k + K) (Nat.le_add_left K k) i
      have hq_tend : Tendsto (fun k => r (k + K)) atTop (𝓝 s) :=
        hr_tend.comp (tendsto_add_atTop_nat K)
      have hYcomap :
          MeasurableSpace.comap (fun ω (i : Fin n) => W.W (u i) ω - W.W s ω) inferInstance
            = ⨆ i, MeasurableSpace.comap (fun ω => W.W (u i) ω - W.W s ω) inferInstance :=
        Probability.comap_pi_eq_iSup fun i ω => W.W (u i) ω - W.W s ω
      rw [← hYcomap]
      refine Probability.indep_comap_of_tendsto_ae (ℱ.rightCont.le s)
        (X := fun k ω (i : Fin n) => W.W (u i) ω - W.W (r (k + K)) ω)
        (fun k => measurable_pi_lambda _ fun i =>
          (W.measurable_eval (u i)).sub (W.measurable_eval (r (k + K))))
        (measurable_pi_lambda _ fun i => (W.measurable_eval (u i)).sub (W.measurable_eval s))
        (fun k => ?_) ?_
      · have hkcomap : MeasurableSpace.comap
              (fun ω (i : Fin n) => W.W (u i) ω - W.W (r (k + K)) ω) inferInstance
            = ⨆ i, MeasurableSpace.comap
              (fun ω => W.W (u i) ω - W.W (r (k + K)) ω) inferInstance :=
          Probability.comap_pi_eq_iSup fun i ω => W.W (u i) ω - W.W (r (k + K)) ω
        rw [hkcomap]
        refine indep_of_indep_of_le_left (indep_of_indep_of_le_right
          (h.indep_future (hs.trans (hr_gt (k + K)).le)) ?_) (hle (k + K))
        exact iSup_le fun i => le_iSup₂_of_le (u i) (Set.mem_Ioi.mpr (hq_lt k i)) le_rfl
      · filter_upwards [W.continuous_paths] with ω hω
        exact tendsto_pi_nhds.2 fun i => tendsto_const_nhds.sub ((hω.tendsto s).comp hq_tend)
    have hsup : (⨆ t ∈ Set.Ioi s,
          MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance)
        = ⨆ t : Set.Ioi s,
            MeasurableSpace.comap (fun ω => W.W (t : ℝ) ω - W.W s ω) inferInstance :=
      le_antisymm
        (iSup₂_le fun t ht => le_iSup (fun t : Set.Ioi s =>
          MeasurableSpace.comap (fun ω => W.W (t : ℝ) ω - W.W s ω) inferInstance) ⟨t, ht⟩)
        (iSup_le fun t => le_iSup₂_of_le (t : ℝ) t.2 le_rfl)
    rw [hsup]
    refine (Probability.indep_iSup_of_finset
      (m := fun t : Set.Ioi s =>
        MeasurableSpace.comap (fun ω => W.W (t : ℝ) ω - W.W s ω) inferInstance)
      (fun t => ((W.measurable_eval (t : ℝ)).sub (W.measurable_eval s)).comap_le)
      (ℱ.rightCont.le s) fun S => ?_).symm
    exact indep_of_indep_of_le_left
      (hfin S.card (fun i => ((S.equivFin.symm i).1 : ℝ))
        (fun i => (S.equivFin.symm i).1.2)).symm
      (iSup₂_le fun t ht => le_iSup_of_le (S.equivFin ⟨t, ht⟩) (by simp))

namespace IsBrownianFiltration

variable {W : BrownianMotion P} {ℱ : Filtration ℝ ‹MeasurableSpace Ω›}

/-- `W_t` is `ℱ t`-strongly measurable. -/
theorem stronglyMeasurable (h : IsBrownianFiltration W ℱ) (t : ℝ) :
    StronglyMeasurable[ℱ t] (W.W t) :=
  (h.measurable t).stronglyMeasurable

/-- The conditional expectation of the increment `W_t − W_s`, `0 ≤ s < t`, given `ℱ s`
vanishes. -/
theorem condExp_increment_eq_zero (h : IsBrownianFiltration W ℱ) {s t : ℝ} (hs : 0 ≤ s)
    (hst : s < t) : P[(fun ω => W.W t ω - W.W s ω) | ℱ s] =ᵐ[P] fun _ => 0 :=
  Martingale.condExp_increment_eq_zero_of_indep W ℱ hs hst (h.indep hs hst)

/-- The martingale identity `E[W_t | ℱ s] = W_s` for `0 ≤ s ≤ t`. -/
theorem condExp_eq (h : IsBrownianFiltration W ℱ) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    P[W.W t | ℱ s] =ᵐ[P] W.W s := by
  have h_int_s := Martingale.brownianMotion_integrable W s
  rcases hst.eq_or_lt with rfl | hlt
  · rw [condExp_of_stronglyMeasurable (ℱ.le s) (h.stronglyMeasurable s) h_int_s]
  · have h_int_t := Martingale.brownianMotion_integrable W t
    have h_decomp : (W.W t : Ω → ℝ) = W.W s + (W.W t - W.W s) := by
      funext ω; simp
    rw [h_decomp]
    filter_upwards [condExp_add h_int_s (h_int_t.sub h_int_s) (ℱ s),
      h.condExp_increment_eq_zero hs hlt] with ω h_add h_zero
    rw [h_add, Pi.add_apply,
      condExp_of_stronglyMeasurable (ℱ.le s) (h.stronglyMeasurable s) h_int_s]
    change W.W s ω + P[(fun ω => W.W t ω - W.W s ω) | ℱ s] ω = W.W s ω
    rw [h_zero, add_zero]

/-- If `W` is a Brownian motion for `ℱ`, it is one for every filtration `𝒢` to which it is adapted
and with `𝒢 s ≤ ℱ s ⊔ m s` for σ-algebras `m s` independent of the join of `ℱ s` with the
σ-algebra generated by the increments of `W` after `s`. -/
theorem of_le_sup (h : IsBrownianFiltration W ℱ) {𝒢 : Filtration ℝ ‹MeasurableSpace Ω›}
    (hadapted : ∀ t, Measurable[𝒢 t] (W.W t)) {m : ℝ → MeasurableSpace Ω}
    (hm : ∀ s, m s ≤ ‹MeasurableSpace Ω›) (hle : ∀ s, 𝒢 s ≤ ℱ s ⊔ m s)
    (hind : ∀ ⦃s : ℝ⦄, 0 ≤ s → Indep (m s) (ℱ s ⊔ ⨆ t ∈ Set.Ioi s,
      MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) P) :
    IsBrownianFiltration W 𝒢 where
  measurable := hadapted
  indep_future s hs := indep_of_indep_of_le_left
    (Probability.indep_sup_left_of_indep (ℱ.le s) (hm s)
      (iSup₂_le fun t _ => ((W.measurable_eval t).sub (W.measurable_eval s)).comap_le)
      (h.indep_future hs) (hind hs))
    (hle s)

end IsBrownianFiltration

end LevyStochCalc.Brownian
