/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.MathlibBridge
import LevyStochCalc.Brownian.Martingale
import LevyStochCalc.Probability.TrivialSigma

/-!
# Independence of the past of a Brownian motion from its future increments

For `0 ≤ s`, the natural filtration `⨆ u ≤ s, σ(W u)` of a Brownian motion is independent of the
σ-algebra `⨆ t > s, σ(W t - W s)` generated by the whole family of increments based at `s`, and
of the σ-algebra generated by the increments `W t - W r` over the subintervals `[r, t]` of
`[s, ∞)`. This is the σ-algebra form of the weak Markov property, and it strengthens the
generator-wise field `BrownianMotion.joint_increment_independent`, which pairs the past with a
single increment.

The past is read through the path map `ω ↦ (W u ω)_{u ≤ s}` on `[0, s]` and through the
null-or-conull σ-algebra at the negative times, where `W` vanishes almost surely.

## Main statements

* `BrownianMotion.indep_naturalFiltration_future` — independence of the natural filtration at `s`
  from the family of increments based at `s`.
* `BrownianMotion.indep_naturalFiltration_increments` — independence of the natural filtration at
  `s` from the family of increments over subintervals of `[s, ∞)`.
-/

namespace LevyStochCalc.Brownian

open MeasureTheory ProbabilityTheory
open scoped NNReal

universe u

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]

namespace BrownianMotion

/-- **Weak Markov property, σ-algebra form.** For `0 ≤ s` the natural filtration of a Brownian
motion at time `s` is independent of the σ-algebra generated by all increments `W t - W s`,
`t > s`. -/
theorem indep_naturalFiltration_future (W : BrownianMotion P) {s : ℝ} (hs : 0 ≤ s) :
    Indep (Martingale.naturalFiltration W s)
      (⨆ t ∈ Set.Ioi s, MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) P := by
  have hs₀ : ((Real.toNNReal s : ℝ≥0) : ℝ) = s := Real.coe_toNNReal s hs
  -- The past path on `[0, s]` is independent of the whole shifted increment path.
  have hindep :
      Indep (MeasurableSpace.comap
          (fun ω (r : Set.Iic (Real.toNNReal s)) => W.W ((r : ℝ≥0) : ℝ) ω) inferInstance)
        (MeasurableSpace.comap
          (fun ω (r : ℝ≥0) => W.W ((Real.toNNReal s + r : ℝ≥0) : ℝ) ω
            - W.W ((Real.toNNReal s : ℝ≥0) : ℝ) ω) inferInstance) P :=
    (W.isPreBrownianReal.indepFun_shift (Real.toNNReal s)).symm
  -- Each increment based at `s` is a coordinate of the shifted increment path.
  have hfut : (⨆ t ∈ Set.Ioi s,
        MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance)
      ≤ MeasurableSpace.comap
        (fun ω (r : ℝ≥0) => W.W ((Real.toNNReal s + r : ℝ≥0) : ℝ) ω
          - W.W ((Real.toNNReal s : ℝ≥0) : ℝ) ω) inferInstance := by
    refine iSup₂_le fun t ht => ?_
    have ht0 : (0 : ℝ) ≤ t := hs.trans (Set.mem_Ioi.mp ht).le
    have hst : Real.toNNReal s ≤ Real.toNNReal t :=
      Real.toNNReal_le_toNNReal (Set.mem_Ioi.mp ht).le
    have hfun : (fun ω => W.W t ω - W.W s ω)
        = (fun p : ℝ≥0 → ℝ => p (Real.toNNReal t - Real.toNNReal s))
          ∘ (fun ω (r : ℝ≥0) => W.W ((Real.toNNReal s + r : ℝ≥0) : ℝ) ω
              - W.W ((Real.toNNReal s : ℝ≥0) : ℝ) ω) := by
      funext ω
      simp only [Function.comp_apply, add_tsub_cancel_of_le hst, Real.coe_toNNReal t ht0, hs₀]
    rw [hfun]
    exact Measurable.comap_le ((measurable_pi_apply _).comp (Measurable.of_comap_le le_rfl))
  -- Each generator of the natural filtration at a nonnegative time is a coordinate of the past
  -- path; the generators at negative times are almost surely constant.
  have hnat : Martingale.naturalFiltration W s
      ≤ MeasurableSpace.comap
          (fun ω (r : Set.Iic (Real.toNNReal s)) => W.W ((r : ℝ≥0) : ℝ) ω) inferInstance
        ⊔ Probability.trivialSigma ‹MeasurableSpace Ω› P := by
    have hseq : Martingale.naturalFiltration W s
        = ⨆ j ≤ s, MeasurableSpace.comap (W.W j) inferInstance := rfl
    rw [hseq]
    refine iSup₂_le fun j hj => ?_
    rcases le_or_gt 0 j with hj0 | hj0
    · refine le_sup_of_le_left ?_
      have hjs : Real.toNNReal j ≤ Real.toNNReal s := Real.toNNReal_le_toNNReal hj
      have hfun : W.W j
          = (fun p : Set.Iic (Real.toNNReal s) → ℝ => p ⟨Real.toNNReal j, hjs⟩)
            ∘ (fun ω (r : Set.Iic (Real.toNNReal s)) => W.W ((r : ℝ≥0) : ℝ) ω) := by
        funext ω
        show W.W j ω = W.W ((Real.toNNReal j : ℝ≥0) : ℝ) ω
        rw [Real.coe_toNNReal j hj0]
      rw [hfun]
      exact Measurable.comap_le ((measurable_pi_apply _).comp (Measurable.of_comap_le le_rfl))
    · exact le_sup_of_le_right
        (Probability.comap_le_trivialSigma (y := 0) (W.measurable_eval j) (W.negative_zero j hj0))
  refine indep_of_indep_of_le_left (Probability.IsTrivialSigma.indep_sup ?_
    Probability.trivialSigma_le ?_ Probability.isTrivialSigma_trivialSigma
    (indep_of_indep_of_le_right hindep hfut)) hnat
  · exact Measurable.comap_le (measurable_pi_lambda _ fun r => W.measurable_eval ((r : ℝ≥0) : ℝ))
  · exact iSup₂_le fun t _ => Measurable.comap_le
      ((W.measurable_eval t).sub (W.measurable_eval s))

/-- For `0 ≤ s` the natural filtration of a Brownian motion at time `s` is independent of the
σ-algebra generated by all increments `W t - W r` with `s ≤ r < t`. -/
theorem indep_naturalFiltration_increments (W : BrownianMotion P) {s : ℝ} (hs : 0 ≤ s) :
    Indep (Martingale.naturalFiltration W s)
      (⨆ r ∈ Set.Ici s, ⨆ t ∈ Set.Ioi r,
        MeasurableSpace.comap (fun ω => W.W t ω - W.W r ω) inferInstance) P := by
  refine indep_of_indep_of_le_right (W.indep_naturalFiltration_future hs) ?_
  have hbase : ∀ u : ℝ, s ≤ u →
      Measurable[⨆ t ∈ Set.Ioi s,
          MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance]
        (fun ω => W.W u ω - W.W s ω) := by
    intro u hu
    rcases eq_or_lt_of_le hu with h | h
    · have hz : (fun ω => W.W u ω - W.W s ω) = fun _ : Ω => (0 : ℝ) := by
        funext ω; rw [← h]; ring
      rw [hz]
      exact measurable_const
    · exact Measurable.of_comap_le (le_iSup₂_of_le u (Set.mem_Ioi.mpr h) le_rfl)
  refine iSup₂_le fun r hr => iSup₂_le fun t ht => ?_
  have hsr : s ≤ r := Set.mem_Ici.mp hr
  have hst : s ≤ t := hsr.trans (Set.mem_Ioi.mp ht).le
  have hfun : (fun ω => W.W t ω - W.W r ω)
      = fun ω => (W.W t ω - W.W s ω) - (W.W r ω - W.W s ω) := by
    funext ω; ring
  rw [hfun]
  exact Measurable.comap_le ((hbase t hst).sub (hbase r hsr))

end BrownianMotion

end LevyStochCalc.Brownian
