/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.Martingale

/-!
# Conditional expectations of Brownian increments

For a Brownian motion `W` and times `0 ≤ s < t`, the σ-algebra generated by the increment
`W_t − W_s` is independent of the natural filtration `ℱ_s`, so that `𝔼[W_t − W_s | ℱ_s] = 0`,
`𝔼[(W_t − W_s)² | ℱ_s] = t − s` and `𝔼[W_s (W_t − W_s) | ℱ_s] = 0` almost surely. The
variance identity rests on the second moment `∫ x² ∂(gaussianReal 0 v) = v` of a centred
Gaussian law.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace LevyStochCalc.Brownian.Martingale

universe u

section ConditionalExpectations
variable {Ω : Type u} [MeasurableSpace Ω]

/-- **σ-algebra-level increment independence.** The σ-algebra generated by the
increment `W_t − W_s` is independent (under `P`) of the natural filtration
`(naturalFiltration W) s`. Stronger than the derived pairwise statement
`BrownianMotion.increment_independent`. -/
lemma increment_indep_naturalFiltration_aux
    {P : Measure Ω} [IsProbabilityMeasure P]
    (W : LevyStochCalc.Brownian.BrownianMotion P)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    ProbabilityTheory.Indep
      ((naturalFiltration W) s)
      (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance)
      P := by
  -- The natural filtration's σ-algebra at s equals `⨆ j ∈ Set.Iic s, σ(W j)`,
  -- which is exactly the structural `joint_increment_independent` field.
  have h_eq : ((naturalFiltration W) s : MeasurableSpace Ω)
      = ⨆ j ∈ Set.Iic s, MeasurableSpace.comap (W.W j) inferInstance := by
    show (naturalFiltration W).seq s = _
    unfold naturalFiltration MeasureTheory.Filtration.natural
    rfl
  rw [h_eq]
  exact W.joint_increment_independent hs hst

/-- The conditional expectation of a Brownian increment `W_t − W_s`, `0 ≤ s < t`, given a
σ-algebra `ℱ s` independent of it vanishes. -/
lemma condExp_increment_eq_zero_of_indep
    {P : Measure Ω} [IsProbabilityMeasure P]
    (W : LevyStochCalc.Brownian.BrownianMotion P)
    (ℱ : MeasureTheory.Filtration ℝ ‹MeasurableSpace Ω›)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t)
    (hind : ProbabilityTheory.Indep (ℱ s)
      (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) P) :
    P[(fun ω => W.W t ω - W.W s ω) | ℱ s] =ᵐ[P] fun _ => 0 := by
  have h_meas_diff : Measurable (fun ω => W.W t ω - W.W s ω) :=
    (W.measurable_eval t).sub (W.measurable_eval s)
  -- Integrability via Gaussian increment law.
  have h_int_id : MeasureTheory.Integrable (id : ℝ → ℝ)
      (ProbabilityTheory.gaussianReal 0 ⟨t - s, by linarith⟩) :=
    MeasureTheory.memLp_one_iff_integrable.mp
      (ProbabilityTheory.IsGaussian.memLp_id _ 1 (by simp))
  have h_int : MeasureTheory.Integrable (fun ω => W.W t ω - W.W s ω) P := by
    have h_map := W.increment_gaussian hs hst
    have := (MeasureTheory.integrable_map_measure (g := (id : ℝ → ℝ))
      (by fun_prop : MeasureTheory.AEStronglyMeasurable id _)
      h_meas_diff.aemeasurable).mp (h_map ▸ h_int_id)
    simpa using this
  -- Mean zero via Gaussian mean.
  have h_mean : ∫ ω, (W.W t ω - W.W s ω) ∂P = 0 := by
    rw [show ∫ ω, (W.W t ω - W.W s ω) ∂P
          = ∫ x, x ∂(P.map (fun ω => W.W t ω - W.W s ω)) from
      (MeasureTheory.integral_map h_meas_diff.aemeasurable
        (by fun_prop : MeasureTheory.AEStronglyMeasurable (id : ℝ → ℝ) _)).symm]
    rw [W.increment_gaussian hs hst]
    exact ProbabilityTheory.integral_id_gaussianReal
  have hle₁ : MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance
      ≤ ‹MeasurableSpace Ω› := by
    intro u ⟨v, hv, hvu⟩
    rw [← hvu]
    exact h_meas_diff hv
  have hf_sm : @MeasureTheory.StronglyMeasurable Ω ℝ _
      (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance)
      (fun ω => W.W t ω - W.W s ω) := by
    apply Measurable.stronglyMeasurable
    exact Measurable.of_comap_le le_rfl
  have h := MeasureTheory.condExp_indep_eq hle₁ (ℱ.le s) hf_sm hind.symm
  filter_upwards [h] with ω hω
  rw [hω]
  exact h_mean

/-- The conditional expectation of a Brownian increment `W_t − W_s`, `0 ≤ s < t`, given the
natural filtration at time `s` vanishes. -/
lemma condExp_increment_eq_zero_aux
    {P : Measure Ω} [IsProbabilityMeasure P]
    (W : LevyStochCalc.Brownian.BrownianMotion P)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    P[(fun ω => W.W t ω - W.W s ω) | (naturalFiltration W) s] =ᵐ[P]
      fun _ => 0 :=
  condExp_increment_eq_zero_of_indep W (naturalFiltration W) hs hst
    (increment_indep_naturalFiltration_aux W hs hst)

/-- **Gaussian second moment.** `∫ x² ∂(gaussianReal 0 v) = v`. -/
lemma gaussianReal_second_moment (v : NNReal) :
    ∫ x : ℝ, x^2 ∂(ProbabilityTheory.gaussianReal 0 v) = v := by
  have h_var : ProbabilityTheory.variance (fun x : ℝ => x)
      (ProbabilityTheory.gaussianReal 0 v) = v :=
    ProbabilityTheory.variance_fun_id_gaussianReal
  rw [ProbabilityTheory.variance_eq_integral measurable_id'.aemeasurable] at h_var
  simp only [ProbabilityTheory.integral_id_gaussianReal, sub_zero] at h_var
  exact h_var

/-- **Conditional expectation of squared increment is `t - s`.** Combines:
* σ-algebra independence of the increment with the past;
* `gaussianReal_second_moment`: variance of `gaussianReal 0 v` is `v`. -/
lemma condExp_increment_sq_eq_var_aux
    {P : Measure Ω} [IsProbabilityMeasure P]
    (W : LevyStochCalc.Brownian.BrownianMotion P)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    P[(fun ω => (W.W t ω - W.W s ω)^2) | (naturalFiltration W) s] =ᵐ[P]
      fun _ => t - s := by
  have h_meas_diff : Measurable (fun ω => W.W t ω - W.W s ω) :=
    (W.measurable_eval t).sub (W.measurable_eval s)
  have h_meas_sq : Measurable (fun ω => (W.W t ω - W.W s ω)^2) :=
    h_meas_diff.pow_const 2
  -- Integrability via Gaussian increment law (second moment).
  have h_int_id_sq : MeasureTheory.Integrable (fun x : ℝ => x^2)
      (ProbabilityTheory.gaussianReal 0 ⟨t - s, by linarith⟩) := by
    have h_memLp : MeasureTheory.MemLp (id : ℝ → ℝ) 2
        (ProbabilityTheory.gaussianReal 0 ⟨t - s, by linarith⟩) :=
      ProbabilityTheory.IsGaussian.memLp_id _ 2 (by simp)
    have h := h_memLp.integrable_norm_pow (p := 2) (by norm_num)
    convert h using 1
    ext x
    change x^2 = ‖x‖^2
    rw [Real.norm_eq_abs, sq_abs]
  have h_int : MeasureTheory.Integrable (fun ω => (W.W t ω - W.W s ω)^2) P := by
    have h_map := W.increment_gaussian hs hst
    have := (MeasureTheory.integrable_map_measure
      (g := fun x : ℝ => x^2)
      (by fun_prop : MeasureTheory.AEStronglyMeasurable
        (fun x : ℝ => x^2) _)
      h_meas_diff.aemeasurable).mp (h_map ▸ h_int_id_sq)
    simpa [Function.comp_def] using this
  -- Mean = t - s via Gaussian second moment.
  have h_mean : ∫ ω, (W.W t ω - W.W s ω)^2 ∂P = t - s := by
    rw [show ∫ ω, (W.W t ω - W.W s ω)^2 ∂P
          = ∫ x, x^2 ∂(P.map (fun ω => W.W t ω - W.W s ω)) from
      (MeasureTheory.integral_map h_meas_diff.aemeasurable
        (by fun_prop : MeasureTheory.AEStronglyMeasurable
          (fun x : ℝ => x^2) _)).symm]
    rw [W.increment_gaussian hs hst]
    rw [gaussianReal_second_moment]
    rfl
  -- σ-algebra independence: the squared increment is in σ(W_t - W_s).
  -- The σ-algebra generated by (W_t - W_s)^2 is contained in that of (W_t - W_s).
  -- Use the larger σ-algebra and apply Indep.symm.
  have h_indep := (increment_indep_naturalFiltration_aux W hs hst).symm
  have hle₁ :
      MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance
        ≤ ‹MeasurableSpace Ω› := by
    intro u ⟨v, hv, hvu⟩
    rw [← hvu]
    exact h_meas_diff hv
  have hle₂ : (naturalFiltration W).seq s ≤ ‹MeasurableSpace Ω› :=
    (naturalFiltration W).le' s
  have hf_sm : @MeasureTheory.StronglyMeasurable Ω ℝ _
      (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance)
      (fun ω => (W.W t ω - W.W s ω)^2) := by
    have h_id : @Measurable Ω ℝ
        (MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance) _
        (fun ω => W.W t ω - W.W s ω) := Measurable.of_comap_le le_rfl
    exact (h_id.pow_const 2).stronglyMeasurable
  have h := MeasureTheory.condExp_indep_eq hle₁ hle₂ hf_sm h_indep
  filter_upwards [h] with ω hω
  rw [hω]
  exact h_mean

/-- **Cross-term conditional expectation is zero.** For
`B := 2 W_s (W_t - W_s)`, the conditional expectation `E[B | F_s] = 0` a.s.,
because the increment factor has zero conditional expectation
(`condExp_increment_eq_zero_aux`) and `W_s` pulls out by
`condExp_mul_of_aestronglyMeasurable_left`. -/
lemma condExp_cross_increment_eq_zero_aux
    {P : Measure Ω} [IsProbabilityMeasure P]
    (W : LevyStochCalc.Brownian.BrownianMotion P)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    P[(fun ω => 2 * W.W s ω * (W.W t ω - W.W s ω))
      | (naturalFiltration W).seq s] =ᵐ[P] fun _ => 0 := by
  have hW_s_memLp : MeasureTheory.MemLp (W.W s) 2 P := brownianMotion_memLp_2 W s
  have h_inc_memLp : MeasureTheory.MemLp (fun ω => W.W t ω - W.W s ω) 2 P := by
    have h_int_id_2 : MeasureTheory.MemLp (id : ℝ → ℝ) 2
        (ProbabilityTheory.gaussianReal 0 ⟨t - s, by linarith⟩) :=
      ProbabilityTheory.IsGaussian.memLp_id _ 2 (by simp)
    rw [show (fun ω => W.W t ω - W.W s ω)
        = id ∘ (fun ω => W.W t ω - W.W s ω) from rfl]
    rw [← W.increment_gaussian hs hst] at h_int_id_2
    exact (MeasureTheory.memLp_map_measure_iff (by fun_prop)
      ((W.measurable_eval t).sub (W.measurable_eval s)).aemeasurable).mp h_int_id_2
  have hW_s_sm : @MeasureTheory.StronglyMeasurable Ω ℝ _
      ((naturalFiltration W).seq s) (W.W s) :=
    MeasureTheory.Filtration.stronglyAdapted_natural
      (u := W.W) (fun u => (W.measurable_eval u).stronglyMeasurable) s
  have h_inc_zero := condExp_increment_eq_zero_aux W hs hst
  -- Rewrite 2 * W_s * (W_t - W_s) = 2 • (W_s * (W_t - W_s))
  have h_rw : (fun ω => 2 * W.W s ω * (W.W t ω - W.W s ω))
      = (2 : ℝ) • (fun ω => W.W s ω * (W.W t ω - W.W s ω)) := by
    funext ω; simp [Pi.smul_apply]; ring
  rw [h_rw]
  have h_smul := MeasureTheory.condExp_smul (μ := P)
    (m := (naturalFiltration W).seq s) (2 : ℝ)
    (fun ω => W.W s ω * (W.W t ω - W.W s ω))
  have h_int_prod : MeasureTheory.Integrable
      (W.W s * (fun ω => W.W t ω - W.W s ω)) P :=
    hW_s_memLp.integrable_mul h_inc_memLp
  have h_inc_int : MeasureTheory.Integrable
      (fun ω => W.W t ω - W.W s ω) P :=
    h_inc_memLp.integrable (by norm_num)
  have h_pull := MeasureTheory.condExp_mul_of_aestronglyMeasurable_left
    (m := (naturalFiltration W).seq s) (μ := P) (f := W.W s)
    (g := fun ω => W.W t ω - W.W s ω)
    hW_s_sm.aestronglyMeasurable h_int_prod h_inc_int
  filter_upwards [h_smul, h_pull, h_inc_zero] with ω h_smul_ω h_pull_ω h_zero_ω
  rw [h_smul_ω, Pi.smul_apply]
  change (2 : ℝ) • P[fun ω => W.W s ω * (W.W t ω - W.W s ω)
    | (naturalFiltration W).seq s] ω = 0
  have h_eq : (fun ω => W.W s ω * (W.W t ω - W.W s ω))
      = W.W s * (fun ω => W.W t ω - W.W s ω) := rfl
  rw [h_eq, h_pull_ω, Pi.mul_apply, h_zero_ω]
  change (2 : ℝ) • (W.W s ω * 0) = 0
  ring

end ConditionalExpectations

end LevyStochCalc.Brownian.Martingale
