/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.Filtered
import LevyStochCalc.Brownian.Multidim

/-!
# The joint natural filtration of a multidimensional Brownian motion

`sigmaBrownian W` is the σ-algebra generated by all the values of a Brownian motion `W`. The
coordinates of a multidimensional Brownian motion generate independent σ-algebras, so every
coordinate `Wʲ` is a Brownian motion for the joint natural filtration `⨆ i, ℱ^{Wⁱ}`
(`MultidimBrownianMotion.isBrownianFiltration_natural`): the increments of `Wʲ` after time `s`
are independent of `ℱ^{Wʲ} s`, and the other coordinates are independent of `σ(Wʲ)` altogether.
-/

open MeasureTheory ProbabilityTheory

lemma MeasureTheory.Filtration.iSup_apply' {Ω ι : Type*} {m : MeasurableSpace Ω}
    (f : ι → Filtration ℝ m) (s : ℝ) : (⨆ i, f i) s = ⨆ i, f i s := by
  change sSup (Set.range f) s = _
  rw [Filtration.sSup_def, sSup_image, iSup_range]

namespace LevyStochCalc.Brownian

universe u

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P] {d : ℕ}

/-- The σ-algebra generated by all the values of a Brownian motion. -/
noncomputable abbrev sigmaBrownian (W : BrownianMotion P) : MeasurableSpace Ω :=
  ⨆ t, MeasurableSpace.comap (W.W t) inferInstance

lemma sigmaBrownian_le (W : BrownianMotion P) : sigmaBrownian W ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun t => (W.measurable_eval t).comap_le

lemma naturalFiltration_le_sigmaBrownian (W : BrownianMotion P) (s : ℝ) :
    Martingale.naturalFiltration W s ≤ sigmaBrownian W :=
  iSup₂_le fun t _ => le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) t

lemma comap_increment_le_sigmaBrownian (W : BrownianMotion P) (s t : ℝ) :
    MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance ≤ sigmaBrownian W := by
  have ht : Measurable[sigmaBrownian W] (W.W t) :=
    Measurable.of_comap_le (le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) t)
  have hs : Measurable[sigmaBrownian W] (W.W s) :=
    Measurable.of_comap_le (le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) s)
  exact (ht.sub hs).comap_le

/-- `σ(W)` is the σ-algebra generated by the path `ω ↦ (t ↦ W t ω)`. -/
lemma sigmaBrownian_eq_comap_path (W : BrownianMotion P) :
    sigmaBrownian W = MeasurableSpace.comap (fun ω t => W.W t ω) MeasurableSpace.pi := by
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  unfold sigmaBrownian
  congr
  funext t
  rw [MeasurableSpace.comap_comp]
  rfl

/-- The coordinates of a multidimensional Brownian motion generate independent σ-algebras. -/
lemma iIndep_sigmaBrownian (W : Multidim.MultidimBrownianMotion P d) :
    iIndep (fun i => sigmaBrownian (W.W i)) P := by
  have h := W.components_independent
  rw [iIndepFun_iff_iIndep] at h
  convert h using 1
  funext i
  exact sigmaBrownian_eq_comap_path (W.W i)

/-- The σ-algebra of the other coordinates is independent of `σ(Wʲ)`. -/
lemma indep_iSup_sigmaBrownian_ne (W : Multidim.MultidimBrownianMotion P d) (j : Fin d) :
    Indep (⨆ i ∈ {i : Fin d | i ≠ j}, sigmaBrownian (W.W i)) (sigmaBrownian (W.W j)) P := by
  have h := indep_iSup_of_disjoint (fun i => sigmaBrownian_le (W.W i)) (iIndep_sigmaBrownian W)
    (S := {i : Fin d | i ≠ j}) (T := {j}) (by simp [Set.disjoint_left])
  simpa using h

namespace Multidim.MultidimBrownianMotion

/-- The joint natural filtration `⨆ i, ℱ^{Wⁱ}` of a multidimensional Brownian motion. -/
noncomputable def naturalFiltration (W : MultidimBrownianMotion P d) :
    Filtration ℝ ‹MeasurableSpace Ω› :=
  ⨆ i, Martingale.naturalFiltration (W.W i)

lemma naturalFiltration_apply (W : MultidimBrownianMotion P d) (s : ℝ) :
    W.naturalFiltration s = ⨆ i, Martingale.naturalFiltration (W.W i) s :=
  Filtration.iSup_apply' _ s

lemma naturalFiltration_coord_le (W : MultidimBrownianMotion P d) (j : Fin d) (s : ℝ) :
    Martingale.naturalFiltration (W.W j) s ≤ W.naturalFiltration s := by
  rw [naturalFiltration_apply]
  exact le_iSup (fun i => Martingale.naturalFiltration (W.W i) s) j

lemma naturalFiltration_le_iSup_sigmaBrownian (W : MultidimBrownianMotion P d) (s : ℝ) :
    W.naturalFiltration s ≤ ⨆ i, sigmaBrownian (W.W i) := by
  rw [naturalFiltration_apply]
  exact iSup_mono fun i => naturalFiltration_le_sigmaBrownian (W.W i) s

/-- Every coordinate of `W` is a Brownian motion for the joint natural filtration. -/
theorem isBrownianFiltration_natural (W : MultidimBrownianMotion P d) (j : Fin d) :
    IsBrownianFiltration (W.W j) W.naturalFiltration := by
  refine (LevyStochCalc.Brownian.isBrownianFiltration_natural (W.W j)).of_le_sup
    (fun t => ((LevyStochCalc.Brownian.isBrownianFiltration_natural (W.W j)).measurable t).mono
      (W.naturalFiltration_coord_le j t) le_rfl)
    (m := fun s => ⨆ i ∈ {i : Fin d | i ≠ j}, Martingale.naturalFiltration (W.W i) s)
    (fun s => iSup₂_le fun i _ => (Martingale.naturalFiltration (W.W i)).le s) ?_ ?_
  · intro s
    rw [naturalFiltration_apply]
    refine iSup_le fun i => ?_
    by_cases hij : i = j
    · subst hij
      exact le_sup_left
    · exact le_sup_of_le_right (le_iSup₂ (f := fun i (_ : i ∈ {i : Fin d | i ≠ j}) =>
        Martingale.naturalFiltration (W.W i) s) i hij)
  · intro s t hs hst
    refine indep_of_indep_of_le_right
      (indep_of_indep_of_le_left (indep_iSup_sigmaBrownian_ne W j) ?_) ?_
    · exact iSup₂_le fun i hi => le_iSup₂_of_le i hi (naturalFiltration_le_sigmaBrownian _ s)
    · exact sup_le (naturalFiltration_le_sigmaBrownian _ s)
        (comap_increment_le_sigmaBrownian (W.W j) s t)

end Multidim.MultidimBrownianMotion

end LevyStochCalc.Brownian
