/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.MeasureTheory.Measure.NullMeasurable

/-!
# Augmenting a sub-σ-algebra by the null sets

The augmentation of `m ≤ m₀` by the `μ`-null sets is the σ-algebra `aug m m₀ μ` of
`m₀`-measurable sets that differ from an `m`-set by a null set; equivalently `m ⊔ 𝒩`, with `𝒩`
generated by the `m₀`-measurable null sets (`aug_eq_sup_nullSigma`).

The point of the file is that **augmentation commutes with a countable antitone infimum**
(`aug_iInf_of_antitone`): for `m₀ ≥ m₀ ≥ m₁ ≥ ⋯`,

  `⨅ n, aug m₀ (m n) μ = aug m₀ (⨅ n, m n) μ`.

The `≥` half is monotonicity. The `≤` half is the `limsup` argument: a set `A` in every
`aug m₀ (m n)` has `m n`-approximants `B n`, and `limsup B n` is `m N`-measurable for every `N`
— dropping the first `N` terms does not change a `limsup`, and after that every `B n` lies in
`m n ≤ m N` — while `A ∆ limsup B n ⊆ ⋃ n, A ∆ B n` is null.

This is the step that lets conditional expectations be compared along a decreasing filtration:
a function a.e.-equal to an `aug m m₀ μ`-measurable function is itself `aug m m₀ μ`-measurable,
so approximants at different indices can be replaced by a single one.

## Main statements

* `aug` — the augmented σ-algebra, and `aug_eq_sup_nullSigma` identifying it as `m ⊔ 𝒩`.
* `aug_iInf_of_antitone` — augmentation commutes with a countable antitone infimum.
-/

open MeasureTheory
open scoped symmDiff

namespace LevyStochCalc.Probability

variable {Ω : Type*}

/-- The augmentation of `m` by the `μ`-null sets inside `m₀`: the `m₀`-measurable sets that
differ from an `m`-measurable set by a `μ`-null set. -/
@[reducible]
def aug (m m₀ : MeasurableSpace Ω) (μ : Measure Ω) : MeasurableSpace Ω where
  MeasurableSet' A := MeasurableSet[m₀] A ∧ ∃ B, MeasurableSet[m] B ∧ μ (A ∆ B) = 0
  measurableSet_empty := ⟨MeasurableSet.empty, ∅, @MeasurableSet.empty Ω m, by simp⟩
  measurableSet_compl := by
    rintro A ⟨hA, B, hB, hAB⟩
    refine ⟨hA.compl, Bᶜ, hB.compl, ?_⟩
    have : Aᶜ ∆ Bᶜ = A ∆ B := by
      ext x; simp only [Set.mem_symmDiff, Set.mem_compl_iff]; tauto
    rwa [this]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨MeasurableSet.iUnion fun i => (hf i).1, ⋃ i, Classical.choose (hf i).2,
      MeasurableSet.iUnion fun i => (Classical.choose_spec (hf i).2).1, ?_⟩
    refine measure_mono_null Set.iUnion_symmDiff_iUnion_subset ?_
    exact measure_iUnion_null fun i => (Classical.choose_spec (hf i).2).2

variable {m m₀ : MeasurableSpace Ω} {μ : Measure Ω}

theorem measurableSet_aug_iff {A : Set Ω} :
    MeasurableSet[aug m m₀ μ] A ↔
      MeasurableSet[m₀] A ∧ ∃ B, MeasurableSet[m] B ∧ μ (A ∆ B) = 0 := Iff.rfl

theorem aug_le : aug m m₀ μ ≤ m₀ := fun _ h => h.1

theorem le_aug (hm : m ≤ m₀) : m ≤ aug m m₀ μ := fun A hA =>
  ⟨hm A hA, A, hA, by simp⟩

theorem aug_mono {m' : MeasurableSpace Ω} (h : m ≤ m') : aug m m₀ μ ≤ aug m' m₀ μ := by
  rintro A ⟨hA, B, hB, hAB⟩
  exact ⟨hA, B, h B hB, hAB⟩

/-- Null sets are augmented-measurable. -/
theorem measurableSet_aug_of_null {A : Set Ω} (hA : MeasurableSet[m₀] A)
    (h : μ A = 0) : MeasurableSet[aug m m₀ μ] A :=
  ⟨hA, ∅, @MeasurableSet.empty Ω m, by simpa using h⟩

/-- A set a.e.-equal to an augmented-measurable set is augmented-measurable. -/
theorem measurableSet_aug_of_ae_eq {A A' : Set Ω}
    (hA' : MeasurableSet[m₀] A') (hA : MeasurableSet[aug m m₀ μ] A) (h : μ (A' ∆ A) = 0) :
    MeasurableSet[aug m m₀ μ] A' := by
  obtain ⟨-, B, hB, hAB⟩ := hA
  refine ⟨hA', B, hB, measure_mono_null (symmDiff_triangle A' A B) ?_⟩
  simpa using measure_union_null h hAB

/-- The σ-algebra generated by the `m₀`-measurable `μ`-null sets. -/
@[reducible]
def nullSigma (m₀ : MeasurableSpace Ω) (μ : Measure Ω) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom {s | MeasurableSet[m₀] s ∧ μ s = 0}

/-- The augmentation is the join of `m` with the null σ-algebra. -/
theorem aug_eq_sup_nullSigma (hm : m ≤ m₀) :
    aug m m₀ μ = m ⊔ nullSigma m₀ μ := by
  refine le_antisymm ?_ (sup_le (le_aug hm) ?_)
  · rintro A ⟨hA, B, hB, hAB⟩
    have hsym : MeasurableSet[m₀] (A ∆ B) :=
      (hA.diff (hm B hB)).union ((hm B hB).diff hA)
    have hmem : MeasurableSet[m ⊔ nullSigma m₀ μ] (A ∆ B) :=
      le_sup_right (α := MeasurableSpace Ω) _
        (MeasurableSpace.measurableSet_generateFrom ⟨hsym, hAB⟩)
    have hB' : MeasurableSet[m ⊔ nullSigma m₀ μ] B := le_sup_left (α := MeasurableSpace Ω) _ hB
    have : A = B ∆ (A ∆ B) := by
      ext x; simp only [Set.mem_symmDiff]; tauto
    rw [this]
    exact (hB'.diff hmem).union (hmem.diff hB')
  · refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨hs, hs0⟩
    exact measurableSet_aug_of_null hs hs0

/-- **Augmentation commutes with a countable antitone infimum.** For a decreasing sequence of
sub-σ-algebras, augmenting each and intersecting is the same as intersecting and augmenting. -/
theorem aug_iInf_of_antitone {mSeq : ℕ → MeasurableSpace Ω} (hanti : Antitone mSeq) :
    ⨅ n, aug (mSeq n) m₀ μ = aug (⨅ n, mSeq n) m₀ μ := by
  refine le_antisymm ?_ (le_iInf fun n => aug_mono (iInf_le _ n))
  intro A hA
  rw [MeasurableSpace.measurableSet_iInf] at hA
  have hA0 : MeasurableSet[m₀] A := (hA 0).1
  choose B hB hAB using fun n => (hA n).2
  set U : ℕ → Set Ω := fun N => ⋃ n, ⋃ (_ : N ≤ n), B n with hUdef
  have hUanti : Antitone U := by
    intro a b hab x hx
    obtain ⟨n, hn⟩ := Set.mem_iUnion.1 hx
    obtain ⟨hbn, hxn⟩ := Set.mem_iUnion.1 hn
    exact Set.mem_iUnion.2 ⟨n, Set.mem_iUnion.2 ⟨hab.trans hbn, hxn⟩⟩
  set C : Set Ω := ⋂ N, U N with hCdef
  refine ⟨hA0, C, ?_, ?_⟩
  · rw [MeasurableSpace.measurableSet_iInf]
    intro N
    have key : C = ⋂ k, U (N + k) := by
      refine subset_antisymm (fun x hx => Set.mem_iInter.2 fun k => Set.mem_iInter.1 hx (N + k))
        (fun x hx => Set.mem_iInter.2 fun N' => ?_)
      exact hUanti (Nat.le_add_left N' N) (Set.mem_iInter.1 hx N')
    rw [key]
    refine MeasurableSet.iInter fun k => MeasurableSet.iUnion fun n => MeasurableSet.iUnion ?_
    intro hn
    exact hanti ((Nat.le_add_right N k).trans hn) _ (hB n)
  · refine measure_mono_null ?_ (measure_iUnion_null hAB)
    intro x hx
    rcases Set.mem_symmDiff.1 hx with ⟨hxA, hxC⟩ | ⟨hxC, hxA⟩
    · obtain ⟨N, hN⟩ : ∃ N, x ∉ U N := by
        by_contra h
        exact hxC (Set.mem_iInter.2 fun N => not_not.1 fun hn => h ⟨N, hn⟩)
      refine Set.mem_iUnion.2 ⟨N, Set.mem_symmDiff.2 (Or.inl ⟨hxA, fun h => hN ?_⟩)⟩
      exact Set.mem_iUnion.2 ⟨N, Set.mem_iUnion.2 ⟨le_refl N, h⟩⟩
    · obtain ⟨n, hn⟩ := Set.mem_iUnion.1 (Set.mem_iInter.1 hxC 0)
      obtain ⟨-, hxn⟩ := Set.mem_iUnion.1 hn
      exact Set.mem_iUnion.2 ⟨n, Set.mem_symmDiff.2 (Or.inr ⟨hxn, hxA⟩)⟩

end LevyStochCalc.Probability
