/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.CharTotal
import LevyStochCalc.Probability.SetIntegralPiSystem
import Mathlib.Analysis.Normed.Lp.MeasurableSpace
import Mathlib.Analysis.InnerProductSpace.PiL2

/-!
# Characters of the finite-dimensional distributions of a process

An integrable complex weight measurable for the σ-algebra a process generates, and integrating to
zero against every character of every finite-dimensional marginal of that process, vanishes almost
everywhere. The σ-algebras generated by the finite-dimensional marginals form a directed family
whose union is a π-system generating the whole σ-algebra of the process.
-/

open MeasureTheory Complex
open scoped ENNReal RealInnerProductSpace

namespace LevyStochCalc.Probability

variable {Ω : Type*} {m0 : MeasurableSpace Ω} {P : Measure Ω} [IsFiniteMeasure P]

/-! ### A directed family of random vectors -/

section Directed

variable {ι : Type*} [Nonempty ι] {V : ι → Type*}
  [∀ i, NormedAddCommGroup (V i)] [∀ i, InnerProductSpace ℝ (V i)]
  [∀ i, MeasurableSpace (V i)] [∀ i, BorelSpace (V i)]
  [∀ i, CompleteSpace (V i)] [∀ i, SecondCountableTopology (V i)]

/-- **Characters of a directed family of random vectors.** An integrable weight measurable for the
supremum of the σ-algebras of a directed family, integrating to zero against every character of
every member, vanishes almost everywhere. -/
theorem ae_eq_zero_of_integral_char_comp_directed {X : ∀ i, Ω → V i}
    (hX : ∀ i, Measurable (X i)) {m : MeasurableSpace Ω} (hm : m ≤ m0)
    (hdir : Directed (· ≤ ·) fun i => MeasurableSpace.comap (X i) inferInstance)
    (hgen : m = ⨆ i, MeasurableSpace.comap (X i) inferInstance)
    {Z : Ω → ℂ} (hZ : Integrable Z P) (hZm : StronglyMeasurable[m] Z)
    (h : ∀ (i : ι) (w : V i), ∫ ω, Complex.exp ((⟪X i ω, w⟫ : ℝ) * Complex.I) * Z ω ∂P = 0) :
    Z =ᵐ[P] 0 :=
  ae_eq_zero_of_forall_setIntegral_eq_zero_directed hm hdir hgen hZ hZm
    fun i _ hs =>
      setIntegral_eq_zero_of_integral_char_comp_mul_eq_zero (mΩ := m0) (hX i) hZ (h i) hs

end Directed

/-! ### The finite-dimensional marginals of a process -/

section Cylinder

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [MeasurableSpace E]
  [BorelSpace E] [CompleteSpace E] [SecondCountableTopology E]
variable {T : Type*}

/-- The vector of the values of a process at the indices of a finite set. -/
def finDimVector (Y : T → Ω → E) (F : Finset T) (ω : Ω) : PiLp 2 fun _ : F => E :=
  WithLp.toLp 2 fun t : F => Y (t : T) ω

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [BorelSpace E] [CompleteSpace E]
  [SecondCountableTopology E] in
theorem measurable_finDimVector {Y : T → Ω → E} (hY : ∀ t, Measurable (Y t)) (F : Finset T) :
    Measurable (finDimVector Y F) :=
  (WithLp.measurable_toLp _ _).comp (measurable_pi_lambda _ fun t => hY (t : T))

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [BorelSpace E] [CompleteSpace E]
  [SecondCountableTopology E] in
/-- The σ-algebra a finite-dimensional marginal generates is the supremum of the σ-algebras its
coordinates generate. -/
theorem comap_finDimVector (Y : T → Ω → E) (F : Finset T) :
    MeasurableSpace.comap (finDimVector Y F) inferInstance
      = ⨆ t ∈ F, MeasurableSpace.comap (Y t) inferInstance := by
  refine le_antisymm ?_ (iSup₂_le fun t ht => ?_)
  · letI mF : MeasurableSpace Ω := ⨆ t ∈ F, MeasurableSpace.comap (Y t) inferInstance
    have hcoord : ∀ t : T, t ∈ F → Measurable[mF] (Y t) := fun t ht =>
      measurable_iff_comap_le.mpr
        (le_iSup₂ (f := fun (s : T) (_ : s ∈ F) => MeasurableSpace.comap (Y s) inferInstance)
          t ht)
    have hvec : Measurable[mF] (finDimVector Y F) :=
      (WithLp.measurable_toLp _ _).comp (measurable_pi_lambda _ fun t => hcoord (t : T) t.2)
    exact hvec.comap_le
  · exact MeasurableSpace.comap_le_comap_of_eq_comp
      (fun x : PiLp 2 fun _ : F => E => WithLp.ofLp x ⟨t, ht⟩)
      ((measurable_pi_apply _).comp (WithLp.measurable_ofLp _ _)) rfl

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [BorelSpace E] [CompleteSpace E]
  [SecondCountableTopology E] in
theorem directed_comap_finDimVector (Y : T → Ω → E) :
    Directed (· ≤ ·)
      fun F : Finset T => MeasurableSpace.comap (finDimVector Y F) inferInstance := by
  classical
  intro F G
  refine ⟨F ∪ G, ?_, ?_⟩ <;> simp only [comap_finDimVector]
  · exact iSup₂_le fun t ht =>
      le_iSup₂ (f := fun (s : T) (_ : s ∈ F ∪ G) => MeasurableSpace.comap (Y s) inferInstance) t
        (Finset.mem_union_left _ ht)
  · exact iSup₂_le fun t ht =>
      le_iSup₂ (f := fun (s : T) (_ : s ∈ F ∪ G) => MeasurableSpace.comap (Y s) inferInstance) t
        (Finset.mem_union_right _ ht)

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [BorelSpace E] [CompleteSpace E]
  [SecondCountableTopology E] in
/-- The finite-dimensional marginals generate the σ-algebra of the process. -/
theorem iSup_comap_finDimVector (Y : T → Ω → E) :
    (⨆ F : Finset T, MeasurableSpace.comap (finDimVector Y F) inferInstance)
      = ⨆ t, MeasurableSpace.comap (Y t) inferInstance := by
  refine le_antisymm (iSup_le fun F => ?_) (iSup_le fun t => ?_)
  · simp only [comap_finDimVector]
    exact iSup₂_le fun t _ => le_iSup (fun s => MeasurableSpace.comap (Y s) inferInstance) t
  · refine le_trans ?_ (le_iSup
      (fun F : Finset T => MeasurableSpace.comap (finDimVector Y F) inferInstance) {t})
    simp only [comap_finDimVector]
    exact le_iSup₂ (f := fun (s : T) (_ : s ∈ ({t} : Finset T)) =>
      MeasurableSpace.comap (Y s) inferInstance) t (Finset.mem_singleton_self t)

/-- **Cylinder characters determine a.e. vanishing.** An integrable weight measurable for the
σ-algebra a process generates, integrating to zero against every character of every
finite-dimensional marginal, vanishes almost everywhere. -/
theorem ae_eq_zero_of_integral_char_cylinder_eq_zero {Y : T → Ω → E}
    (hY : ∀ t, Measurable (Y t)) {m : MeasurableSpace Ω} (hm : m ≤ m0)
    (hgen : m = ⨆ t, MeasurableSpace.comap (Y t) inferInstance)
    {Z : Ω → ℂ} (hZ : Integrable Z P) (hZm : StronglyMeasurable[m] Z)
    (h : ∀ (F : Finset T) (w : F → E),
      ∫ ω, Complex.exp ((∑ t : F, ⟪Y (t : T) ω, w t⟫ : ℝ) * Complex.I) * Z ω ∂P = 0) :
    Z =ᵐ[P] 0 := by
  refine ae_eq_zero_of_integral_char_comp_directed
    (X := fun F : Finset T => finDimVector Y F) (fun F => measurable_finDimVector hY F) hm
    (directed_comap_finDimVector Y) ?_ hZ hZm ?_
  · rw [hgen, ← iSup_comap_finDimVector Y]
  · intro F w
    refine Eq.trans ?_ (h F fun t => WithLp.ofLp w t)
    refine integral_congr_ae (Filter.Eventually.of_forall fun ω => ?_)
    have hinner : (⟪finDimVector Y F ω, w⟫ : ℝ)
        = ∑ t : F, ⟪Y (t : T) ω, WithLp.ofLp w t⟫ := PiLp.inner_apply _ _
    simp only [hinner]

end Cylinder

end LevyStochCalc.Probability
