/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.MeasureTheory.Group.Arithmetic

/-!
# The σ-algebra generated by a tuple of random variables

The σ-algebra a tuple generates is the join of those its components generate. This is what turns a
finite family of generators into a single vector-valued map, the form that limit arguments for
independence take.

## Main statements

* `comap_pi_eq_iSup` — for a family, `σ(ω ↦ (f i ω)ᵢ) = ⨆ i, σ(f i)`.
* `comap_prod_eq_sup` — for a pair, `σ(ω ↦ (g ω, h ω)) = σ(g) ⊔ σ(h)`.
* `comap_add_le` — `σ(f + g)` is below any σ-algebra above `σ(f)` and `σ(g)`.
-/

namespace LevyStochCalc.Probability

variable {Ω : Type*}

/-- The σ-algebra generated by a tuple is the supremum of those generated by its components. -/
theorem comap_pi_eq_iSup {ι : Type*} {𝓨 : ι → Type*} [∀ i, MeasurableSpace (𝓨 i)]
    (f : ∀ i, Ω → 𝓨 i) :
    MeasurableSpace.comap (fun ω i => f i ω) MeasurableSpace.pi
      = ⨆ i, MeasurableSpace.comap (f i) inferInstance := by
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  exact iSup_congr fun i => MeasurableSpace.comap_comp

/-- The σ-algebra generated by a pair is the join of those generated by its components. -/
theorem comap_prod_eq_sup {𝓨 𝓩 : Type*} [MeasurableSpace 𝓨] [MeasurableSpace 𝓩]
    (g : Ω → 𝓨) (h : Ω → 𝓩) :
    MeasurableSpace.comap (fun ω => (g ω, h ω)) inferInstance
      = MeasurableSpace.comap g inferInstance ⊔ MeasurableSpace.comap h inferInstance := by
  show MeasurableSpace.comap (fun ω => (g ω, h ω))
      (MeasurableSpace.comap Prod.fst inferInstance ⊔ MeasurableSpace.comap Prod.snd inferInstance)
    = _
  rw [MeasurableSpace.comap_sup, MeasurableSpace.comap_comp, MeasurableSpace.comap_comp]
  rfl

/-- The σ-algebra generated by a sum is contained in any σ-algebra containing those generated by
the summands. -/
theorem comap_add_le {M : Type*} [MeasurableSpace M] [Add M] [MeasurableAdd₂ M]
    {m : MeasurableSpace Ω} {f g : Ω → M}
    (hf : MeasurableSpace.comap f inferInstance ≤ m)
    (hg : MeasurableSpace.comap g inferInstance ≤ m) :
    MeasurableSpace.comap (fun ω => f ω + g ω) inferInstance ≤ m :=
  ((Measurable.of_comap_le hf).add (Measurable.of_comap_le hg)).comap_le

end LevyStochCalc.Probability
