/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.Probability.Independence.Basic

/-!
# Independence of a join of σ-algebras

If `m₁` is independent of `m₃` and `m₂` is independent of `m₁ ⊔ m₃`, then `m₁ ⊔ m₂` is
independent of `m₃`. The join `m₁ ⊔ m₂` is generated by the π-system of intersections
`A ∩ B` with `A ∈ m₁`, `B ∈ m₂`, on which the product formula is a two-line computation.

Iterating that step along a monotone family `𝒢` gives `indep_iSup_lt_of_indep`: increments that
are measurable one step ahead and independent of the σ-algebra one step behind are *jointly*
independent of the initial σ-algebra.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Probability

variable {Ω : Type*} {m₁ m₂ m₃ mΩ : MeasurableSpace Ω} {P : Measure Ω} [IsProbabilityMeasure P]

/-- The π-system of intersections `A ∩ B` with `A ∈ m₁` and `B ∈ m₂`. -/
def interSets (m₁ m₂ : MeasurableSpace Ω) : Set (Set Ω) :=
  {s | ∃ A B, MeasurableSet[m₁] A ∧ MeasurableSet[m₂] B ∧ s = A ∩ B}

omit [IsProbabilityMeasure P] in
lemma isPiSystem_interSets : IsPiSystem (interSets m₁ m₂) := by
  rintro _ ⟨A, B, hA, hB, rfl⟩ _ ⟨A', B', hA', hB', rfl⟩ -
  exact ⟨A ∩ A', B ∩ B', hA.inter hA', hB.inter hB', by ext x; simp; tauto⟩

omit [IsProbabilityMeasure P] in
lemma sup_eq_generateFrom_interSets : m₁ ⊔ m₂ = MeasurableSpace.generateFrom (interSets m₁ m₂) := by
  refine le_antisymm (sup_le ?_ ?_) (MeasurableSpace.generateFrom_le ?_)
  · intro A hA
    exact MeasurableSpace.measurableSet_generateFrom ⟨A, Set.univ, hA, MeasurableSet.univ,
      (Set.inter_univ A).symm⟩
  · intro B hB
    exact MeasurableSpace.measurableSet_generateFrom ⟨Set.univ, B, MeasurableSet.univ, hB,
      (Set.univ_inter B).symm⟩
  · rintro _ ⟨A, B, hA, hB, rfl⟩
    exact ((le_sup_left : m₁ ≤ m₁ ⊔ m₂) _ hA).inter ((le_sup_right : m₂ ≤ m₁ ⊔ m₂) _ hB)

/-- If `m₁ ⟂ m₃` and `m₂ ⟂ m₁ ⊔ m₃`, then `m₁ ⊔ m₂ ⟂ m₃`. -/
theorem indep_sup_left_of_indep (h₁ : m₁ ≤ mΩ) (h₂ : m₂ ≤ mΩ) (h₃ : m₃ ≤ mΩ)
    (h13 : Indep m₁ m₃ P) (h2 : Indep m₂ (m₁ ⊔ m₃) P) : Indep (m₁ ⊔ m₂) m₃ P := by
  refine IndepSets.indep (sup_le h₁ h₂) h₃ isPiSystem_interSets
    (@MeasurableSpace.isPiSystem_measurableSet Ω m₃) sup_eq_generateFrom_interSets
    (@MeasurableSpace.generateFrom_measurableSet Ω m₃).symm ?_
  rw [IndepSets_iff]
  rintro _ C ⟨A, B, hA, hB, rfl⟩ hC
  have hAC : MeasurableSet[m₁ ⊔ m₃] (A ∩ C) :=
    ((le_sup_left : m₁ ≤ m₁ ⊔ m₃) _ hA).inter ((le_sup_right : m₃ ≤ m₁ ⊔ m₃) _ hC)
  have hA' : MeasurableSet[m₁ ⊔ m₃] A := (le_sup_left : m₁ ≤ m₁ ⊔ m₃) _ hA
  rw [Indep_iff] at h13 h2
  have e1 : A ∩ B ∩ C = B ∩ (A ∩ C) := by ext x; simp; tauto
  have e2 : A ∩ B = B ∩ A := Set.inter_comm A B
  rw [e1, h2 B (A ∩ C) hB hAC, h13 A C hA hC, e2, h2 B A hB hA']
  ring

/-- **Grid induction for independence.** For a monotone family `𝒢` of σ-algebras and increments
`m k` that are `𝒢 (k+1)`-measurable and independent of `𝒢 k`, the join of the first `n`
increments is independent of `𝒢 0`. -/
theorem indep_iSup_lt_of_indep {𝒢 m : ℕ → MeasurableSpace Ω} (hmono : Monotone 𝒢)
    (h𝒢 : ∀ k, 𝒢 k ≤ mΩ) (hm : ∀ k, m k ≤ mΩ) (hle : ∀ k, m k ≤ 𝒢 (k + 1))
    (hindep : ∀ k, Indep (𝒢 k) (m k) P) (n : ℕ) :
    Indep (⨆ k, ⨆ _ : k < n, m k) (𝒢 0) P := by
  induction n with
  | zero => simpa using indep_bot_left (𝒢 0)
  | succ n ih =>
    have hsplit : (⨆ k, ⨆ _ : k < n + 1, m k) = (⨆ k, ⨆ _ : k < n, m k) ⊔ m n := by
      refine le_antisymm (iSup_le fun k => iSup_le fun hk => ?_) (sup_le ?_ ?_)
      · rcases Nat.lt_succ_iff_lt_or_eq.1 hk with hk' | rfl
        · exact le_sup_of_le_left (le_iSup₂_of_le k hk' le_rfl)
        · exact le_sup_right
      · exact iSup_le fun k => iSup_le fun hk =>
          le_iSup₂_of_le k (Nat.lt_succ_of_lt hk) le_rfl
      · exact le_iSup₂_of_le n (Nat.lt_succ_self n) le_rfl
    rw [hsplit]
    refine indep_sup_left_of_indep (iSup_le fun k => iSup_le fun _ => hm k) (hm n) (h𝒢 0) ih ?_
    refine indep_of_indep_of_le_right (hindep n).symm (sup_le ?_ (hmono (Nat.zero_le n)))
    exact iSup_le fun k => iSup_le fun hk => (hle k).trans (hmono hk)

/-- **Independence of a supremum from independence of its finite subjoins.** -/
theorem indep_iSup_of_finset {ι : Type*} {m : ι → MeasurableSpace Ω} {m' : MeasurableSpace Ω}
    (h_le : ∀ i, m i ≤ mΩ) (h_le' : m' ≤ mΩ)
    (h : ∀ S : Finset ι, Indep (⨆ i ∈ S, m i) m' P) :
    Indep (⨆ i, m i) m' P := by
  classical
  have hsup : (⨆ S : Finset ι, ⨆ i ∈ S, m i) = ⨆ i, m i :=
    le_antisymm (iSup_le fun _ => iSup_le fun i => iSup_le fun _ => le_iSup m i)
      (iSup_le fun i => le_iSup_of_le {i} (le_iSup₂_of_le i (Finset.mem_singleton_self i) le_rfl))
  rw [← hsup]
  refine indep_iSup_of_directed_le h
    (fun _ => iSup_le fun i => iSup_le fun _ => h_le i) h_le' fun S T => ⟨S ∪ T, ?_, ?_⟩
  · exact iSup_le fun i => iSup_le fun hi =>
      le_iSup₂_of_le i (Finset.mem_union_left T hi) le_rfl
  · exact iSup_le fun i => iSup_le fun hi =>
      le_iSup₂_of_le i (Finset.mem_union_right S hi) le_rfl

end LevyStochCalc.Probability
