/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.Progressive

/-!
# The marked predictable σ-algebra

The compensated Poisson integral is defined for marked processes that are progressively
measurable, and it is the `L²` limit of left-endpoint approximants; the identification of that
limit with a pathwise integral against the random measure needs the strictly smaller predictable
class. On the time–mark space the predictable σ-algebra is generated by the rectangles
`F × (r, q] × B` with `F` known at `r` and `B` of finite intensity. These rectangles are a
π-system, and a predictable marked process is progressively measurable.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace LevyStochCalc.Probability

universe u v w

variable {Ω : Type u} {mΩ : MeasurableSpace Ω} {E : Type v} [MeasurableSpace E]

/-- The generating rectangles of the marked predictable σ-algebra: an event known at time `r`,
a time interval opening at `r`, and a mark set of finite intensity. -/
def markedPredictableRect (ℱ : Filtration ℝ mΩ) (ν : Measure E) : Set (Set (Ω × ℝ × E)) :=
  {S | ∃ (r q : ℝ) (F : Set Ω) (B : Set E), 0 ≤ r ∧ MeasurableSet[ℱ r] F ∧ MeasurableSet B ∧
    ν B ≠ ⊤ ∧ S = F ×ˢ (Set.Ioc r q ×ˢ B)}

theorem isPiSystem_markedPredictableRect (ℱ : Filtration ℝ mΩ) (ν : Measure E) :
    IsPiSystem (markedPredictableRect ℱ ν) := by
  rintro _ ⟨r₁, q₁, F₁, B₁, hr₁, hF₁, hB₁, hν₁, rfl⟩ _ ⟨r₂, q₂, F₂, B₂, hr₂, hF₂, hB₂, hν₂, rfl⟩ _
  refine ⟨max r₁ r₂, min q₁ q₂, F₁ ∩ F₂, B₁ ∩ B₂, le_max_of_le_left hr₁, ?_, hB₁.inter hB₂, ?_,
    ?_⟩
  · exact (ℱ.mono (le_max_left r₁ r₂) _ hF₁).inter (ℱ.mono (le_max_right r₁ r₂) _ hF₂)
  · exact ne_top_of_le_ne_top hν₁ (measure_mono Set.inter_subset_left)
  · rw [Set.prod_inter_prod, Set.prod_inter_prod, Set.Ioc_inter_Ioc]

/-- The marked predictable σ-algebra of a filtration on the time–mark space. -/
@[implicit_reducible]
def markedPredictableSigma (ℱ : Filtration ℝ mΩ) (ν : Measure E) :
    MeasurableSpace (Ω × ℝ × E) :=
  MeasurableSpace.generateFrom (markedPredictableRect ℱ ν)

/-- A marked process is *predictable* for `ℱ` when it is measurable for the marked predictable
σ-algebra. -/
def MarkedPredictable {F : Type w} [MeasurableSpace F] (ℱ : Filtration ℝ mΩ) (ν : Measure E)
    (ψ : Ω → ℝ → E → F) : Prop :=
  Measurable[markedPredictableSigma ℱ ν] fun p : Ω × ℝ × E => ψ p.1 p.2.1 p.2.2

section Deterministic

variable {ℱ : Filtration ℝ mΩ} {ν : Measure E}

/-- A window of finite mark measure is a predictable rectangle. -/
theorem measurableSet_univ_prod_window_self (ℱ : Filtration ℝ mΩ) (T : ℝ) {B : Set E}
    (hB : MeasurableSet B) (hBν : ν B ≠ ⊤) :
    MeasurableSet[markedPredictableSigma ℱ ν]
      ((Set.univ : Set Ω) ×ˢ (Set.Ioc (0 : ℝ) T ×ˢ B)) :=
  MeasurableSpace.measurableSet_generateFrom
    ⟨0, T, Set.univ, B, le_rfl, MeasurableSet.univ, hB, hBν, rfl⟩

/-- Every measurable time set, cut to a window of finite mark measure, is predictable. -/
theorem measurableSet_univ_prod_timeInter {T : ℝ} {B : Set E} (hB : MeasurableSet B)
    (hBν : ν B ≠ ⊤) {S : Set ℝ} (hS : MeasurableSet S) :
    MeasurableSet[markedPredictableSigma ℱ ν]
      ((Set.univ : Set Ω) ×ˢ ((S ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)) := by
  have hwin := measurableSet_univ_prod_window_self ℱ T hB hBν
  refine MeasurableSpace.induction_on_inter (C := fun S _ =>
      MeasurableSet[markedPredictableSigma ℱ ν]
        ((Set.univ : Set Ω) ×ˢ ((S ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)))
    (borel_eq_generateFrom_Iic ℝ) isPiSystem_Iic ?_ ?_ ?_ ?_ S hS
  · have hzero : (Set.univ : Set Ω) ×ˢ (((∅ : Set ℝ) ∩ Set.Ioc (0 : ℝ) T) ×ˢ B) = ∅ := by
      simp
    rw [hzero]
    exact @MeasurableSet.empty _ (markedPredictableSigma ℱ ν)
  · rintro t ⟨a, rfl⟩
    have hset : Set.Iic a ∩ Set.Ioc (0 : ℝ) T = Set.Ioc (0 : ℝ) (min a T) := by
      ext x
      simp only [Set.mem_inter_iff, Set.mem_Iic, Set.mem_Ioc, le_min_iff]
      tauto
    rw [hset]
    exact MeasurableSpace.measurableSet_generateFrom
      ⟨0, min a T, Set.univ, B, le_rfl, MeasurableSet.univ, hB, hBν, rfl⟩
  · intro t _ iht
    have hset : (Set.univ : Set Ω) ×ˢ ((tᶜ ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)
        = ((Set.univ : Set Ω) ×ˢ (Set.Ioc (0 : ℝ) T ×ˢ B))
          \ ((Set.univ : Set Ω) ×ˢ ((t ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)) := by
      ext p
      simp only [Set.mem_prod, Set.mem_univ, true_and, Set.mem_sdiff, Set.mem_inter_iff,
        Set.mem_compl_iff, not_and]
      tauto
    rw [hset]
    exact hwin.diff iht
  · intro f _ _ ihf
    have hset : (Set.univ : Set Ω) ×ˢ (((⋃ i, f i) ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)
        = ⋃ i, ((Set.univ : Set Ω) ×ˢ ((f i ∩ Set.Ioc (0 : ℝ) T) ×ˢ B)) := by
      ext p
      simp only [Set.mem_prod, Set.mem_univ, true_and, Set.mem_iUnion, Set.mem_inter_iff]
      tauto
    rw [hset]
    exact MeasurableSet.iUnion ihf

/-- Every measurable time–mark set, cut to a window of finite mark measure, is predictable. -/
theorem measurableSet_univ_prod_window {T : ℝ} {A : Set E} (hA : MeasurableSet A)
    (hAν : ν A ≠ ⊤) {D : Set (ℝ × E)} (hD : MeasurableSet D) :
    MeasurableSet[markedPredictableSigma ℱ ν]
      ((Set.univ : Set Ω) ×ˢ (D ∩ Set.Ioc (0 : ℝ) T ×ˢ A)) := by
  have hwin := measurableSet_univ_prod_window_self ℱ T hA hAν
  refine MeasurableSpace.induction_on_inter (C := fun D _ =>
      MeasurableSet[markedPredictableSigma ℱ ν]
        ((Set.univ : Set Ω) ×ˢ (D ∩ Set.Ioc (0 : ℝ) T ×ˢ A)))
    generateFrom_prod.symm isPiSystem_prod ?_ ?_ ?_ ?_ D hD
  · have hzero : (Set.univ : Set Ω) ×ˢ ((∅ : Set (ℝ × E)) ∩ Set.Ioc (0 : ℝ) T ×ˢ A) = ∅ := by
      simp
    rw [hzero]
    exact @MeasurableSet.empty _ (markedPredictableSigma ℱ ν)
  · rintro t ⟨S, hS, B, hB, rfl⟩
    rw [Set.prod_inter_prod]
    exact measurableSet_univ_prod_timeInter (hB.inter hA)
      (ne_top_of_le_ne_top hAν (measure_mono Set.inter_subset_right)) hS
  · intro t _ iht
    have hset : (Set.univ : Set Ω) ×ˢ (tᶜ ∩ Set.Ioc (0 : ℝ) T ×ˢ A)
        = ((Set.univ : Set Ω) ×ˢ (Set.Ioc (0 : ℝ) T ×ˢ A))
          \ ((Set.univ : Set Ω) ×ˢ (t ∩ Set.Ioc (0 : ℝ) T ×ˢ A)) := by
      ext p
      simp only [Set.mem_prod, Set.mem_univ, true_and, Set.mem_sdiff, Set.mem_inter_iff,
        Set.mem_compl_iff, not_and]
      tauto
    rw [hset]
    exact hwin.diff iht
  · intro f _ _ ihf
    have hset : (Set.univ : Set Ω) ×ˢ ((⋃ i, f i) ∩ Set.Ioc (0 : ℝ) T ×ˢ A)
        = ⋃ i, ((Set.univ : Set Ω) ×ˢ (f i ∩ Set.Ioc (0 : ℝ) T ×ˢ A)) := by
      ext p
      simp only [Set.mem_prod, Set.mem_univ, true_and, Set.mem_iUnion, Set.mem_inter_iff]
      tauto
    rw [hset]
    exact MeasurableSet.iUnion ihf

/-- **A measurable function of the time and the mark, carried by a window of finite mark
measure, is predictable.** -/
theorem markedPredictable_of_measurable_window {T : ℝ} {A : Set E} (hA : MeasurableSet A)
    (hAν : ν A ≠ ⊤) {f : ℝ × E → ℝ} (hf : Measurable f)
    (hsupp : ∀ p : ℝ × E, p ∉ Set.Ioc (0 : ℝ) T ×ˢ A → f p = 0) :
    MarkedPredictable ℱ ν fun (_ : Ω) (s : ℝ) (e : E) => f (s, e) := by
  intro U hU
  have hwin := measurableSet_univ_prod_window_self ℱ T hA hAν
  have hcut := measurableSet_univ_prod_window (ℱ := ℱ) (T := T) hA hAν (hf hU)
  by_cases h0 : (0 : ℝ) ∈ U
  · have hset : (fun p : Ω × ℝ × E => f p.2) ⁻¹' U
        = ((Set.univ : Set Ω) ×ˢ (f ⁻¹' U ∩ Set.Ioc (0 : ℝ) T ×ˢ A))
          ∪ ((Set.univ : Set Ω) ×ˢ (Set.Ioc (0 : ℝ) T ×ˢ A))ᶜ := by
      ext p
      constructor
      · intro hp
        by_cases hw : p.2 ∈ Set.Ioc (0 : ℝ) T ×ˢ A
        · exact Or.inl ⟨Set.mem_univ _, hp, hw⟩
        · exact Or.inr fun hmem => hw hmem.2
      · rintro (hp | hp)
        · exact hp.2.1
        · have hw : p.2 ∉ Set.Ioc (0 : ℝ) T ×ˢ A := fun hmem => hp ⟨Set.mem_univ _, hmem⟩
          show f p.2 ∈ U
          rw [hsupp p.2 hw]
          exact h0
    rw [hset]
    exact hcut.union hwin.compl
  · have hset : (fun p : Ω × ℝ × E => f p.2) ⁻¹' U
        = (Set.univ : Set Ω) ×ˢ (f ⁻¹' U ∩ Set.Ioc (0 : ℝ) T ×ˢ A) := by
      ext p
      constructor
      · intro hp
        refine ⟨Set.mem_univ _, hp, ?_⟩
        by_contra hw
        have hz : f p.2 = 0 := hsupp p.2 hw
        have hpU : f p.2 ∈ U := hp
        rw [hz] at hpU
        exact h0 hpU
      · exact fun hp => hp.2.1
    rw [hset]
    exact hcut

end Deterministic

section Progressive

variable {ℱ : Filtration ℝ mΩ} {ν : Measure E}

/-- The marked predictable σ-algebra is coarser than the product σ-algebra. -/
theorem markedPredictableSigma_le (ℱ : Filtration ℝ mΩ) (ν : Measure E) :
    markedPredictableSigma ℱ ν ≤ (inferInstance : MeasurableSpace (Ω × ℝ × E)) := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro _ ⟨r, q, F, B, -, hF, hB, -, rfl⟩
  exact (ℱ.le r _ hF).prod (measurableSet_Ioc.prod hB)

/-- The slice of a predictable set at a sample point is measurable. -/
theorem measurableSet_slice {S : Set (Ω × ℝ × E)}
    (hS : MeasurableSet[markedPredictableSigma ℱ ν] S) (ω : Ω) :
    MeasurableSet (Prod.mk ω ⁻¹' S) :=
  measurable_prodMk_left (markedPredictableSigma_le ℱ ν _ hS)

/-- The times up to `t` in the time–mark space. -/
theorem measurableSet_timeIic (t : ℝ) :
    MeasurableSet[@Prod.instMeasurableSpace Ω (ℝ × E) (ℱ t) inferInstance]
      {p : Ω × ℝ × E | p.2.1 ≤ t} :=
  measurable_snd.fst measurableSet_Iic

/-- Every predictable set, cut down to the times up to `t`, is known at `t`. -/
theorem measurableSet_inter_timeIic {S : Set (Ω × ℝ × E)}
    (hS : MeasurableSet[markedPredictableSigma ℱ ν] S) (t : ℝ) :
    MeasurableSet[@Prod.instMeasurableSpace Ω (ℝ × E) (ℱ t) inferInstance]
      (S ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}) := by
  have hemp : MeasurableSet[@Prod.instMeasurableSpace Ω (ℝ × E) (ℱ t) inferInstance]
      (∅ : Set (Ω × ℝ × E)) :=
    @MeasurableSet.empty (Ω × ℝ × E) (@Prod.instMeasurableSpace Ω (ℝ × E) (ℱ t) inferInstance)
  induction hS with
  | basic S hS =>
    obtain ⟨r, q, F, B, hr, hF, hB, -, rfl⟩ := hS
    by_cases hrt : r < t
    · have hset : (F ×ˢ (Set.Ioc r q ×ˢ B)) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}
          = F ×ˢ (Set.Ioc r (min q t) ×ˢ B) := by
        ext p
        simp only [Set.mem_inter_iff, Set.mem_prod, Set.mem_Ioc, Set.mem_setOf_eq, le_min_iff]
        tauto
      rw [hset]
      exact (ℱ.mono hrt.le _ hF).prod (measurableSet_Ioc.prod hB)
    · have hset : (F ×ˢ (Set.Ioc r q ×ˢ B)) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t} = ∅ := by
        ext p
        simp only [Set.mem_inter_iff, Set.mem_prod, Set.mem_Ioc, Set.mem_setOf_eq,
          Set.mem_empty_iff_false, iff_false, not_and]
        intro hp hq
        exact absurd (lt_of_lt_of_le hp.2.1.1 hq) (not_lt.mpr (not_lt.mp hrt))
      rw [hset]
      exact hemp
  | empty => simp
  | compl S _ ih =>
    have hrw : Sᶜ ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}
        = {p : Ω × ℝ × E | p.2.1 ≤ t} \ (S ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_sdiff, Set.mem_compl_iff, Set.mem_setOf_eq]
      tauto
    rw [hrw]
    exact (measurableSet_timeIic (ℱ := ℱ) (E := E) t).diff ih
  | iUnion f _ ih =>
    have hrw : (⋃ i, f i) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}
        = ⋃ i, f i ∩ {p : Ω × ℝ × E | p.2.1 ≤ t} := Set.iUnion_inter _ _
    rw [hrw]
    exact MeasurableSet.iUnion ih

/-- **A predictable marked process is progressively measurable.** -/
theorem MarkedPredictable.markedProgressivelyMeasurable {ψ : Ω → ℝ → E → ℝ}
    (h : MarkedPredictable ℱ ν ψ) : MarkedProgressivelyMeasurable ℱ ψ := by
  intro t
  refine Measurable.stronglyMeasurable ?_
  have hrw : (fun p : Ω × ℝ × E => (Set.Iic t).indicator (fun s => ψ p.1 s p.2.2) p.2.1)
      = fun p : Ω × ℝ × E =>
        if p.2.1 ≤ t then ψ p.1 p.2.1 p.2.2 else 0 := by
    funext p
    by_cases hp : p.2.1 ≤ t
    · rw [Set.indicator_of_mem (Set.mem_Iic.mpr hp), if_pos hp]
    · rw [Set.indicator_of_notMem (fun hmem => hp (Set.mem_Iic.mp hmem)), if_neg hp]
  rw [hrw]
  intro U hU
  have hpre : MeasurableSet[@Prod.instMeasurableSpace Ω (ℝ × E) (ℱ t) inferInstance]
      (((fun p : Ω × ℝ × E => ψ p.1 p.2.1 p.2.2) ⁻¹' U) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t}) :=
    measurableSet_inter_timeIic (h hU) t
  by_cases h0 : (0 : ℝ) ∈ U
  · have hset : (fun p : Ω × ℝ × E => if p.2.1 ≤ t then ψ p.1 p.2.1 p.2.2 else 0) ⁻¹' U
        = (((fun p : Ω × ℝ × E => ψ p.1 p.2.1 p.2.2) ⁻¹' U) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t})
          ∪ {p : Ω × ℝ × E | p.2.1 ≤ t}ᶜ := by
      ext p
      by_cases hp : p.2.1 ≤ t <;> simp [hp, h0, Set.mem_preimage]
    rw [hset]
    exact hpre.union (measurableSet_timeIic (ℱ := ℱ) (E := E) t).compl
  · have hset : (fun p : Ω × ℝ × E => if p.2.1 ≤ t then ψ p.1 p.2.1 p.2.2 else 0) ⁻¹' U
        = ((fun p : Ω × ℝ × E => ψ p.1 p.2.1 p.2.2) ⁻¹' U) ∩ {p : Ω × ℝ × E | p.2.1 ≤ t} := by
      ext p
      by_cases hp : p.2.1 ≤ t <;> simp [hp, h0, Set.mem_preimage]
    rw [hset]
    exact hpre

end Progressive

end LevyStochCalc.Probability
