/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.Progressive
import Mathlib.Probability.Process.Predictable

/-!
# The predictable σ-algebra of a filtration indexed by `ℝ`

Mathlib's `MeasureTheory.Filtration.predictable` is stated for an index type with a bottom
element. The processes here are indexed by `ℝ`, with the convention that the filtration is
constant on `(-∞, 0]`, so the bottom cell `{⊥} × A` is replaced by `(-∞, 0] × A` with
`A ∈ ℱ 0`. A predictable process is progressively measurable in the sense of
`Probability.ProgressivelyMeasurable`.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace LevyStochCalc.Probability

universe u v

variable {Ω : Type u} {mΩ : MeasurableSpace Ω} {F : Type v} [TopologicalSpace F] [Zero F]

/-- The predictable σ-algebra of a filtration indexed by `ℝ`: the σ-algebra on `ℝ × Ω`
generated by the left-open stochastic intervals `(s, ∞) × A` with `A ∈ ℱ s`, together with the
initial cell `(-∞, 0] × A` with `A ∈ ℱ 0`. -/
@[implicit_reducible]
def predictableSigma (ℱ : Filtration ℝ mΩ) : MeasurableSpace (ℝ × Ω) :=
  MeasurableSpace.generateFrom
    ({s | ∃ A, MeasurableSet[ℱ 0] A ∧ s = Set.Iic (0 : ℝ) ×ˢ A} ∪
      {s | ∃ r A, MeasurableSet[ℱ r] A ∧ s = Set.Ioi r ×ˢ A})

/-- The initial cell is predictable. -/
theorem measurableSet_predictableSigma_Iic_prod {ℱ : Filtration ℝ mΩ} {A : Set Ω}
    (hA : MeasurableSet[ℱ 0] A) :
    MeasurableSet[predictableSigma ℱ] (Set.Iic (0 : ℝ) ×ˢ A) :=
  MeasurableSpace.measurableSet_generateFrom (Or.inl ⟨A, hA, rfl⟩)

/-- A left-open stochastic interval is predictable. -/
theorem measurableSet_predictableSigma_Ioi_prod {ℱ : Filtration ℝ mΩ} {r : ℝ} {A : Set Ω}
    (hA : MeasurableSet[ℱ r] A) :
    MeasurableSet[predictableSigma ℱ] (Set.Ioi r ×ˢ A) :=
  MeasurableSpace.measurableSet_generateFrom (Or.inr ⟨r, A, hA, rfl⟩)

/-- The inclusion of the time-truncated product into `ℝ × Ω` is measurable from the
`ℱ t`-product σ-algebra to the predictable σ-algebra. -/
theorem measurable_inclusion_predictableSigma {ℱ : Filtration ℝ mΩ}
    (hℱ0 : ∀ t : ℝ, t ≤ 0 → ℱ 0 ≤ ℱ t) (t : ℝ) :
    @Measurable (Set.Iic t × Ω) (ℝ × Ω)
      (Subtype.instMeasurableSpace.prod (ℱ t)) (predictableSigma ℱ)
      (fun x => ((x.1 : ℝ), x.2)) := by
  letI : MeasurableSpace (Set.Iic t × Ω) := Subtype.instMeasurableSpace.prod (ℱ t)
  refine measurable_generateFrom ?_
  rintro - (⟨A, hA, rfl⟩ | ⟨r, A, hA, rfl⟩)
  · have hpre : (fun x : Set.Iic t × Ω => ((x.1 : ℝ), x.2)) ⁻¹' (Set.Iic (0 : ℝ) ×ˢ A)
        = (Subtype.val ⁻¹' Set.Iic (0 : ℝ)) ×ˢ A := by
      ext ⟨u, ω⟩; simp
    have hAt : MeasurableSet[ℱ t] A := by
      rcases le_or_gt 0 t with h | h
      · exact ℱ.mono h _ hA
      · exact hℱ0 t h.le _ hA
    rw [hpre]
    exact (measurable_subtype_coe measurableSet_Iic).prod hAt
  · rcases le_or_gt r t with h | h
    · have hpre : (fun x : Set.Iic t × Ω => ((x.1 : ℝ), x.2)) ⁻¹' (Set.Ioi r ×ˢ A)
          = (Subtype.val ⁻¹' Set.Ioi r) ×ˢ A := by
        ext ⟨u, ω⟩; simp
      rw [hpre]
      exact (measurable_subtype_coe measurableSet_Ioi).prod (ℱ.mono h _ hA)
    · have hpre : (fun x : Set.Iic t × Ω => ((x.1 : ℝ), x.2)) ⁻¹' (Set.Ioi r ×ˢ A) = ∅ := by
        ext ⟨u, ω⟩
        have := u.2
        simp only [Set.mem_Iic] at this
        simp only [Set.mem_preimage, Set.mem_prod, Set.mem_Ioi, Set.mem_empty_iff_false,
          iff_false, not_and]
        intro hu
        exact absurd (hu.trans_le this) (not_lt.mpr h.le)
      rw [hpre]
      exact MeasurableSet.empty

/-- A process is predictable for `ℱ` if it is strongly measurable for the predictable
σ-algebra. -/
def Predictable (ℱ : Filtration ℝ mΩ) (H : Ω → ℝ → F) : Prop :=
  StronglyMeasurable[predictableSigma ℱ] fun p : ℝ × Ω => H p.2 p.1

/-- **A predictable process is progressively measurable.** -/
theorem Predictable.progressivelyMeasurable {ℱ : Filtration ℝ mΩ} {H : Ω → ℝ → F}
    (hℱ0 : ∀ t : ℝ, t ≤ 0 → ℱ 0 ≤ ℱ t) (h : Predictable ℱ H) :
    ProgressivelyMeasurable ℱ H := by
  refine ProgressivelyMeasurable.of_isStronglyProgressive fun t => ?_
  letI : MeasurableSpace (ℝ × Ω) := predictableSigma ℱ
  letI : MeasurableSpace (Set.Iic t × Ω) := Subtype.instMeasurableSpace.prod (ℱ t)
  exact StronglyMeasurable.comp_measurable h (measurable_inclusion_predictableSigma hℱ0 t)

end LevyStochCalc.Probability
