/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import Mathlib.MeasureTheory.Function.AEEqOfIntegral
import Mathlib.MeasureTheory.PiSystem
import Mathlib.MeasureTheory.Integral.Bochner.Set

/-!
# Vanishing set integrals over a π-system

A function that integrates to zero over every set of a π-system integrates to zero over every
set of the σ-algebra that π-system generates, because the sets on which it integrates to zero
form a Dynkin system. If the function is also measurable for that σ-algebra, it vanishes.
-/

open MeasureTheory
open scoped ENNReal

namespace LevyStochCalc.Probability

variable {α : Type*} {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]

omit [CompleteSpace E] in
/-- Vanishing set integrals extend from a π-system to the σ-algebra it generates. -/
theorem setIntegral_eq_zero_of_isPiSystem {m m0 : MeasurableSpace α} (hm : m ≤ m0)
    {μ : Measure α} {S : Set (Set α)} (hgen : m = MeasurableSpace.generateFrom S)
    (hpi : IsPiSystem S) {f : α → E} (hf : Integrable f μ)
    (h_univ : ∫ x, f x ∂μ = 0) (h : ∀ s ∈ S, ∫ x in s, f x ∂μ = 0)
    (t : Set α) (ht : MeasurableSet[m] t) :
    ∫ x in t, f x ∂μ = 0 := by
  induction t, ht using MeasurableSpace.induction_on_inter (h_eq := hgen) (h_inter := hpi) with
  | empty => simp
  | basic t ht => exact h t ht
  | compl t htm ht =>
      have hsplit : (∫ x in t, f x ∂μ) + ∫ x in tᶜ, f x ∂μ = ∫ x, f x ∂μ :=
        integral_add_compl (hm t htm) hf
      have := hsplit
      rw [ht, h_univ, zero_add] at this
      exact this
  | iUnion g hdisj hgm hg =>
      rw [integral_iUnion (fun i => hm _ (hgm i)) hdisj hf.integrableOn]
      simp [hg]

/-- A function measurable for a σ-algebra generated by a π-system, and integrating to zero over
every set of that π-system, vanishes almost everywhere. -/
theorem ae_eq_zero_of_forall_setIntegral_eq_zero_isPiSystem {m m0 : MeasurableSpace α}
    (hm : m ≤ m0) {μ : Measure α} [IsFiniteMeasure μ] {S : Set (Set α)}
    (hgen : m = MeasurableSpace.generateFrom S) (hpi : IsPiSystem S) {f : α → E}
    (hf : Integrable f μ) (hfm : StronglyMeasurable[m] f)
    (h_univ : ∫ x, f x ∂μ = 0) (h : ∀ s ∈ S, ∫ x in s, f x ∂μ = 0) :
    f =ᵐ[μ] 0 := by
  haveI : IsFiniteMeasure (μ.trim hm) := isFiniteMeasure_trim hm
  exact ae_eq_zero_of_forall_setIntegral_eq_of_finStronglyMeasurable_trim hm
    (fun s _ _ => hf.integrableOn)
    (fun s hs _ => setIntegral_eq_zero_of_isPiSystem hm hgen hpi hf h_univ h s hs)
    (hfm.finStronglyMeasurable (μ.trim hm))

/-- **A directed family of σ-algebras.** If the sets of a directed family of sub-σ-algebras all
carry vanishing integrals of `f`, and `f` is measurable for their supremum, then `f` vanishes. -/
theorem ae_eq_zero_of_forall_setIntegral_eq_zero_directed {m m0 : MeasurableSpace α}
    (hm : m ≤ m0) {μ : Measure α} [IsFiniteMeasure μ] {ι : Type*} [Nonempty ι]
    {𝒢 : ι → MeasurableSpace α} (hdir : Directed (· ≤ ·) 𝒢) (hgen : m = ⨆ i, 𝒢 i)
    {f : α → E} (hf : Integrable f μ) (hfm : StronglyMeasurable[m] f)
    (h : ∀ i, ∀ s, MeasurableSet[𝒢 i] s → ∫ x in s, f x ∂μ = 0) :
    f =ᵐ[μ] 0 := by
  have hpi : IsPiSystem (⋃ i, {t | MeasurableSet[𝒢 i] t}) := by
    rintro s hs t ht -
    simp only [Set.mem_iUnion, Set.mem_setOf_eq] at hs ht ⊢
    obtain ⟨i, hi⟩ := hs
    obtain ⟨j, hj⟩ := ht
    obtain ⟨k, hik, hjk⟩ := hdir i j
    exact ⟨k, (hik _ hi).inter (hjk _ hj)⟩
  have hgen' : m = MeasurableSpace.generateFrom (⋃ i, {t | MeasurableSet[𝒢 i] t}) := by
    rw [hgen]
    exact (MeasurableSpace.generateFrom_iUnion_measurableSet 𝒢).symm
  have hmem : ∀ s ∈ ⋃ i, {t | MeasurableSet[𝒢 i] t}, ∫ x in s, f x ∂μ = 0 := by
    rintro s hs
    simp only [Set.mem_iUnion, Set.mem_setOf_eq] at hs
    obtain ⟨i, hi⟩ := hs
    exact h i s hi
  have h_univ : ∫ x, f x ∂μ = 0 := by
    have huniv := hmem Set.univ (by
      simp only [Set.mem_iUnion, Set.mem_setOf_eq]
      exact ⟨Classical.arbitrary ι, MeasurableSet.univ⟩)
    simpa using huniv
  exact ae_eq_zero_of_forall_setIntegral_eq_zero_isPiSystem hm hgen' hpi hf hfm h_univ hmem

end LevyStochCalc.Probability
