/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Probability.IndepJoin

/-!
# σ-algebras whose sets are null or conull

A sub-σ-algebra each of whose sets has measure `0` or `1` is independent of every other
sub-σ-algebra, and a σ-algebra generated by an almost-surely constant random variable is of that
kind. Together they let such a factor be dropped from an independence statement.

## Main statements

* `IsTrivialSigma` — the predicate.
* `IsTrivialSigma.indep` — a trivial σ-algebra is independent of everything.
* `isTrivialSigma_comap_of_ae_const` — the σ-algebra of an a.s. constant random variable.
* `IsTrivialSigma.indep_sup` — a trivial factor drops out of an independence statement.
* `trivialSigma` — the σ-algebra of measurable null-or-conull sets, which absorbs a whole family
  of trivial factors at once.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Probability

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}

/-- A sub-σ-algebra is `P`-trivial when each of its sets is null or conull. -/
def IsTrivialSigma (P : Measure Ω) (m : MeasurableSpace Ω) : Prop :=
  ∀ A, MeasurableSet[m] A → P A = 0 ∨ P A = 1

/-- **A trivial σ-algebra is independent of every other one.** -/
theorem IsTrivialSigma.indep [IsProbabilityMeasure P] {m m' : MeasurableSpace Ω}
    (hm : m ≤ mΩ) (h : IsTrivialSigma P m) : Indep m m' P := by
  rw [Indep_iff]
  intro A B hA hB
  rcases h A hA with h0 | h1
  · rw [measure_mono_null Set.inter_subset_left h0, h0, zero_mul]
  · have hAc : P Aᶜ = 0 := by
      rw [prob_compl_eq_one_sub (hm A hA), h1, tsub_self]
    have hsub : B \ Aᶜ ⊆ A ∩ B := fun x hx => ⟨not_not.1 hx.2, hx.1⟩
    have : P (A ∩ B) = P B :=
      le_antisymm (measure_mono Set.inter_subset_right)
        ((measure_sdiff_null hAc).symm.trans_le (measure_mono hsub))
    rw [this, h1, one_mul]

/-- **The σ-algebra generated by an almost-surely constant random variable is trivial.** -/
theorem isTrivialSigma_comap_of_ae_const [IsProbabilityMeasure P] {𝓨 : Type*}
    [MeasurableSpace 𝓨] {f : Ω → 𝓨} {y : 𝓨} (h : ∀ᵐ ω ∂P, f ω = y) :
    IsTrivialSigma P (MeasurableSpace.comap f inferInstance) := by
  rintro _ ⟨S, -, rfl⟩
  by_cases hy : y ∈ S
  · right
    have hae : f ⁻¹' S =ᵐ[P] (Set.univ : Set Ω) := by
      filter_upwards [h] with ω hω
      change (ω ∈ f ⁻¹' S) = (ω ∈ (Set.univ : Set Ω))
      simp [Set.mem_preimage, hω, hy]
    rw [measure_congr hae, measure_univ]
  · left
    have hae : f ⁻¹' S =ᵐ[P] (∅ : Set Ω) := by
      filter_upwards [h] with ω hω
      change (ω ∈ f ⁻¹' S) = (ω ∈ (∅ : Set Ω))
      simp [Set.mem_preimage, hω, hy]
    rw [measure_congr hae, measure_empty]

variable (mΩ P) in
/-- The σ-algebra of measurable sets that are null or conull. Every trivial sub-σ-algebra of
`mΩ` sits inside it, so a whole family of trivial factors can be absorbed at once. -/
@[reducible]
def trivialSigma [IsProbabilityMeasure P] : MeasurableSpace Ω where
  MeasurableSet' A := MeasurableSet[mΩ] A ∧ (P A = 0 ∨ P A = 1)
  measurableSet_empty := ⟨MeasurableSet.empty, Or.inl measure_empty⟩
  measurableSet_compl := by
    rintro A ⟨hA, h⟩
    refine ⟨hA.compl, ?_⟩
    rcases h with h | h
    · right; rw [prob_compl_eq_one_sub hA, h, tsub_zero]
    · left; rw [prob_compl_eq_one_sub hA, h, tsub_self]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨MeasurableSet.iUnion fun n => (hf n).1, ?_⟩
    by_cases h : ∃ n, P (f n) = 1
    · obtain ⟨n, hn⟩ := h
      exact Or.inr (le_antisymm prob_le_one (hn ▸ measure_mono (Set.subset_iUnion f n)))
    · refine Or.inl (measure_iUnion_null fun n => ?_)
      rcases (hf n).2 with h0 | h1
      · exact h0
      · exact absurd ⟨n, h1⟩ h

theorem isTrivialSigma_trivialSigma [IsProbabilityMeasure P] :
    IsTrivialSigma P (trivialSigma mΩ P) := fun _ hA => hA.2

theorem trivialSigma_le [IsProbabilityMeasure P] : trivialSigma mΩ P ≤ mΩ := fun _ hA => hA.1

/-- The σ-algebra generated by an almost-surely constant random variable sits inside the
null-or-conull σ-algebra. -/
theorem comap_le_trivialSigma [IsProbabilityMeasure P] {𝓨 : Type*} [MeasurableSpace 𝓨]
    {f : Ω → 𝓨} {y : 𝓨} (hf : Measurable f) (h : ∀ᵐ ω ∂P, f ω = y) :
    MeasurableSpace.comap f inferInstance ≤ trivialSigma mΩ P := fun A hA =>
  ⟨by obtain ⟨S, hS, rfl⟩ := hA; exact hf hS, isTrivialSigma_comap_of_ae_const h A hA⟩

/-- **A trivial factor can be joined onto either side of an independence statement.** -/
theorem IsTrivialSigma.indep_sup [IsProbabilityMeasure P] {m₁ m₂ m₃ : MeasurableSpace Ω}
    (h₁ : m₁ ≤ mΩ) (h₂ : m₂ ≤ mΩ) (h₃ : m₃ ≤ mΩ) (h : IsTrivialSigma P m₂)
    (h13 : Indep m₁ m₃ P) : Indep (m₁ ⊔ m₂) m₃ P :=
  indep_sup_left_of_indep h₁ h₂ h₃ h13 (h.indep h₂)

end LevyStochCalc.Probability
