/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.VectorIncrement
import LevyStochCalc.Poisson.CompensatedProfileRepr

/-!
# The increment of a Lévy driver over a cell along deterministic mark modes

The compensated step integral of a simple mark profile over `(s, t]` is measurable for the
σ-algebra generated by the counts on the strips over its mark sets, which lie after `s`, so it is
independent of the joint filtration at `s`. The compensated integral of a bounded
square-integrable mark profile is an `L²(P)` limit of such step integrals, hence an almost
everywhere limit along a subsequence, and independence of a σ-algebra passes to almost everywhere
limits.

Over a cell `(s, t]` the `d` Brownian increments of the driver together with the compensated
integrals of a finite family of bounded square-integrable mark profiles form a vector in
`Fin (d + q) → ℝ`, independent of the joint filtration at `s` and measurable for the joint
filtration at `t`.

## Main definitions

* `LevyStochCalc.Driver.levyCellProfileStep` — the increment of a Lévy driver over a cell along
  a finite family of deterministic mark profiles.

## Main statements

* `LevyStochCalc.Driver.LevyDriver.indep_comap_stepIntegral` — the compensated step integral of
  a simple mark profile is independent of the joint filtration at the start of the step.
* `LevyStochCalc.Driver.LevyDriver.indep_comap_compensatedProfile` — the compensated integral of
  a bounded square-integrable mark profile over `(s, t]` is independent of the joint filtration
  at `s`.
* `LevyStochCalc.Driver.LevyDriver.indep_sigmaBrownian_comap_compensatedProfile` — it is
  independent of everything the Brownian coordinates generate.
* `LevyStochCalc.Driver.indep_comap_levyCellProfileStep` — the cell increment is independent of
  the joint filtration at the start of the cell.
* `LevyStochCalc.Driver.measurable_levyCellProfileStep_filtration` — the cell increment is
  measurable for the joint filtration at the end of the cell.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped NNReal ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d q : ℕ}

/-! ### Almost everywhere approximation by compensated step integrals -/

/-- A sequence of simple mark profiles whose compensated step integrals converge almost
everywhere to the compensated integral of a bounded square-integrable mark profile. -/
private theorem exists_seq_tendsto_ae_stepIntegral (N : Poisson.PoissonRandomMeasure P ν)
    {f : E → ℝ} (hf : MemLp f 2 ν) {Cb : ℝ} (hb : ∀ e, |f e| ≤ Cb) {a b : ℝ} (ha : 0 ≤ a)
    (hab : a ≤ b) :
    ∃ (G : ℕ → Poisson.SimpleProfile E ν) (ns : ℕ → ℕ), ∀ᵐ ω ∂P,
      Tendsto (fun i => (G (ns i)).stepIntegral N a b ω) atTop
        (nhds (Poisson.compensatedProfile N f a b ω)) := by
  obtain ⟨G, -, hG⟩ := Poisson.exists_simpleProfile_tendsto_L2 hf hb
  have htim : TendstoInMeasure P (fun n => (G n).stepIntegral N a b) atTop
      (Poisson.compensatedProfile N f a b) :=
    tendstoInMeasure_of_tendsto_eLpNorm (by norm_num)
      (fun n => ((G n).memLp_stepIntegral N ha b).aestronglyMeasurable)
      (Poisson.memLp_compensatedProfile N f a b).aestronglyMeasurable
      (Poisson.tendsto_stepIntegral_compensatedProfile N hf ha hab G hG)
  obtain ⟨ns, -, hae⟩ := htim.exists_seq_tendsto_ae
  exact ⟨G, ns, hae⟩

/-- Simple mark profiles for a finite family of bounded square-integrable mark profiles, and a
common subsequence along which all their compensated step integrals converge almost everywhere to
the compensated integrals of the family. -/
private theorem exists_seq_tendsto_ae_stepIntegral_family
    (N : Poisson.PoissonRandomMeasure P ν) {ζ : Fin q → E → ℝ} (hζm : ∀ r, MemLp (ζ r) 2 ν)
    (hζb : ∀ r, ∃ C, ∀ e, |ζ r e| ≤ C) {a b : ℝ} (ha : 0 ≤ a) (hab : a ≤ b) :
    ∃ (G : Fin q → ℕ → Poisson.SimpleProfile E ν) (ns : ℕ → ℕ), ∀ᵐ ω ∂P,
      ∀ r, Tendsto (fun i => (G r (ns i)).stepIntegral N a b ω) atTop
        (nhds (Poisson.compensatedProfile N (ζ r) a b ω)) := by
  choose Cb hCb using hζb
  choose G hGb hG using fun r => Poisson.exists_simpleProfile_tendsto_L2 (hζm r) (hCb r)
  clear hGb
  set J : Fin q → Ω → ℝ := fun r => Poisson.compensatedProfile N (ζ r) a b with hJ
  set Z : ℕ → Ω → ℝ := fun n ω => ∑ r, ‖(G r n).stepIntegral N a b ω - J r ω‖ with hZ
  have hdiff : ∀ r n, MemLp (fun ω => (G r n).stepIntegral N a b ω - J r ω) 2 P := fun r n =>
    ((G r n).memLp_stepIntegral N ha b).sub (Poisson.memLp_compensatedProfile N (ζ r) a b)
  have hrw : ∀ n, Z n = ∑ r, fun ω => ‖(G r n).stepIntegral N a b ω - J r ω‖ := by
    intro n
    funext ω
    simp [hZ, Finset.sum_apply]
  have hZm : ∀ n, AEStronglyMeasurable (Z n) P := fun n => by
    rw [hrw n]
    exact Finset.aestronglyMeasurable_sum _ fun r _ => (hdiff r n).aestronglyMeasurable.norm
  have hterm : ∀ r, Tendsto
      (fun n => eLpNorm (fun ω => (G r n).stepIntegral N a b ω - J r ω) 2 P) atTop (nhds 0) :=
    fun r => Poisson.tendsto_stepIntegral_compensatedProfile N (hζm r) ha hab (G r) (hG r)
  have hsum : Tendsto (fun n => ∑ r,
      eLpNorm (fun ω => (G r n).stepIntegral N a b ω - J r ω) 2 P) atTop (nhds 0) := by
    have h := tendsto_finsetSum (Finset.univ : Finset (Fin q)) fun r _ => hterm r
    simpa using h
  have hbound : ∀ n, eLpNorm (Z n) 2 P
      ≤ ∑ r, eLpNorm (fun ω => (G r n).stepIntegral N a b ω - J r ω) 2 P := by
    intro n
    rw [hrw n]
    refine (eLpNorm_sum_le (fun r _ => (hdiff r n).aestronglyMeasurable.norm) one_le_two).trans ?_
    exact le_of_eq (Finset.sum_congr rfl fun r _ => eLpNorm_norm _)
  have hZ0 : Tendsto (fun n => eLpNorm (Z n) 2 P) atTop (nhds 0) :=
    tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds hsum (fun _ => zero_le) hbound
  have htim : TendstoInMeasure P Z atTop 0 := by
    refine tendstoInMeasure_of_tendsto_eLpNorm (p := 2) (by norm_num) hZm
      aestronglyMeasurable_zero ?_
    simpa using hZ0
  obtain ⟨ns, -, hae⟩ := htim.exists_seq_tendsto_ae
  refine ⟨G, ns, ?_⟩
  filter_upwards [hae] with ω hω r
  have hle : ∀ i, ‖(G r (ns i)).stepIntegral N a b ω - J r ω‖ ≤ Z (ns i) ω := fun i =>
    Finset.single_le_sum (f := fun r => ‖(G r (ns i)).stepIntegral N a b ω - J r ω‖)
      (fun r _ => norm_nonneg _) (Finset.mem_univ r)
  have hsub : Tendsto (fun i => (G r (ns i)).stepIntegral N a b ω - J r ω) atTop (nhds 0) :=
    squeeze_zero_norm hle (by simpa using hω)
  simpa using hsub.add_const (J r ω)

namespace LevyDriver

variable (D : LevyDriver.{u, v, w} P d ν)

/-! ### Independence of the compensated integral of a mark profile from the past -/

/-- The compensated step integral of a simple mark profile over `(s, t]` generates a σ-algebra
below the one generated by the counts on the strips over its mark sets. -/
theorem comap_stepIntegral_le (G : Poisson.SimpleProfile E ν) (s t : ℝ) :
    MeasurableSpace.comap (G.stepIntegral D.N s t) inferInstance
      ≤ ⨆ k, D.regionSigma (Set.Ioc s t ×ˢ G.B k) :=
  (Poisson.SimpleProfile.stronglyMeasurable_stepIntegral_regionSigma D.N G s t).measurable.comap_le

/-- The compensated step integral of a simple mark profile over `(s, t]` is measurable. -/
theorem measurable_stepIntegral (G : Poisson.SimpleProfile E ν) (s t : ℝ) :
    Measurable (G.stepIntegral D.N s t) :=
  Measurable.of_comap_le ((D.comap_stepIntegral_le G s t).trans
    (iSup_le fun k => (D.regionSigma_le (measurableSet_Ioc.prod (G.B_measurable k))).trans
      (sigmaPoisson_le _)))

/-- **The compensated step integral of a simple mark profile over `(s, t]` is independent of the
joint filtration at `s`.** -/
theorem indep_comap_stepIntegral (G : Poisson.SimpleProfile E ν) (s t : ℝ) :
    Indep (MeasurableSpace.comap (G.stepIntegral D.N s t) inferInstance) (D.filtration s) P :=
  indep_of_indep_of_le_left
    (D.indep_iSup_regionSigma (fun k => Set.Ioc s t ×ˢ G.B k)
      (fun k => measurableSet_Ioc.prod (G.B_measurable k)) s
      (fun _ => Set.prod_mono Set.Ioc_subset_Ioi_self (Set.subset_univ _)))
    (D.comap_stepIntegral_le G s t)

/-- **The compensated integral over `(s, t]` of a bounded square-integrable mark profile is
independent of the joint filtration at `s`.** -/
theorem indep_comap_compensatedProfile {f : E → ℝ} (hf : MemLp f 2 ν) {Cb : ℝ}
    (hb : ∀ e, |f e| ≤ Cb) {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    Indep (MeasurableSpace.comap (Poisson.compensatedProfile D.N f s t) inferInstance)
      (D.filtration s) P := by
  obtain ⟨G, ns, hae⟩ := exists_seq_tendsto_ae_stepIntegral D.N hf hb hs hst.le
  exact (Probability.indep_comap_of_tendsto_ae (D.filtration.le s)
    (fun i => D.measurable_stepIntegral (G (ns i)) s t)
    (Poisson.measurable_compensatedProfile D.N f s t)
    (fun i => (D.indep_comap_stepIntegral (G (ns i)) s t).symm) hae).symm

/-- **The compensated integral over `(s, t]` of a bounded square-integrable mark profile is
independent of everything the Brownian coordinates of the driver generate.** -/
theorem indep_sigmaBrownian_comap_compensatedProfile {f : E → ℝ} (hf : MemLp f 2 ν) {Cb : ℝ}
    (hb : ∀ e, |f e| ≤ Cb) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    Indep (⨆ i, Brownian.sigmaBrownian (D.W.W i))
      (MeasurableSpace.comap (Poisson.compensatedProfile D.N f s t) inferInstance) P := by
  obtain ⟨G, ns, hae⟩ := exists_seq_tendsto_ae_stepIntegral D.N hf hb hs hst
  refine Probability.indep_comap_of_tendsto_ae
    (iSup_le fun i => Brownian.sigmaBrownian_le (D.W.W i))
    (fun i => D.measurable_stepIntegral (G (ns i)) s t)
    (Poisson.measurable_compensatedProfile D.N f s t) (fun i => ?_) hae
  refine indep_of_indep_of_le_right D.indep ?_
  exact (D.comap_stepIntegral_le (G (ns i)) s t).trans
    (iSup_le fun k => D.regionSigma_le (measurableSet_Ioc.prod ((G (ns i)).B_measurable k)))

end LevyDriver

/-! ### The cell increment along deterministic mark modes -/

/-- The increment of a Lévy driver over the cell `(s, t]` along deterministic mark modes: the `d`
Brownian increments in the first `d` coordinates, and in the last `q` coordinates the
representatives, for the joint filtration at `t`, of the compensated integrals over the cell of
the mark profiles `ζ r`. -/
noncomputable def levyCellProfileStep (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (ζ : Fin q → E → ℝ) (ω : Ω) : Fin (d + q) → ℝ :=
  Fin.append (fun j => (D.W.W j).W t ω - (D.W.W j).W s ω)
    (fun r => Poisson.compensatedProfileRepr (D.filtration t) D.N (ζ r) s t ω)

@[simp] theorem levyCellProfileStep_castAdd (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (ζ : Fin q → E → ℝ) (ω : Ω) (j : Fin d) :
    levyCellProfileStep D s t ζ ω (Fin.castAdd q j)
      = (D.W.W j).W t ω - (D.W.W j).W s ω := by
  simp [levyCellProfileStep]

@[simp] theorem levyCellProfileStep_natAdd (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (ζ : Fin q → E → ℝ) (ω : Ω) (r : Fin q) :
    levyCellProfileStep D s t ζ ω (Fin.natAdd d r)
      = Poisson.compensatedProfileRepr (D.filtration t) D.N (ζ r) s t ω := by
  simp [levyCellProfileStep]

/-- The cell increment along deterministic mark modes is measurable. -/
theorem measurable_levyCellProfileStep (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (ζ : Fin q → E → ℝ) : Measurable (levyCellProfileStep D s t ζ) := by
  refine measurable_pi_lambda _ fun k => ?_
  refine Fin.addCases ?_ ?_ k
  · intro j
    simp only [levyCellProfileStep_castAdd]
    exact ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval s)
  · intro r
    simp only [levyCellProfileStep_natAdd]
    exact Poisson.measurable_compensatedProfileRepr (D.filtration t) (D.filtration.le t) D.N
      (ζ r) s t

/-- **The cell increment along deterministic mark modes is measurable for the joint filtration at
the end of the cell.** -/
theorem measurable_levyCellProfileStep_filtration (D : LevyDriver.{u, v, w} P d ν) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) {ζ : Fin q → E → ℝ} (hζm : ∀ r, MemLp (ζ r) 2 ν)
    (hζb : ∀ r, ∃ C, ∀ e, |ζ r e| ≤ C) :
    Measurable[D.filtration t] (levyCellProfileStep D s t ζ) := by
  classical
  choose Cb hCb using hζb
  refine Measurable.of_comap_le ?_
  rw [show MeasurableSpace.comap (levyCellProfileStep D s t ζ) inferInstance
      = ⨆ k, MeasurableSpace.comap (fun ω => levyCellProfileStep D s t ζ ω k) inferInstance from
    Probability.comap_pi_eq_iSup fun k ω => levyCellProfileStep D s t ζ ω k]
  refine iSup_le fun k => ?_
  refine Fin.addCases ?_ ?_ k
  · intro j
    simp only [funext fun ω => levyCellProfileStep_castAdd D s t ζ ω j]
    exact (((D.isBrownianFiltration j).measurable t).sub
      (((D.isBrownianFiltration j).measurable s).mono (D.filtration.mono hst) le_rfl)).comap_le
  · intro r
    simp only [funext fun ω => levyCellProfileStep_natAdd D s t ζ ω r]
    obtain ⟨G, -, hG⟩ := Poisson.exists_simpleProfile_tendsto_L2 (hζm r) (hCb r)
    refine (Poisson.stronglyMeasurable_compensatedProfileRepr (D.filtration t)
      (D.filtration.le t) D.N (hζm r) hs hst G hG fun n => ?_).measurable.comap_le
    refine ((Poisson.SimpleProfile.stronglyMeasurable_stepIntegral_regionSigma D.N (G n) s
      t).mono (iSup_le fun k => ?_)).aestronglyMeasurable
    exact (D.isPoissonFiltration.measurable
      (Set.prod_mono Set.Ioc_subset_Iic_self (Set.subset_univ _))
      (measurableSet_Ioc.prod ((G n).B_measurable k))).comap_le

/-- **The cell increment along deterministic mark modes is independent of the joint filtration at
the start of the cell.** -/
theorem indep_comap_levyCellProfileStep (D : LevyDriver.{u, v, w} P d ν) {s t : ℝ} (hs : 0 ≤ s)
    (hst : s < t) {ζ : Fin q → E → ℝ} (hζm : ∀ r, MemLp (ζ r) 2 ν)
    (hζb : ∀ r, ∃ C, ∀ e, |ζ r e| ≤ C) :
    Indep (MeasurableSpace.comap (levyCellProfileStep D s t ζ) inferInstance)
      (D.filtration s) P := by
  classical
  obtain ⟨G, ns, hae⟩ := exists_seq_tendsto_ae_stepIntegral_family D.N hζm hζb hs hst.le
  set X : ℕ → Ω → Fin (d + q) → ℝ := fun i ω =>
    Fin.append (fun j => (D.W.W j).W t ω - (D.W.W j).W s ω)
      (fun r => (G r (ns i)).stepIntegral D.N s t ω) with hXdef
  have hXcast : ∀ i ω (j : Fin d), X i ω (Fin.castAdd q j)
      = (D.W.W j).W t ω - (D.W.W j).W s ω := by
    intro i ω j
    simp [hXdef]
  have hXnat : ∀ i ω (r : Fin q), X i ω (Fin.natAdd d r)
      = (G r (ns i)).stepIntegral D.N s t ω := by
    intro i ω r
    simp [hXdef]
  have hXm : ∀ i, Measurable (X i) := by
    intro i
    refine measurable_pi_lambda _ fun k => ?_
    refine Fin.addCases ?_ ?_ k
    · intro j
      simp only [hXcast]
      exact ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval s)
    · intro r
      simp only [hXnat]
      exact D.measurable_stepIntegral (G r (ns i)) s t
  have hind : ∀ i, Indep (D.filtration s) (MeasurableSpace.comap (X i) inferInstance) P := by
    intro i
    obtain ⟨e⟩ : Nonempty ((Σ r : Fin q, Fin ((G r (ns i)).K))
        ≃ Fin (Fintype.card (Σ r : Fin q, Fin ((G r (ns i)).K)))) := ⟨Fintype.equivFin _⟩
    obtain ⟨B, hB⟩ : ∃ B : (Σ r : Fin q, Fin ((G r (ns i)).K)) → Set E,
        ∀ (r : Fin q) (l : Fin ((G r (ns i)).K)), B ⟨r, l⟩ = (G r (ns i)).B l :=
      ⟨fun x => (G x.1 (ns i)).B x.2, fun _ _ => rfl⟩
    have hBm : ∀ x, MeasurableSet (B x) := by
      rintro ⟨r, l⟩
      rw [hB]
      exact (G r (ns i)).B_measurable l
    refine (indep_of_indep_of_le_left (D.indep_stepSigma
        (fun k => Set.Ioc s t ×ˢ B (e.symm k))
        (fun k => measurableSet_Ioc.prod (hBm (e.symm k)))
        hs hst (fun _ => Set.prod_mono Set.Ioc_subset_Ioi_self (Set.subset_univ _))) ?_).symm
    rw [show MeasurableSpace.comap (X i) inferInstance
        = ⨆ k, MeasurableSpace.comap (fun ω => X i ω k) inferInstance from
      Probability.comap_pi_eq_iSup fun k ω => X i ω k]
    refine iSup_le fun k => ?_
    refine Fin.addCases ?_ ?_ k
    · intro j
      simp only [funext fun ω => hXcast i ω j]
      exact le_sup_of_le_left (le_iSup (fun j => D.incrementSigma j s t) j)
    · intro r
      simp only [funext fun ω => hXnat i ω r]
      refine (D.comap_stepIntegral_le (G r (ns i)) s t).trans (iSup_le fun l => ?_)
      refine le_sup_of_le_right (le_iSup_of_le (e ⟨r, l⟩) (le_of_eq ?_))
      simp only [Equiv.symm_apply_apply, hB]
  have hlim : ∀ᵐ ω ∂P,
      Tendsto (fun i => X i ω) atTop (nhds (levyCellProfileStep D s t ζ ω)) := by
    filter_upwards [hae, ae_all_iff.2 fun r : Fin q =>
      Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N (ζ r) s t] with ω hω hrepr
    refine tendsto_pi_nhds.2 fun k => ?_
    refine Fin.addCases ?_ ?_ k
    · intro j
      simp only [hXcast, levyCellProfileStep_castAdd]
      exact tendsto_const_nhds
    · intro r
      simp only [hXnat, levyCellProfileStep_natAdd, hrepr r]
      exact hω r
  exact (Probability.indep_comap_of_tendsto_ae (D.filtration.le s) hXm
    (measurable_levyCellProfileStep D s t ζ) hind hlim).symm

end LevyStochCalc.Driver
