/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.Joint
import LevyStochCalc.Probability.IndepGrouping

/-!
# Joint independence of the coordinates of a step of a Lévy driver

The Brownian increments `Wʲ_t − Wʲ_s`, `j : Fin d`, of a step of a Lévy driver are jointly
independent, each being measurable for the σ-algebra of its own coordinate Brownian motion and
those σ-algebras being jointly independent. The compensated counts `N(B_k) − c_k`, `k : Fin p`,
over pairwise-disjoint measurable regions `B_k ⊆ ℝ × E` are jointly independent, being functions
of the counts of a Poisson random measure over disjoint sets. Each Brownian increment is
measurable for `⨆ j, σ(Wʲ)` and each compensated count for `σ(N)`, and those two σ-algebras are
independent, so the concatenation of the two groups along `Fin (d + p)` is a jointly independent
family.

## Main statements

* `LevyStochCalc.Driver.LevyDriver.iIndepFun_increment` — the Brownian increments of a step are
  jointly independent.
* `LevyStochCalc.Driver.LevyDriver.iIndepFun_count` — the compensated counts over
  pairwise-disjoint regions are jointly independent.
* `LevyStochCalc.Driver.LevyDriver.comap_count_sub_le_sigmaPoisson` — a compensated count is
  measurable for the σ-algebra of the Poisson random measure.
* `LevyStochCalc.Driver.LevyDriver.indep_iSup_increment_iSup_count` — the σ-algebra of the
  Brownian increments of a step is independent of the σ-algebra of the compensated counts.
* `LevyStochCalc.Driver.LevyDriver.iIndepFun_increment_count` — the concatenated family is
  jointly independent.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

universe u v w

namespace LevyStochCalc.Driver.LevyDriver

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d p : ℕ}

/-- The Brownian increments of a step of a Lévy driver are jointly independent. -/
theorem iIndepFun_increment (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) :
    iIndepFun (fun j ω => (D.W.W j).W t ω - (D.W.W j).W s ω) P := by
  rw [iIndepFun_iff_iIndep]
  exact iIndep_of_iIndep_of_le (Brownian.iIndep_sigmaBrownian D.W)
    fun j => Brownian.comap_increment_le_sigmaBrownian (D.W.W j) s t

/-- The compensated counts of a Lévy driver over pairwise-disjoint measurable regions are jointly
independent. -/
theorem iIndepFun_count (D : LevyDriver.{u, v, w} P d ν) {B : Fin p → Set (ℝ × E)}
    (hB : ∀ k, MeasurableSet (B k)) (hBd : Pairwise fun k k' => Disjoint (B k) (B k'))
    (c : Fin p → ℝ) :
    iIndepFun (fun k ω => (D.N.N ω (B k)).toReal - c k) P := by
  have h := D.N.independent_disjoint (fun o : ULift.{w} (Fin p) => B o.down)
    (fun o => hB o.down) fun o o' hoo' => hBd fun h' => hoo' (by rw [ULift.ext_iff]; exact h')
  have h2 := h.precomp (g := ULift.up.{w}) fun x y hxy => by simpa [ULift.ext_iff] using hxy
  exact h2.comp (fun k y => y.toReal - c k) fun k => ENNReal.measurable_toReal.sub_const _

/-- A compensated count over a measurable region is measurable for the σ-algebra generated by the
Poisson random measure of a Lévy driver. -/
theorem comap_count_sub_le_sigmaPoisson (D : LevyDriver.{u, v, w} P d ν) {B : Set (ℝ × E)}
    (hB : MeasurableSet B) (c : ℝ) :
    MeasurableSpace.comap (fun ω => (D.N.N ω B).toReal - c) inferInstance
      ≤ sigmaPoisson D.N :=
  ((ENNReal.measurable_toReal.comp
    (Measurable.of_comap_le (comap_count_le_sigmaPoisson D.N hB))).sub_const c).comap_le

/-- The σ-algebra generated by the Brownian increments of a step of a Lévy driver is independent
of the σ-algebra generated by its compensated counts. -/
theorem indep_iSup_increment_iSup_count (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    {B : Fin p → Set (ℝ × E)} (hB : ∀ k, MeasurableSet (B k)) (c : Fin p → ℝ) :
    Indep (⨆ j, MeasurableSpace.comap (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω) inferInstance)
      (⨆ k, MeasurableSpace.comap (fun ω => (D.N.N ω (B k)).toReal - c k) inferInstance) P :=
  indep_of_indep_of_le D.indep
    (iSup_le fun j => (Brownian.comap_increment_le_sigmaBrownian (D.W.W j) s t).trans
      (le_iSup (fun i => Brownian.sigmaBrownian (D.W.W i)) j))
    (iSup_le fun k => D.comap_count_sub_le_sigmaPoisson (hB k) (c k))

/-- The Brownian increments of a step and the compensated counts on pairwise-disjoint regions
are jointly independent. -/
theorem iIndepFun_increment_count (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    {B : Fin p → Set (ℝ × E)} (hB : ∀ k, MeasurableSet (B k))
    (hBd : Pairwise fun k k' => Disjoint (B k) (B k')) (c : Fin p → ℝ) :
    iIndepFun (Fin.addCases (motive := fun _ => Ω → ℝ)
      (fun j ω => (D.W.W j).W t ω - (D.W.W j).W s ω)
      (fun k ω => (D.N.N ω (B k)).toReal - c k)) P :=
  Probability.iIndepFun_addCases (D.iIndepFun_increment s t) (D.iIndepFun_count hB hBd c)
    (D.indep_iSup_increment_iSup_count s t hB c)

end LevyStochCalc.Driver.LevyDriver
