/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.CellProfileStep
import LevyStochCalc.Poisson.CompensatedProductMoments

/-!
# The compensated product of two mark profiles over a cell of a Lévy driver

For mark profiles `f, g : E → ℝ` and the representatives `J(h)`, for the joint filtration at `t`,
of the compensated integrals over the cell `(s, t]` that the cell increment
`levyCellProfileStep` uses as its jump coordinates, the compensated product over the cell is

  `Q(f, g) = J(f) J(g) − J(f g) − (t − s) ∫ f g dν`.

It agrees almost everywhere with `Poisson.compensatedProduct`, so at bounded square-integrable
profiles it is square integrable and centred, its Gram is
`E[Q(f, g) Q(f', g')] = (t − s)² (⟨f, f'⟩ ⟨g, g'⟩ + ⟨f, g'⟩ ⟨g, f'⟩)` with `⟨u, v⟩ = ∫ u v dν`,
and it is orthogonal in `L²(P)` to every jump coordinate of the cell increment. When `f`, `g` and
`f g` are among the profiles of the cell increment, the compensated product is measurable for the
σ-algebra the cell increment generates.

The compensated integral of a bounded square-integrable profile is an `L²(P)` limit of
compensated step integrals, each measurable for the counts of the Poisson random measure, so it
is almost everywhere equal to a function measurable for the σ-algebra of the Poisson random
measure; so is the compensated product. That σ-algebra is independent of the Brownian motion, so
the compensated product is independent of every Brownian increment of the cell, and a centred
Brownian increment is orthogonal to it.

## Main definitions

* `LevyStochCalc.Driver.levyCellProduct` — the compensated product of two mark profiles over a
  cell, built from the jump coordinates of the cell increment.

## Main statements

* `LevyStochCalc.Driver.levyCellProduct_ae_eq` — it agrees almost everywhere with the compensated
  product of the compensated integrals.
* `LevyStochCalc.Driver.measurable_levyCellProduct_comap` — measurability for the σ-algebra
  generated by the cell increment.
* `LevyStochCalc.Driver.memLp_levyCellProduct`, `LevyStochCalc.Driver.integral_levyCellProduct`,
  `LevyStochCalc.Driver.integral_levyCellProduct_mul` — square integrability, mean and Gram.
* `LevyStochCalc.Driver.integral_levyCellProfileStep_natAdd_mul_levyCellProduct` — orthogonality
  to the jump coordinates of the cell increment.
* `LevyStochCalc.Driver.integral_levyCellProfileStep_castAdd_mul_levyCellProduct` —
  orthogonality to the Brownian coordinates of the cell increment.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped NNReal ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d q : ℕ}

/-- The compensated product over the cell `(s, t]` of the mark profiles `f` and `g`,
`J(f) J(g) − J(f g) − (t − s) ∫ f g dν`, where `J(h)` is the representative, for the joint
filtration at `t`, of the compensated integral of `h` over the cell. -/
noncomputable def levyCellProduct (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (f g : E → ℝ)
    (ω : Ω) : ℝ :=
  Poisson.compensatedProfileRepr (D.filtration t) D.N f s t ω
      * Poisson.compensatedProfileRepr (D.filtration t) D.N g s t ω
    - Poisson.compensatedProfileRepr (D.filtration t) D.N (fun e => f e * g e) s t ω
    - (t - s) * ∫ e, f e * g e ∂ν

/-- The compensated product over a cell agrees almost everywhere with the compensated product of
the compensated integrals of the two mark profiles. -/
theorem levyCellProduct_ae_eq (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (f g : E → ℝ) :
    levyCellProduct D s t f g =ᵐ[P] Poisson.compensatedProduct D.N f g s t := by
  filter_upwards [Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N f s t,
    Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N g s t,
    Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N (fun e => f e * g e) s t]
    with ω h1 h2 h3
  simp only [levyCellProduct, Poisson.compensatedProduct, h1, h2, h3]

/-- **The compensated product over a cell of two mark profiles of the cell increment, whose
product is also a profile of the cell increment, is measurable for the σ-algebra the cell
increment generates.** -/
theorem measurable_levyCellProduct_comap (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    {η : Fin q → E → ℝ} {r r' r'' : Fin q} (hη : η r'' = fun e => η r e * η r' e) :
    Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellProduct D s t (η r) (η r')) := by
  have hstep : Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellProfileStep D s t η) := Measurable.of_comap_le le_rfl
  have hcoord : ∀ k : Fin q,
      Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
        (fun ω => Poisson.compensatedProfileRepr (D.filtration t) D.N (η k) s t ω) := by
    intro k
    have h := (measurable_pi_apply (Fin.natAdd d k)).comp hstep
    simp only [Function.comp_def, levyCellProfileStep_natAdd] at h
    exact h
  have hrw : levyCellProduct D s t (η r) (η r') = fun ω =>
      Poisson.compensatedProfileRepr (D.filtration t) D.N (η r) s t ω
        * Poisson.compensatedProfileRepr (D.filtration t) D.N (η r') s t ω
      - Poisson.compensatedProfileRepr (D.filtration t) D.N (η r'') s t ω
      - (t - s) * ∫ e, η r e * η r' e ∂ν := by
    funext ω
    rw [hη]
    rfl
  rw [hrw]
  exact (((hcoord r).mul (hcoord r')).sub (hcoord r'')).sub measurable_const

/-! ### The moments -/

/-- **Square integrability.** The compensated product over the cell `(s, t]` of two bounded
square-integrable mark profiles is square integrable. -/
theorem memLp_levyCellProduct (D : LevyDriver.{u, v, w} P d ν) {f g : E → ℝ} (hf : MemLp f 2 ν)
    (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf) (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (levyCellProduct D s t f g) 2 P :=
  (Poisson.memLp_compensatedProduct D.N hf hg hbf hbg hs hst).ae_eq
    (levyCellProduct_ae_eq D s t f g).symm

/-- **The mean.** The compensated product over the cell `(s, t]` of two bounded square-integrable
mark profiles is centred. -/
theorem integral_levyCellProduct (D : LevyDriver.{u, v, w} P d ν) {f g : E → ℝ}
    (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf)
    (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProduct D s t f g ω ∂P = 0 := by
  rw [integral_congr_ae (levyCellProduct_ae_eq D s t f g)]
  exact Poisson.integral_compensatedProduct D.N hf hg hbf hbg hs hst

/-- **The Gram.** The `L²(P)` pairing of the compensated products over the cell `(s, t]` of
bounded square-integrable mark profiles, with `⟨u, v⟩ = ∫ u v dν`:
`E[Q(f, g) Q(f', g')] = (t − s)² (⟨f, f'⟩ ⟨g, g'⟩ + ⟨f, g'⟩ ⟨g, f'⟩)`. -/
theorem integral_levyCellProduct_mul (D : LevyDriver.{u, v, w} P d ν) {f g f' g' : E → ℝ}
    (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) (hf' : MemLp f' 2 ν) (hg' : MemLp g' 2 ν)
    {Cf Cg Cf' Cg' : ℝ} (hbf : ∀ e, |f e| ≤ Cf) (hbg : ∀ e, |g e| ≤ Cg)
    (hbf' : ∀ e, |f' e| ≤ Cf') (hbg' : ∀ e, |g' e| ≤ Cg') {s t : ℝ} (hs : 0 ≤ s)
    (hst : s ≤ t) :
    ∫ ω, levyCellProduct D s t f g ω * levyCellProduct D s t f' g' ω ∂P
      = (t - s) ^ 2 * ((∫ e, f e * f' e ∂ν) * (∫ e, g e * g' e ∂ν)
        + (∫ e, f e * g' e ∂ν) * (∫ e, g e * f' e ∂ν)) := by
  rw [← Poisson.integral_compensatedProduct_mul D.N hf hg hf' hg' hbf hbg hbf' hbg' hs hst]
  refine integral_congr_ae ?_
  filter_upwards [levyCellProduct_ae_eq D s t f g, levyCellProduct_ae_eq D s t f' g']
    with ω h1 h2
  rw [h1, h2]

/-- **Orthogonality to the jump coordinates.** The compensated product over the cell `(s, t]` of
two bounded square-integrable mark profiles is orthogonal in `L²(P)` to the jump coordinate of
the cell increment along a bounded square-integrable mark profile. -/
theorem integral_levyCellProfileStep_natAdd_mul_levyCellProduct (D : LevyDriver.{u, v, w} P d ν)
    {η : Fin q → E → ℝ} (r : Fin q) (hη : MemLp (η r) 2 ν) {Cη : ℝ} (hbη : ∀ e, |η r e| ≤ Cη)
    {f g : E → ℝ} (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf)
    (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.natAdd d r) * levyCellProduct D s t f g ω ∂P = 0 := by
  rw [← Poisson.integral_compensatedProduct_mul_compensatedProfile D.N hf hg hη hbf hbg hbη hs
    hst]
  refine integral_congr_ae ?_
  filter_upwards [levyCellProduct_ae_eq D s t f g,
    Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N (η r) s t] with ω h1 h2
  rw [levyCellProfileStep_natAdd, h1, h2, mul_comm]

/-! ### Orthogonality to the Brownian coordinates -/

/-- The compensated integral over `(s, t]` of a bounded square-integrable mark profile is almost
everywhere equal to a function measurable for the σ-algebra of the Poisson random measure. -/
private theorem aestronglyMeasurable_sigmaPoisson_compensatedProfile
    (D : LevyDriver.{u, v, w} P d ν) {h : E → ℝ} (hh : MemLp h 2 ν) {C : ℝ}
    (hb : ∀ e, |h e| ≤ C) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    AEStronglyMeasurable[sigmaPoisson D.N] (Poisson.compensatedProfile D.N h s t) P := by
  obtain ⟨G, -, hG⟩ := Poisson.exists_simpleProfile_tendsto_L2 hh hb
  refine Poisson.aestronglyMeasurable_compensatedProfile (sigmaPoisson D.N) (sigmaPoisson_le D.N)
    D.N hh hs hst G hG fun n => ?_
  exact ((Poisson.SimpleProfile.stronglyMeasurable_stepIntegral_regionSigma D.N (G n) s t).mono
    (iSup_le fun k => D.regionSigma_le
      (measurableSet_Ioc.prod ((G n).B_measurable k)))).aestronglyMeasurable

omit [SigmaFinite ν] in
/-- The product of a square-integrable and a bounded square-integrable mark profile is square
integrable. -/
private theorem memLp_mul_of_bound {f g : E → ℝ} (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cg : ℝ}
    (hbg : ∀ e, |g e| ≤ Cg) : MemLp (fun e => f e * g e) 2 ν :=
  hf.of_le_mul (hf.1.mul hg.1) (Eventually.of_forall fun e => by
    rw [Real.norm_eq_abs, Real.norm_eq_abs, abs_mul, mul_comm Cg]
    exact mul_le_mul_of_nonneg_left (hbg e) (abs_nonneg _))

/-- The compensated product over `(s, t]` of two bounded square-integrable mark profiles is
almost everywhere equal to a function measurable for the σ-algebra of the Poisson random
measure. -/
private theorem aestronglyMeasurable_sigmaPoisson_compensatedProduct
    (D : LevyDriver.{u, v, w} P d ν) {f g : E → ℝ} (hf : MemLp f 2 ν) (hg : MemLp g 2 ν)
    {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf) (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s)
    (hst : s ≤ t) :
    AEStronglyMeasurable[sigmaPoisson D.N] (Poisson.compensatedProduct D.N f g s t) P := by
  have hfg : ∀ e, |f e * g e| ≤ Cf * Cg := fun e => by
    rw [abs_mul]
    exact mul_le_mul (hbf e) (hbg e) (abs_nonneg _) ((abs_nonneg _).trans (hbf e))
  have h1 := aestronglyMeasurable_sigmaPoisson_compensatedProfile D hf hbf hs hst
  have h2 := aestronglyMeasurable_sigmaPoisson_compensatedProfile D hg hbg hs hst
  have h3 := aestronglyMeasurable_sigmaPoisson_compensatedProfile D
    (memLp_mul_of_bound hf hg hbg) hfg hs hst
  exact ((h1.mul h2).sub h3).sub aestronglyMeasurable_const

/-- The Brownian increments of a Lévy driver are centred. -/
private theorem integral_increment (D : LevyDriver.{u, v, w} P d ν) (j : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s < t) :
    ∫ ω, ((D.W.W j).W t ω - (D.W.W j).W s ω) ∂P = 0 := by
  have hmeas : Measurable fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω :=
    ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval s)
  have h := integral_map (μ := P) (f := fun x : ℝ => x) hmeas.aemeasurable
    aestronglyMeasurable_id
  rw [(D.W.W j).increment_gaussian hs hst, integral_id_gaussianReal] at h
  exact h.symm

/-- **Orthogonality to the Brownian coordinates.** The compensated product over the cell
`(s, t]` of two bounded square-integrable mark profiles is orthogonal in `L²(P)` to every
Brownian coordinate of the cell increment. -/
theorem integral_levyCellProfileStep_castAdd_mul_levyCellProduct
    (D : LevyDriver.{u, v, w} P d ν) {η : Fin q → E → ℝ} (j : Fin d) {f g : E → ℝ}
    (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf)
    (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.castAdd q j) * levyCellProduct D s t f g ω ∂P
      = 0 := by
  simp only [levyCellProfileStep_castAdd]
  rcases hst.lt_or_eq with hlt | rfl
  swap
  · simp
  have hQ := aestronglyMeasurable_sigmaPoisson_compensatedProduct D hf hg hbf hbg hs hst
  set Y : Ω → ℝ := hQ.mk _
  have hYm : StronglyMeasurable[sigmaPoisson D.N] Y := hQ.stronglyMeasurable_mk
  have hY : levyCellProduct D s t f g =ᵐ[P] Y := (levyCellProduct_ae_eq D s t f g).trans hQ.ae_eq_mk
  have hΔ : Measurable[⨆ i, Brownian.sigmaBrownian (D.W.W i)]
      (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω) :=
    Measurable.of_comap_le ((Brownian.comap_increment_le_sigmaBrownian (D.W.W j) s t).trans
      (le_iSup (fun i => Brownian.sigmaBrownian (D.W.W i)) j))
  have hind : IndepFun (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω) Y P := by
    rw [IndepFun_iff_Indep]
    exact indep_of_indep_of_le_right (indep_of_indep_of_le_left D.indep hΔ.comap_le)
      hYm.measurable.comap_le
  have hmeas : Measurable fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω :=
    ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval s)
  have hcongr : ∫ ω, ((D.W.W j).W t ω - (D.W.W j).W s ω) * levyCellProduct D s t f g ω ∂P
      = ∫ ω, ((D.W.W j).W t ω - (D.W.W j).W s ω) * Y ω ∂P := by
    refine integral_congr_ae ?_
    filter_upwards [hY] with ω hω
    rw [hω]
  rw [hcongr, hind.integral_fun_mul_eq_mul_integral hmeas.aestronglyMeasurable
      (hYm.mono (sigmaPoisson_le D.N)).aestronglyMeasurable,
    integral_increment D j hs hlt, zero_mul]

end LevyStochCalc.Driver
