/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.CellProductStep
import LevyStochCalc.Brownian.ChaosStep

/-!
# The mixed element of degree two over a cell of a Lévy driver

Over the cell `(s, t]` of a Lévy driver write `ΔWᵃ = Wᵃ_t − Wᵃ_s` for the increment of the
Brownian coordinate `a`, and `J(f)` for the representative, for the joint filtration at `t`, of
the compensated integral of a mark profile `f` over the cell, which is the jump coordinate of the
cell increment `levyCellProfileStep` along `f`. The mixed element of degree two of the cell is

  `M_a(f) = ΔWᵃ J(f)`.

At bounded square-integrable profiles it is square integrable and centred, its Gram is
`E[M_a(f) M_b(g)] = (t − s)² δ_ab ∫ f g dν`, and it is orthogonal in `L²(P)` to every coordinate
of the cell increment and to the compensated products `levyCellProduct`. When `f` is a profile of
the cell increment it is measurable for the σ-algebra the cell increment generates.

A function of the Brownian coordinates is independent of a function measurable for the
σ-algebra of the Poisson random measure, and `J(f)` is almost everywhere equal to such a
function, so every expectation of a Brownian factor times a jump factor splits; one of the two
factors is then centred, or the Brownian one is the covariance `E[ΔWᵃ ΔWᵇ] = δ_ab (t − s)`. No
independence among the jump coordinates enters: they are uncorrelated, and not independent when
the profiles overlap. The covariance comes from the independence of the increment of one
coordinate from everything else the driver generates.

## Main definitions

* `LevyStochCalc.Driver.levyCellMixed` — the mixed element `ΔWᵃ J(f)` over a cell.

## Main statements

* `LevyStochCalc.Driver.LevyDriver.hasLaw_increment` — the Brownian increment over `(s, t]` has
  law `𝒩(0, t − s)`.
* `LevyStochCalc.Driver.LevyDriver.integral_mul_eq_mul_integral_of_restSigma` — a function of
  one Brownian coordinate and a function of everything else the driver generates factor in
  expectation.
* `LevyStochCalc.Driver.LevyDriver.integral_increment_mul_increment` — the covariance
  `E[ΔWᵃ ΔWᵇ] = δ_ab (t − s)`.
* `LevyStochCalc.Driver.measurable_levyCellMixed_comap` — measurability for the σ-algebra
  generated by the cell increment.
* `LevyStochCalc.Driver.memLp_levyCellMixed`, `LevyStochCalc.Driver.integral_levyCellMixed`,
  `LevyStochCalc.Driver.integral_levyCellMixed_mul` — square integrability, mean and Gram.
* `LevyStochCalc.Driver.integral_levyCellProfileStep_castAdd_mul_levyCellMixed`,
  `LevyStochCalc.Driver.integral_levyCellProfileStep_natAdd_mul_levyCellMixed` — orthogonality
  to the Brownian and the jump coordinates of the cell increment.
* `LevyStochCalc.Driver.integral_levyCellMixed_mul_levyCellProduct` — orthogonality to the
  compensated products.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped NNReal ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d q : ℕ}

/-! ### The Brownian increments of a cell -/

/-- The increment over `(s, t]` of a Brownian coordinate of a Lévy driver has law
`𝒩(0, t − s)`. -/
theorem LevyDriver.hasLaw_increment (D : LevyDriver.{u, v, w} P d ν) (j : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    HasLaw (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω)
      (gaussianReal 0 ⟨t - s, sub_nonneg.2 hst⟩) P := by
  convert (D.W.W j).hasLaw_increment ⟨s, hs⟩ ⟨t, hs.trans hst⟩ hst using 2
  · rfl
  · refine NNReal.eq ?_
    rw [NNReal.coe_sub (show (⟨s, hs⟩ : ℝ≥0) ≤ ⟨t, hs.trans hst⟩ from hst)]
    rfl

/-- A Brownian increment of a Lévy driver is square integrable. -/
private theorem memLp_increment (D : LevyDriver.{u, v, w} P d ν) (j : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω) 2 P := by
  have h := Probability.memLp_two_wienerChaosStep (D.hasLaw_increment j hs hst) 1
  simpa only [Probability.wienerChaosStep_one] using h

/-- The increment over `(s, t]` of a Brownian coordinate `j` of a Lévy driver is measurable for
the σ-algebra generated by everything the driver generates apart from a coordinate `k ≠ j`. -/
theorem LevyDriver.measurable_increment_restSigma (D : LevyDriver.{u, v, w} P d ν)
    {j k : Fin d} (hjk : j ≠ k) (s t : ℝ) :
    Measurable[D.restSigma k] fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω :=
  Measurable.of_comap_le ((Brownian.comap_increment_le_sigmaBrownian (D.W.W j) s t).trans
    (le_sup_of_le_left (le_iSup₂_of_le (f := fun i (_ : i ∈ {i : Fin d | i ≠ k}) =>
      Brownian.sigmaBrownian (D.W.W i)) j hjk le_rfl)))

/-- **A function of one Brownian coordinate and a function of everything else the driver
generates factor in expectation.** For `Z` measurable for the σ-algebra of the Brownian
coordinate `k` of a Lévy driver and `Y` measurable for the σ-algebra generated by the other
coordinates and the Poisson random measure, `E[Z Y] = E[Z] E[Y]`. -/
theorem LevyDriver.integral_mul_eq_mul_integral_of_restSigma (D : LevyDriver.{u, v, w} P d ν)
    (k : Fin d) {Z Y : Ω → ℝ} (hZ : Measurable[Brownian.sigmaBrownian (D.W.W k)] Z)
    (hY : Measurable[D.restSigma k] Y) :
    ∫ ω, Z ω * Y ω ∂P = (∫ ω, Z ω ∂P) * ∫ ω, Y ω ∂P := by
  have hind : IndepFun Z Y P := by
    rw [IndepFun_iff_Indep]
    exact indep_of_indep_of_le_right
      (indep_of_indep_of_le_left (D.indep_restSigma k).symm hZ.comap_le) hY.comap_le
  exact hind.integral_fun_mul_eq_mul_integral
    (hZ.mono (Brownian.sigmaBrownian_le _) le_rfl).aestronglyMeasurable
    (hY.mono (D.restSigma_le k) le_rfl).aestronglyMeasurable

/-- The increment over `(s, t]` of the Brownian coordinate `k` of a Lévy driver times a function
of everything else the driver generates is centred. -/
theorem LevyDriver.integral_increment_mul_eq_zero_of_restSigma
    (D : LevyDriver.{u, v, w} P d ν) (k : Fin d) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t)
    {Y : Ω → ℝ} (hY : Measurable[D.restSigma k] Y) :
    ∫ ω, ((D.W.W k).W t ω - (D.W.W k).W s ω) * Y ω ∂P = 0 := by
  rw [D.integral_mul_eq_mul_integral_of_restSigma k
      (Measurable.of_comap_le (Brownian.comap_increment_le_sigmaBrownian (D.W.W k) s t)) hY,
    D.integral_increment k hs hst, zero_mul]

/-- **The covariance of the Brownian increments of a cell**, `E[ΔWᵃ ΔWᵇ] = δ_ab (t − s)`. -/
theorem LevyDriver.integral_increment_mul_increment (D : LevyDriver.{u, v, w} P d ν)
    (a b : Fin d) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω) ∂P
      = if a = b then t - s else 0 := by
  by_cases hab : a = b
  · subst hab
    rw [if_pos rfl]
    have h := Probability.integral_wienerChaosStep_mul (D.hasLaw_increment a hs hst) 1 1
    simp only [Probability.wienerChaosStep_one, if_true, Nat.factorial_one, Nat.cast_one,
      pow_one, one_mul] at h
    exact h
  · rw [if_neg hab]
    exact D.integral_increment_mul_eq_zero_of_restSigma a hs hst
      (D.measurable_increment_restSigma (Ne.symm hab) s t)

/-! ### The jump coordinates -/

private theorem integral_repr (D : LevyDriver.{u, v, w} P d ν) {f : E → ℝ} (hf : MemLp f 2 ν)
    {C : ℝ} (hb : ∀ e, |f e| ≤ C) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, Poisson.compensatedProfileRepr (D.filtration t) D.N f s t ω ∂P = 0 := by
  rw [integral_congr_ae (Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N f s t)]
  exact Poisson.integral_compensatedProfile D.N hf hb hs hst

private theorem integral_repr_mul (D : LevyDriver.{u, v, w} P d ν) {f g : E → ℝ}
    (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf)
    (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, Poisson.compensatedProfileRepr (D.filtration t) D.N f s t ω
        * Poisson.compensatedProfileRepr (D.filtration t) D.N g s t ω ∂P
      = (t - s) * ∫ e, f e * g e ∂ν := by
  rw [← Poisson.integral_compensatedProfile_mul D.N hf hg hbf hbg hs hst]
  refine integral_congr_ae ?_
  filter_upwards [Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N f s t,
    Poisson.compensatedProfileRepr_ae_eq (D.filtration t) D.N g s t] with ω h1 h2
  rw [h1, h2]

/-! ### The mixed element -/

/-- The mixed element over the cell `(s, t]` of the Brownian coordinate `a` and the mark profile
`f`, `ΔWᵃ J(f)`: the increment of `Wᵃ` over the cell times the representative `J(f)`, for the
joint filtration at `t`, of the compensated integral of `f` over the cell. -/
noncomputable def levyCellMixed (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (a : Fin d)
    (f : E → ℝ) (ω : Ω) : ℝ :=
  ((D.W.W a).W t ω - (D.W.W a).W s ω)
    * Poisson.compensatedProfileRepr (D.filtration t) D.N f s t ω

private theorem measurable_levyCellMixed (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (a : Fin d)
    (f : E → ℝ) : Measurable (levyCellMixed D s t a f) :=
  (((D.W.W a).measurable_eval t).sub ((D.W.W a).measurable_eval s)).mul
    (Poisson.measurable_compensatedProfileRepr (D.filtration t) (D.filtration.le t) D.N f s t)

/-- **The mixed element over a cell along a mark profile of the cell increment is measurable
for the σ-algebra the cell increment generates.** -/
theorem measurable_levyCellMixed_comap (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (a : Fin d)
    {η : Fin q → E → ℝ} (r : Fin q) :
    Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellMixed D s t a (η r)) := by
  have hstep : Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellProfileStep D s t η) := Measurable.of_comap_le le_rfl
  have hB := (measurable_pi_apply (Fin.castAdd q a)).comp hstep
  have hJ := (measurable_pi_apply (Fin.natAdd d r)).comp hstep
  simp only [Function.comp_def, levyCellProfileStep_castAdd, levyCellProfileStep_natAdd]
    at hB hJ
  exact hB.mul hJ

/-- **Square integrability.** The mixed element over the cell `(s, t]` along a bounded
square-integrable mark profile is square integrable. -/
theorem memLp_levyCellMixed (D : LevyDriver.{u, v, w} P d ν) (a : Fin d) {f : E → ℝ}
    (hf : MemLp f 2 ν) {C : ℝ} (hb : ∀ e, |f e| ≤ C) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (levyCellMixed D s t a f) 2 P := by
  have hJ := aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hb hs hst
  have hYm : StronglyMeasurable[sigmaPoisson D.N] (hJ.mk _) := hJ.stronglyMeasurable_mk
  have hind : IndepFun (fun ω => ((D.W.W a).W t ω - (D.W.W a).W s ω) ^ 2)
      (fun ω => hJ.mk _ ω ^ 2) P := by
    rw [IndepFun_iff_Indep]
    exact indep_of_indep_of_le_right (indep_of_indep_of_le_left D.indep
      ((D.measurable_increment_iSup_sigmaBrownian a s t).pow_const 2).comap_le)
      (hYm.measurable.pow_const 2).comap_le
  have hX2 : Integrable (fun ω => ((D.W.W a).W t ω - (D.W.W a).W s ω) ^ 2) P :=
    (memLp_increment D a hs hst).integrable_sq
  have hY2 : Integrable (fun ω => hJ.mk _ ω ^ 2) P :=
    ((Poisson.memLp_compensatedProfileRepr (D.filtration t) D.N f s t).ae_eq
      hJ.ae_eq_mk).integrable_sq
  refine (memLp_two_iff_integrable_sq
    (measurable_levyCellMixed D s t a f).aestronglyMeasurable).2 ?_
  refine (hind.integrable_mul hX2 hY2).congr ?_
  filter_upwards [hJ.ae_eq_mk] with ω hω
  simp only [Pi.mul_apply, levyCellMixed, hω, mul_pow]

/-- **The mean.** The mixed element over the cell `(s, t]` along a bounded square-integrable mark
profile is centred. -/
theorem integral_levyCellMixed (D : LevyDriver.{u, v, w} P d ν) (a : Fin d) {f : E → ℝ}
    (hf : MemLp f 2 ν) {C : ℝ} (hb : ∀ e, |f e| ≤ C) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellMixed D s t a f ω ∂P = 0 := by
  simp only [levyCellMixed]
  rw [D.integral_mul_eq_mul_integral_of_sigmaPoisson
      (D.measurable_increment_iSup_sigmaBrownian a s t)
      (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hb hs hst),
    D.integral_increment a hs hst, zero_mul]

/-- **The Gram.** The `L²(P)` pairing of the mixed elements over the cell `(s, t]` along bounded
square-integrable mark profiles: `E[ΔWᵃ J(f) ΔWᵇ J(g)] = (t − s)² δ_ab ∫ f g dν`. -/
theorem integral_levyCellMixed_mul (D : LevyDriver.{u, v, w} P d ν) (a b : Fin d)
    {f g : E → ℝ} (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) {Cf Cg : ℝ} (hbf : ∀ e, |f e| ≤ Cf)
    (hbg : ∀ e, |g e| ≤ Cg) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellMixed D s t a f ω * levyCellMixed D s t b g ω ∂P
      = (t - s) ^ 2 * (if a = b then 1 else 0) * ∫ e, f e * g e ∂ν := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson
      ((D.measurable_increment_iSup_sigmaBrownian a s t).mul
        (D.measurable_increment_iSup_sigmaBrownian b s t))
      ((aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hbf hs hst).mul
        (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hg hbg hs hst)))).trans ?_
  · simp only [levyCellMixed, Pi.mul_apply]
    ring
  · simp only [Pi.mul_apply]
    rw [D.integral_increment_mul_increment a b hs hst, integral_repr_mul D hf hg hbf hbg hs hst]
    split_ifs <;> ring

/-- **Orthogonality to the Brownian coordinates.** The mixed element over the cell `(s, t]` along
a bounded square-integrable mark profile is orthogonal in `L²(P)` to every Brownian coordinate of
the cell increment. -/
theorem integral_levyCellProfileStep_castAdd_mul_levyCellMixed (D : LevyDriver.{u, v, w} P d ν)
    {η : Fin q → E → ℝ} (j a : Fin d) {f : E → ℝ} (hf : MemLp f 2 ν) {C : ℝ}
    (hb : ∀ e, |f e| ≤ C) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.castAdd q j) * levyCellMixed D s t a f ω ∂P
      = 0 := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson
      ((D.measurable_increment_iSup_sigmaBrownian j s t).mul
        (D.measurable_increment_iSup_sigmaBrownian a s t))
      (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hb hs hst))).trans ?_
  · simp only [levyCellProfileStep_castAdd, levyCellMixed, Pi.mul_apply]
    ring
  · rw [integral_repr D hf hb hs hst, mul_zero]

/-- **Orthogonality to the jump coordinates.** The mixed element over the cell `(s, t]` along a
bounded square-integrable mark profile is orthogonal in `L²(P)` to the jump coordinate of the
cell increment along a bounded square-integrable mark profile. -/
theorem integral_levyCellProfileStep_natAdd_mul_levyCellMixed (D : LevyDriver.{u, v, w} P d ν)
    {η : Fin q → E → ℝ} (r : Fin q) (hη : MemLp (η r) 2 ν) {Cη : ℝ} (hbη : ∀ e, |η r e| ≤ Cη)
    (a : Fin d) {f : E → ℝ} (hf : MemLp f 2 ν) {C : ℝ} (hb : ∀ e, |f e| ≤ C) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.natAdd d r) * levyCellMixed D s t a f ω ∂P
      = 0 := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson
      (D.measurable_increment_iSup_sigmaBrownian a s t)
      ((aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hη hbη hs hst).mul
        (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hb hs hst)))).trans ?_
  · simp only [levyCellProfileStep_natAdd, levyCellMixed, Pi.mul_apply]
    ring
  · rw [D.integral_increment a hs hst, zero_mul]

/-- **The mixed element and the compensated product are orthogonal.** Over the cell `(s, t]`, the
mixed element along a bounded square-integrable mark profile is orthogonal in `L²(P)` to the
compensated product of two bounded square-integrable mark profiles. -/
theorem integral_levyCellMixed_mul_levyCellProduct (D : LevyDriver.{u, v, w} P d ν) (a : Fin d)
    {f g h : E → ℝ} (hf : MemLp f 2 ν) (hg : MemLp g 2 ν) (hh : MemLp h 2 ν) {Cf Cg Ch : ℝ}
    (hbf : ∀ e, |f e| ≤ Cf) (hbg : ∀ e, |g e| ≤ Cg) (hbh : ∀ e, |h e| ≤ Ch) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellMixed D s t a f ω * levyCellProduct D s t g h ω ∂P = 0 := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson
      (D.measurable_increment_iSup_sigmaBrownian a s t)
      ((aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hbf hs hst).mul
        ((aestronglyMeasurable_sigmaPoisson_compensatedProduct D hg hh hbg hbh hs hst).congr
          (levyCellProduct_ae_eq D s t g h).symm)))).trans ?_
  · simp only [levyCellMixed, Pi.mul_apply]
    ring
  · rw [D.integral_increment a hs hst, zero_mul]

end LevyStochCalc.Driver
