/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.CellMixedStep

/-!
# The Brownian element of degree two over a cell of a Lévy driver

Over the cell `(s, t]` of a Lévy driver write `ΔWᵃ = Wᵃ_t − Wᵃ_s` for the increment of the
Brownian coordinate `a`. The Brownian element of degree two of the cell is

  `B_ab = ΔWᵃ ΔWᵇ − δ_ab (t − s)`.

It is square integrable and centred, its Gram is
`E[B_ab B_a'b'] = (t − s)² (δ_aa' δ_bb' + δ_ab' δ_ba')`, and it is orthogonal in `L²(P)` to every
coordinate of the cell increment `levyCellProfileStep`, to the mixed elements `levyCellMixed` and
to the compensated products `levyCellProduct` of bounded square-integrable mark profiles. It is
measurable for the σ-algebra the cell increment generates.

The Brownian increments of distinct coordinates are independent centred Gaussians, so a moment
of them of order at most four in which one coordinate occurs exactly once vanishes, and every
other such moment reduces to Gaussian moments of single coordinates. Against a jump factor, a
function measurable for the σ-algebra of the Poisson random measure up to a null set, the
expectation splits by the independence of the Brownian and the Poisson σ-algebras.

## Main definitions

* `LevyStochCalc.Driver.levyCellBrownian` — the Brownian element `ΔWᵃ ΔWᵇ − δ_ab (t − s)` over a
  cell.

## Main statements

* `LevyStochCalc.Driver.measurable_levyCellBrownian_comap` — measurability for the σ-algebra
  generated by the cell increment.
* `LevyStochCalc.Driver.memLp_levyCellBrownian`, `LevyStochCalc.Driver.integral_levyCellBrownian`,
  `LevyStochCalc.Driver.integral_levyCellBrownian_mul` — square integrability, mean and Gram.
* `LevyStochCalc.Driver.integral_levyCellProfileStep_castAdd_mul_levyCellBrownian`,
  `LevyStochCalc.Driver.integral_levyCellProfileStep_natAdd_mul_levyCellBrownian` — orthogonality
  to the Brownian and the jump coordinates of the cell increment.
* `LevyStochCalc.Driver.integral_levyCellMixed_mul_levyCellBrownian`,
  `LevyStochCalc.Driver.integral_levyCellBrownian_mul_levyCellProduct` — orthogonality to the
  mixed elements and to the compensated products.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped NNReal ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d q : ℕ}

/-! ### Gaussian moments of one Brownian increment -/

/-- `E[ΔW (ΔW² − (t − s))] = 0` for a Brownian increment `ΔW` over `(s, t]`. -/
private theorem integral_increment_mul_sq_sub (D : LevyDriver.{u, v, w} P d ν) (j : Fin d)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, ((D.W.W j).W t ω - (D.W.W j).W s ω)
      * (((D.W.W j).W t ω - (D.W.W j).W s ω) * ((D.W.W j).W t ω - (D.W.W j).W s ω) - (t - s))
      ∂P = 0 := by
  have h := Probability.integral_wienerChaosStep_mul (D.hasLaw_increment j hs hst) 1 2
  simp only [Probability.wienerChaosStep_one, Probability.wienerChaosStep_two, sq,
    if_neg (show (1 : ℕ) ≠ 2 by decide)] at h
  exact h

/-- `E[(ΔW² − (t − s))²] = 2 (t − s)²` for a Brownian increment `ΔW` over `(s, t]`. -/
private theorem integral_increment_sq_sub_mul (D : LevyDriver.{u, v, w} P d ν) (j : Fin d)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, (((D.W.W j).W t ω - (D.W.W j).W s ω) * ((D.W.W j).W t ω - (D.W.W j).W s ω) - (t - s))
      * (((D.W.W j).W t ω - (D.W.W j).W s ω) * ((D.W.W j).W t ω - (D.W.W j).W s ω) - (t - s))
      ∂P = 2 * (t - s) ^ 2 := by
  have h := Probability.integral_wienerChaosStep_mul (D.hasLaw_increment j hs hst) 2 2
  simp only [Probability.wienerChaosStep_two, if_true, sq] at h
  refine h.trans ?_
  change ((Nat.factorial 2 : ℕ) : ℝ) * ((t - s) * (t - s)) = 2 * (t - s) ^ 2
  norm_num [Nat.factorial]
  ring

private theorem memLp_increment_sq (D : LevyDriver.{u, v, w} P d ν) (j : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (fun ω => ((D.W.W j).W t ω - (D.W.W j).W s ω) ^ 2) 2 P := by
  have h := (Probability.memLp_two_wienerChaosStep (D.hasLaw_increment j hs hst) 2).add
    (memLp_const (t - s))
  refine h.ae_eq (Eventually.of_forall fun ω => ?_)
  simp only [Pi.add_apply, Probability.wienerChaosStep_two]
  exact sub_add_cancel _ _

private theorem memLp_increment_mul (D : LevyDriver.{u, v, w} P d ν) (a b : Fin d)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (fun ω => ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω))
      2 P := by
  refine (memLp_two_iff_integrable_sq
    ((((D.W.W a).measurable_eval t).sub ((D.W.W a).measurable_eval s)).mul
      (((D.W.W b).measurable_eval t).sub ((D.W.W b).measurable_eval s))).aestronglyMeasurable).2 ?_
  refine ((memLp_increment_sq D a hs hst).integrable_mul
    (memLp_increment_sq D b hs hst)).congr (Eventually.of_forall fun ω => ?_)
  simp only [Pi.mul_apply, Pi.sub_apply]
  ring

/-! ### The Brownian element -/

/-- The Brownian element over the cell `(s, t]` of the coordinates `a` and `b`,
`ΔWᵃ ΔWᵇ − δ_ab (t − s)`. -/
noncomputable def levyCellBrownian (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (a b : Fin d)
    (ω : Ω) : ℝ :=
  ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω)
    - if a = b then t - s else 0

private theorem levyCellBrownian_self (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) (a : Fin d)
    (ω : Ω) :
    levyCellBrownian D s t a a ω
      = ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W a).W t ω - (D.W.W a).W s ω)
        - (t - s) := by
  simp [levyCellBrownian]

private theorem levyCellBrownian_of_ne (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ) {a b : Fin d}
    (hab : a ≠ b) (ω : Ω) :
    levyCellBrownian D s t a b ω
      = ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω) := by
  simp [levyCellBrownian, hab]

private theorem measurable_levyCellBrownian_iSup (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (a b : Fin d) :
    Measurable[⨆ i, Brownian.sigmaBrownian (D.W.W i)] (levyCellBrownian D s t a b) :=
  ((D.measurable_increment_iSup_sigmaBrownian a s t).mul
    (D.measurable_increment_iSup_sigmaBrownian b s t)).sub measurable_const

private theorem measurable_levyCellBrownian_restSigma (D : LevyDriver.{u, v, w} P d ν)
    (s t : ℝ) {a b k : Fin d} (hak : a ≠ k) (hbk : b ≠ k) :
    Measurable[D.restSigma k] (levyCellBrownian D s t a b) :=
  ((D.measurable_increment_restSigma hak s t).mul
    (D.measurable_increment_restSigma hbk s t)).sub measurable_const

/-- **The Brownian element over a cell is measurable for the σ-algebra the cell increment
generates.** -/
theorem measurable_levyCellBrownian_comap (D : LevyDriver.{u, v, w} P d ν) (s t : ℝ)
    (a b : Fin d) {η : Fin q → E → ℝ} :
    Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellBrownian D s t a b) := by
  have hstep : Measurable[MeasurableSpace.comap (levyCellProfileStep D s t η) inferInstance]
      (levyCellProfileStep D s t η) := Measurable.of_comap_le le_rfl
  have ha := (measurable_pi_apply (Fin.castAdd q a)).comp hstep
  have hb := (measurable_pi_apply (Fin.castAdd q b)).comp hstep
  simp only [Function.comp_def, levyCellProfileStep_castAdd] at ha hb
  exact (ha.mul hb).sub measurable_const

/-! ### The moments -/

/-- **Square integrability.** The Brownian element over the cell `(s, t]` is square
integrable. -/
theorem memLp_levyCellBrownian (D : LevyDriver.{u, v, w} P d ν) (a b : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    MemLp (levyCellBrownian D s t a b) 2 P :=
  (memLp_increment_mul D a b hs hst).sub (memLp_const _)

/-- **The mean.** The Brownian element over the cell `(s, t]` is centred. -/
theorem integral_levyCellBrownian (D : LevyDriver.{u, v, w} P d ν) (a b : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellBrownian D s t a b ω ∂P = 0 := by
  simp only [levyCellBrownian]
  rw [integral_sub ((memLp_increment_mul D a b hs hst).integrable one_le_two)
    (integrable_const _), D.integral_increment_mul_increment a b hs hst]
  simp

/-- **The Gram.** The `L²(P)` pairing of the Brownian elements over the cell `(s, t]`:
`E[B_ab B_a'b'] = (t − s)² (δ_aa' δ_bb' + δ_ab' δ_ba')`. -/
theorem integral_levyCellBrownian_mul (D : LevyDriver.{u, v, w} P d ν) (a b a' b' : Fin d)
    {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellBrownian D s t a b ω * levyCellBrownian D s t a' b' ω ∂P
      = (t - s) ^ 2 * ((if a = a' then 1 else 0) * (if b = b' then 1 else 0)
        + (if a = b' then 1 else 0) * (if b = a' then 1 else 0)) := by
  by_cases hab : a = b
  · subst hab
    by_cases hab' : a' = b'
    · subst hab'
      by_cases haa : a = a'
      · subst haa
        simp only [levyCellBrownian_self, if_true]
        rw [integral_increment_sq_sub_mul D a hs hst]
        ring
      · have hZ : Measurable[Brownian.sigmaBrownian (D.W.W a)] (levyCellBrownian D s t a a) :=
          ((Measurable.of_comap_le (Brownian.comap_increment_le_sigmaBrownian (D.W.W a) s t)).mul
            (Measurable.of_comap_le (Brownian.comap_increment_le_sigmaBrownian (D.W.W a) s t))).sub
            measurable_const
        rw [D.integral_mul_eq_mul_integral_of_restSigma a hZ
          (measurable_levyCellBrownian_restSigma D s t (Ne.symm haa) (Ne.symm haa)),
          integral_levyCellBrownian D a a hs hst, zero_mul]
        simp [haa]
    · by_cases haa : a = a'
      · subst haa
        refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
          ((D.integral_increment_mul_eq_zero_of_restSigma b' hs hst
            (Y := fun ω => levyCellBrownian D s t a a ω * ((D.W.W a).W t ω - (D.W.W a).W s ω))
            ((measurable_levyCellBrownian_restSigma D s t hab' hab').mul
              (D.measurable_increment_restSigma hab' s t))).trans ?_)
        · simp only [levyCellBrownian_of_ne D s t hab' ω]
          ring
        · simp [hab']
      · refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
          ((D.integral_increment_mul_eq_zero_of_restSigma a' hs hst
            (Y := fun ω => levyCellBrownian D s t a a ω * ((D.W.W b').W t ω - (D.W.W b').W s ω))
            ((measurable_levyCellBrownian_restSigma D s t haa haa).mul
              (D.measurable_increment_restSigma (Ne.symm hab') s t))).trans ?_)
        · simp only [levyCellBrownian_of_ne D s t hab' ω]
          ring
        · simp [haa]
  · by_cases h1 : a ≠ a' ∧ a ≠ b'
    · refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
        ((D.integral_increment_mul_eq_zero_of_restSigma a hs hst
          (Y := fun ω => ((D.W.W b).W t ω - (D.W.W b).W s ω) * levyCellBrownian D s t a' b' ω)
          ((D.measurable_increment_restSigma (Ne.symm hab) s t).mul
            (measurable_levyCellBrownian_restSigma D s t (Ne.symm h1.1) (Ne.symm h1.2)))).trans
          ?_)
      · simp only [levyCellBrownian_of_ne D s t hab ω]
        ring
      · simp [h1.1, h1.2]
    by_cases h2 : b ≠ a' ∧ b ≠ b'
    · refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
        ((D.integral_increment_mul_eq_zero_of_restSigma b hs hst
          (Y := fun ω => ((D.W.W a).W t ω - (D.W.W a).W s ω) * levyCellBrownian D s t a' b' ω)
          ((D.measurable_increment_restSigma hab s t).mul
            (measurable_levyCellBrownian_restSigma D s t (Ne.symm h2.1) (Ne.symm h2.2)))).trans
          ?_)
      · simp only [levyCellBrownian_of_ne D s t hab ω]
        ring
      · simp [h2.1, h2.2]
    have hsq : ∫ ω, ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω)
        * (((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω)) ∂P
        = (t - s) ^ 2 := by
      have hZ : Measurable[Brownian.sigmaBrownian (D.W.W a)]
          fun ω => (D.W.W a).W t ω - (D.W.W a).W s ω :=
        Measurable.of_comap_le (Brownian.comap_increment_le_sigmaBrownian (D.W.W a) s t)
      refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
        ((D.integral_mul_eq_mul_integral_of_restSigma a (hZ.mul hZ)
          ((D.measurable_increment_restSigma (Ne.symm hab) s t).mul
            (D.measurable_increment_restSigma (Ne.symm hab) s t))).trans ?_)
      · simp only [Pi.mul_apply]
        ring
      · simp only [Pi.mul_apply]
        rw [D.integral_increment_mul_increment a a hs hst,
          D.integral_increment_mul_increment b b hs hst, if_pos rfl, if_pos rfl]
        ring
    by_cases haa : a = a'
    · subst haa
      have hbb : b = b' := by
        by_contra hbb
        exact h2 ⟨hab ∘ Eq.symm, hbb⟩
      subst hbb
      refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans (hsq.trans ?_)
      · simp only [levyCellBrownian_of_ne D s t hab]
      · simp [hab, Ne.symm hab]
    · have hab'' : a = b' := by
        by_contra h
        exact h1 ⟨haa, h⟩
      subst hab''
      have hba : b = a' := by
        by_contra h
        exact h2 ⟨h, Ne.symm hab⟩
      subst hba
      refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans (hsq.trans ?_)
      · simp only [levyCellBrownian_of_ne D s t hab, levyCellBrownian_of_ne D s t (Ne.symm hab)]
        ring
      · simp [hab, Ne.symm hab]

/-! ### Orthogonality -/

/-- A Brownian increment of the cell `(s, t]` is orthogonal in `L²(P)` to every Brownian
element of the cell. -/
private theorem integral_increment_mul_levyCellBrownian (D : LevyDriver.{u, v, w} P d ν)
    (j a b : Fin d) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, ((D.W.W j).W t ω - (D.W.W j).W s ω) * levyCellBrownian D s t a b ω ∂P = 0 := by
  by_cases hab : a = b
  · subst hab
    by_cases haj : a = j
    · subst haj
      simp only [levyCellBrownian_self]
      exact integral_increment_mul_sq_sub D a hs hst
    · exact D.integral_increment_mul_eq_zero_of_restSigma j hs hst
        (measurable_levyCellBrownian_restSigma D s t haj haj)
  · by_cases haj : a = j
    · subst haj
      refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
        (D.integral_increment_mul_eq_zero_of_restSigma b hs hst
          (Y := fun ω => ((D.W.W a).W t ω - (D.W.W a).W s ω) * ((D.W.W a).W t ω - (D.W.W a).W s ω))
          ((D.measurable_increment_restSigma hab s t).mul
            (D.measurable_increment_restSigma hab s t)))
      simp only [levyCellBrownian_of_ne D s t hab ω]
      ring
    · refine (integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
        (D.integral_increment_mul_eq_zero_of_restSigma a hs hst
          (Y := fun ω => ((D.W.W j).W t ω - (D.W.W j).W s ω) * ((D.W.W b).W t ω - (D.W.W b).W s ω))
          ((D.measurable_increment_restSigma (Ne.symm haj) s t).mul
            (D.measurable_increment_restSigma (Ne.symm hab) s t)))
      simp only [levyCellBrownian_of_ne D s t hab ω]
      ring

/-- **Orthogonality to the Brownian coordinates.** The Brownian element over the cell `(s, t]` is
orthogonal in `L²(P)` to every Brownian coordinate of the cell increment. -/
theorem integral_levyCellProfileStep_castAdd_mul_levyCellBrownian
    (D : LevyDriver.{u, v, w} P d ν) {η : Fin q → E → ℝ} (j a b : Fin d) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.castAdd q j) * levyCellBrownian D s t a b ω ∂P
      = 0 := by
  simp only [levyCellProfileStep_castAdd]
  exact integral_increment_mul_levyCellBrownian D j a b hs hst

/-- **Orthogonality to the jump coordinates.** The Brownian element over the cell `(s, t]` is
orthogonal in `L²(P)` to the jump coordinate of the cell increment along a bounded
square-integrable mark profile. -/
theorem integral_levyCellProfileStep_natAdd_mul_levyCellBrownian
    (D : LevyDriver.{u, v, w} P d ν) {η : Fin q → E → ℝ} (r : Fin q) (hη : MemLp (η r) 2 ν)
    {Cη : ℝ} (hbη : ∀ e, |η r e| ≤ Cη) (a b : Fin d) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellProfileStep D s t η ω (Fin.natAdd d r) * levyCellBrownian D s t a b ω ∂P
      = 0 := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson (measurable_levyCellBrownian_iSup D s t a b)
      (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hη hbη hs hst))).trans ?_
  · rw [levyCellProfileStep_natAdd, mul_comm]
  · rw [integral_levyCellBrownian D a b hs hst, zero_mul]

/-- **The mixed and the Brownian elements are orthogonal.** Over the cell `(s, t]`, the mixed
element along a bounded square-integrable mark profile is orthogonal in `L²(P)` to every
Brownian element. -/
theorem integral_levyCellMixed_mul_levyCellBrownian (D : LevyDriver.{u, v, w} P d ν)
    (a b c : Fin d) {f : E → ℝ} (hf : MemLp f 2 ν) {C : ℝ} (hb : ∀ e, |f e| ≤ C) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellMixed D s t a f ω * levyCellBrownian D s t b c ω ∂P = 0 := by
  refine ((integral_congr_ae (Eventually.of_forall fun ω => ?_)).trans
    (D.integral_mul_eq_mul_integral_of_sigmaPoisson
      ((D.measurable_increment_iSup_sigmaBrownian a s t).mul
        (measurable_levyCellBrownian_iSup D s t b c))
      (aestronglyMeasurable_sigmaPoisson_compensatedProfileRepr D hf hb hs hst))).trans ?_
  · simp only [levyCellMixed, Pi.mul_apply]
    ring
  · simp only [Pi.mul_apply]
    rw [integral_increment_mul_levyCellBrownian D a b c hs hst, zero_mul]

/-- **The Brownian element and the compensated product are orthogonal.** Over the cell `(s, t]`,
every Brownian element is orthogonal in `L²(P)` to the compensated product of two bounded
square-integrable mark profiles. -/
theorem integral_levyCellBrownian_mul_levyCellProduct (D : LevyDriver.{u, v, w} P d ν)
    (a b : Fin d) {g h : E → ℝ} (hg : MemLp g 2 ν) (hh : MemLp h 2 ν) {Cg Ch : ℝ}
    (hbg : ∀ e, |g e| ≤ Cg) (hbh : ∀ e, |h e| ≤ Ch) {s t : ℝ} (hs : 0 ≤ s) (hst : s ≤ t) :
    ∫ ω, levyCellBrownian D s t a b ω * levyCellProduct D s t g h ω ∂P = 0 := by
  rw [D.integral_mul_eq_mul_integral_of_sigmaPoisson (measurable_levyCellBrownian_iSup D s t a b)
      ((aestronglyMeasurable_sigmaPoisson_compensatedProduct D hg hh hbg hbh hs hst).congr
        (levyCellProduct_ae_eq D s t g h).symm),
    integral_levyCellBrownian D a b hs hst, zero_mul]

end LevyStochCalc.Driver
