/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.Joint
import LevyStochCalc.Brownian.Transport
import LevyStochCalc.Poisson.Transport

/-!
# Existence of a Lévy driver

For every `d` and every σ-finite intensity `ν` on a standard Borel space, some probability
space carries a `d`-dimensional Brownian motion together with a Poisson random measure with
intensity `ν` generating an independent σ-algebra — a `LevyDriver`.

The space is the product of a space carrying the Brownian motion
(`MultidimBrownianMotion.exists`) and one carrying the Poisson random measure
(`PoissonRandomMeasure.exists_of_sigmaFinite`); both projections are measure preserving, so
each driver transports to the product, and there the two σ-algebras factor through the two
coordinates, which are independent under a product measure.

Consequently the hypothesis carried by the SDE/BSDEJ layer — one filtration `ℱ` for which
every coordinate of `W` is a Brownian motion and `N` a Poisson random measure — is
satisfiable: `LevyDriver.filtration` is such an `ℱ` (`LevyDriver.isBrownianFiltration`,
`LevyDriver.isPoissonFiltration`).
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Driver

universe v

variable {Ω₁ : Type v} [MeasurableSpace Ω₁] {Ω₂ : Type v} [MeasurableSpace Ω₂]
  {E : Type v} [MeasurableSpace E]
  {P₁ : Measure Ω₁} [IsProbabilityMeasure P₁] {P₂ : Measure Ω₂} [IsProbabilityMeasure P₂]
  {ν : Measure E} [SigmaFinite ν] {d : ℕ}

/-- The σ-algebra generated by a Brownian motion transported from the first factor of a
product space is contained in the σ-algebra of that factor. -/
lemma sigmaBrownian_comap_fst_le (W : Brownian.BrownianMotion P₁) :
    Brownian.sigmaBrownian (W.comap (measurePreserving_fst (μ := P₁) (ν := P₂)))
      ≤ MeasurableSpace.comap Prod.fst ‹MeasurableSpace Ω₁› :=
  iSup_le fun t =>
    Measurable.comap_le ((W.measurable_eval t).comp (Measurable.of_comap_le le_rfl))

/-- The σ-algebra generated by a Poisson random measure transported from the second factor
of a product space is contained in the σ-algebra of that factor. -/
lemma sigmaPoisson_comap_snd_le (N : Poisson.PoissonRandomMeasure P₂ ν) :
    sigmaPoisson (N.comap (measurePreserving_snd (μ := P₁) (ν := P₂)))
      ≤ MeasurableSpace.comap Prod.snd ‹MeasurableSpace Ω₂› :=
  iSup₂_le fun _ hB =>
    Measurable.comap_le ((N.measurable_eval hB).comp (Measurable.of_comap_le le_rfl))

/-- On a product probability space the two coordinate σ-algebras are independent. -/
lemma indep_comap_fst_comap_snd :
    Indep (MeasurableSpace.comap Prod.fst ‹MeasurableSpace Ω₁›)
      (MeasurableSpace.comap Prod.snd ‹MeasurableSpace Ω₂›) (P₁.prod P₂) :=
  indepFun_prod (X := id) (Y := id) (μ := P₁) (ν := P₂) measurable_id measurable_id

/-- The Lévy driver on the product space carrying `W` on the first factor and `N` on the
second; the two are independent because the product measure makes the coordinates so. -/
noncomputable def levyDriverProd (W : Brownian.Multidim.MultidimBrownianMotion P₁ d)
    (N : Poisson.PoissonRandomMeasure P₂ ν) : LevyDriver (P₁.prod P₂) d ν where
  W := W.comap measurePreserving_fst
  N := N.comap measurePreserving_snd
  indep :=
    indep_of_indep_of_le_left
      (indep_of_indep_of_le_right indep_comap_fst_comap_snd (sigmaPoisson_comap_snd_le N))
      (iSup_le fun i => sigmaBrownian_comap_fst_le (W.W i))

/-- **Existence of a Lévy driver.** For every `d` and every σ-finite intensity `ν` on a
standard Borel space, some probability space carries a `d`-dimensional Brownian motion and a
Poisson random measure with intensity `ν` generating independent σ-algebras. -/
theorem LevyDriver.exists (d : ℕ) (E : Type v) [MeasurableSpace E] [StandardBorelSpace E]
    (ν : Measure E) [SigmaFinite ν] :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P),
      Nonempty (LevyDriver P d ν) := by
  obtain ⟨Ω₁, _, P₁, _, ⟨W⟩⟩ :=
    Brownian.Multidim.MultidimBrownianMotion.exists.{v} d
  obtain ⟨Ω₂, _, P₂, _, ⟨N⟩⟩ := Poisson.PoissonRandomMeasure.exists_of_sigmaFinite E ν
  exact ⟨Ω₁ × Ω₂, inferInstance, P₁.prod P₂, inferInstance, ⟨levyDriverProd W N⟩⟩

/-- **A filtration carrying both driver properties exists.** For every `d` and every σ-finite
intensity `ν` on a standard Borel space there are a probability space, a `d`-dimensional
Brownian motion `W`, a Poisson random measure `N` with intensity `ν`, and one filtration for
which every coordinate of `W` is a Brownian motion and `N` is a Poisson random measure.

This is the hypothesis that `JumpDiffusion.is_solution`, the Itô–Lévy formula, the Picard
iteration and `IsBSDEJSolution` carry; it is satisfiable, and `ℱ = ⊤` does not satisfy it.
It does *not* say that those statements have solutions — only that the filtration hypothesis
common to all of them is not vacuous. -/
theorem exists_isBrownianFiltration_and_isPoissonFiltration (d : ℕ) (E : Type v)
    [MeasurableSpace E] [StandardBorelSpace E] (ν : Measure E) [SigmaFinite ν] :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P)
      (D : LevyDriver P d ν),
      (∀ j, Brownian.IsBrownianFiltration (D.W.W j) D.filtration) ∧
        Poisson.IsPoissonFiltration D.N D.filtration := by
  obtain ⟨Ω, _, P, _, ⟨D⟩⟩ := LevyDriver.exists d E ν
  exact ⟨Ω, inferInstance, P, inferInstance, D, D.isBrownianFiltration, D.isPoissonFiltration⟩

end LevyStochCalc.Driver
