/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.Filtered
import LevyStochCalc.Brownian.Multidim
import LevyStochCalc.Poisson.Filtered
import LevyStochCalc.Probability.IndepJoin

/-!
# The joint filtration of an independent Brownian motion and Poisson random measure

A `LevyDriver` is a `d`-dimensional Brownian motion `W` and a Poisson random measure `N` on one
probability space, with `σ(W)` independent of `σ(N)`. Its joint natural filtration
`(⨆ i, ℱ^{Wⁱ}) ⊔ ℱ^N` is one for which every coordinate `Wⁱ` is a Brownian motion and `N` a
Poisson random measure (`LevyDriver.isBrownianFiltration`, `LevyDriver.isPoissonFiltration`):
the increments of `Wⁱ` after `s` are independent of `ℱ^{Wⁱ} s`, and the rest of the joint
filtration at time `s` is independent of `σ(Wⁱ)` altogether, so the join stays independent
(`indep_sup_left_of_indep`); likewise for the future counts of `N`.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Driver

lemma _root_.MeasureTheory.Filtration.iSup_apply' {Ω ι : Type*} {m : MeasurableSpace Ω}
    (f : ι → Filtration ℝ m) (s : ℝ) : (⨆ i, f i) s = ⨆ i, f i s := by
  change sSup (Set.range f) s = _
  rw [Filtration.sSup_def, sSup_image, iSup_range]

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d : ℕ}

/-- The σ-algebra generated by all the values of a Brownian motion. -/
noncomputable abbrev sigmaBrownian (W : Brownian.BrownianMotion P) : MeasurableSpace Ω :=
  ⨆ t, MeasurableSpace.comap (W.W t) inferInstance

/-- The σ-algebra generated by all the counts of a Poisson random measure. -/
noncomputable abbrev sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) : MeasurableSpace Ω :=
  ⨆ B ∈ {C : Set (ℝ × E) | MeasurableSet C}, MeasurableSpace.comap (fun ω => N.N ω B) inferInstance

lemma sigmaBrownian_le (W : Brownian.BrownianMotion P) : sigmaBrownian W ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun t => (W.measurable_eval t).comap_le

lemma sigmaPoisson_le (N : Poisson.PoissonRandomMeasure P ν) :
    sigmaPoisson N ≤ ‹MeasurableSpace Ω› :=
  iSup₂_le fun _ hB => (N.measurable_eval hB).comap_le

lemma naturalFiltration_le_sigmaBrownian (W : Brownian.BrownianMotion P) (s : ℝ) :
    Brownian.Martingale.naturalFiltration W s ≤ sigmaBrownian W :=
  iSup₂_le fun t _ => le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) t

lemma naturalFiltration_le_sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) (s : ℝ) :
    Poisson.naturalFiltration N s ≤ sigmaPoisson N :=
  iSup₂_le fun B hB => le_iSup₂ (f := fun B (_ : B ∈ {C : Set (ℝ × E) | MeasurableSet C}) =>
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance) B hB.2

lemma comap_increment_le_sigmaBrownian (W : Brownian.BrownianMotion P) (s t : ℝ) :
    MeasurableSpace.comap (fun ω => W.W t ω - W.W s ω) inferInstance ≤ sigmaBrownian W := by
  have ht : Measurable[sigmaBrownian W] (W.W t) :=
    Measurable.of_comap_le (le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) t)
  have hs : Measurable[sigmaBrownian W] (W.W s) :=
    Measurable.of_comap_le (le_iSup (fun t => MeasurableSpace.comap (W.W t) inferInstance) s)
  exact (ht.sub hs).comap_le

lemma comap_count_le_sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) {B : Set (ℝ × E)}
    (hB : MeasurableSet B) :
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance ≤ sigmaPoisson N :=
  le_iSup₂ (f := fun B (_ : B ∈ {C : Set (ℝ × E) | MeasurableSet C}) =>
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance) B hB

/-- `σ(W)` is the σ-algebra generated by the path `ω ↦ (t ↦ W t ω)`. -/
lemma sigmaBrownian_eq_comap_path (W : Brownian.BrownianMotion P) :
    sigmaBrownian W = MeasurableSpace.comap (fun ω t => W.W t ω) MeasurableSpace.pi := by
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  unfold sigmaBrownian
  congr
  funext t
  rw [MeasurableSpace.comap_comp]
  rfl

/-- The coordinates of a multidimensional Brownian motion generate independent σ-algebras. -/
lemma iIndep_sigmaBrownian (W : Brownian.Multidim.MultidimBrownianMotion P d) :
    iIndep (fun i => sigmaBrownian (W.W i)) P := by
  have h := W.components_independent
  rw [iIndepFun_iff_iIndep] at h
  convert h using 1
  funext i
  exact sigmaBrownian_eq_comap_path (W.W i)

/-- The σ-algebra of the other coordinates is independent of `σ(Wʲ)`. -/
lemma indep_iSup_sigmaBrownian_ne (W : Brownian.Multidim.MultidimBrownianMotion P d) (j : Fin d) :
    Indep (⨆ i ∈ {i : Fin d | i ≠ j}, sigmaBrownian (W.W i)) (sigmaBrownian (W.W j)) P := by
  have h := indep_iSup_of_disjoint (fun i => sigmaBrownian_le (W.W i)) (iIndep_sigmaBrownian W)
    (S := {i : Fin d | i ≠ j}) (T := {j}) (by simp [Set.disjoint_left])
  simpa using h

/-- A `d`-dimensional Brownian motion and a Poisson random measure on one probability space,
generating independent σ-algebras. -/
structure LevyDriver (P : Measure Ω) [IsProbabilityMeasure P] (d : ℕ) (ν : Measure E)
    [SigmaFinite ν] where
  /-- The Brownian motion. -/
  W : Brownian.Multidim.MultidimBrownianMotion P d
  /-- The Poisson random measure. -/
  N : Poisson.PoissonRandomMeasure.{u, v, w} P ν
  /-- `σ(W)` and `σ(N)` are independent. -/
  indep : Indep (⨆ i, sigmaBrownian (W.W i)) (sigmaPoisson N) P

namespace LevyDriver

variable (D : LevyDriver.{u, v, w} P d ν)

/-- The joint natural filtration of the driver, `(⨆ i, ℱ^{Wⁱ}) ⊔ ℱ^N`. -/
noncomputable def filtration : Filtration ℝ ‹MeasurableSpace Ω› :=
  (⨆ i, Brownian.Martingale.naturalFiltration (D.W.W i)) ⊔ Poisson.naturalFiltration D.N

lemma filtration_apply (s : ℝ) :
    D.filtration s = (⨆ i, Brownian.Martingale.naturalFiltration (D.W.W i) s)
      ⊔ Poisson.naturalFiltration D.N s := by
  unfold filtration
  rw [Filtration.coeFn_sup, Pi.sup_apply, Filtration.iSup_apply']

lemma naturalFiltration_brownian_le (j : Fin d) (s : ℝ) :
    Brownian.Martingale.naturalFiltration (D.W.W j) s ≤ D.filtration s := by
  rw [filtration_apply]
  exact le_sup_of_le_left (le_iSup (fun i => Brownian.Martingale.naturalFiltration (D.W.W i) s) j)

lemma naturalFiltration_poisson_le (s : ℝ) : Poisson.naturalFiltration D.N s ≤ D.filtration s := by
  rw [filtration_apply]
  exact le_sup_right

/-- Every coordinate of `W` is a Brownian motion for the joint filtration. -/
theorem isBrownianFiltration (j : Fin d) : Brownian.IsBrownianFiltration (D.W.W j)
      D.filtration where
  measurable t :=
    ((Brownian.isBrownianFiltration_natural (D.W.W j)).measurable t).mono
      (D.naturalFiltration_brownian_le j t) le_rfl
  indep := by
    intro s t hs hst
    have hfilt : D.filtration s ≤ Brownian.Martingale.naturalFiltration (D.W.W j) s ⊔
        ((⨆ i ∈ {i : Fin d | i ≠ j}, Brownian.Martingale.naturalFiltration (D.W.W i) s)
          ⊔ Poisson.naturalFiltration D.N s) := by
      rw [filtration_apply]
      refine sup_le (iSup_le fun i => ?_) (le_sup_of_le_right le_sup_right)
      by_cases hij : i = j
      · subst hij
        exact le_sup_left
      · exact le_sup_of_le_right (le_sup_of_le_left
          (le_iSup₂ (f := fun i (_ : i ∈ {i : Fin d | i ≠ j}) =>
            Brownian.Martingale.naturalFiltration (D.W.W i) s) i hij))
    refine indep_of_indep_of_le_left ?_ hfilt
    -- σ(the other coordinates) ⊔ σ(N) is independent of σ(Wʲ)
    have hrest : Indep ((⨆ i ∈ {i : Fin d | i ≠ j}, sigmaBrownian (D.W.W i)) ⊔ sigmaPoisson D.N)
        (sigmaBrownian (D.W.W j)) P := by
      refine Probability.indep_sup_left_of_indep (iSup₂_le fun i _ => sigmaBrownian_le _)
        (sigmaPoisson_le _) (sigmaBrownian_le _) (indep_iSup_sigmaBrownian_ne D.W j) ?_
      refine indep_of_indep_of_le_right D.indep.symm (sup_le (iSup₂_le fun i _ => ?_) ?_)
      · exact le_iSup (fun i => sigmaBrownian (D.W.W i)) i
      · exact le_iSup (fun i => sigmaBrownian (D.W.W i)) j
    refine Probability.indep_sup_left_of_indep
      ((naturalFiltration_le_sigmaBrownian _ s).trans (sigmaBrownian_le _)) ?_
      ((comap_increment_le_sigmaBrownian (D.W.W j) s t).trans (sigmaBrownian_le _))
      ((Brownian.isBrownianFiltration_natural (D.W.W j)).indep hs hst) ?_
    · exact sup_le (iSup₂_le fun i _ => (naturalFiltration_le_sigmaBrownian _ s).trans
        (sigmaBrownian_le _)) ((naturalFiltration_le_sigmaPoisson _ s).trans (sigmaPoisson_le _))
    · refine indep_of_indep_of_le_right (indep_of_indep_of_le_left hrest ?_) ?_
      · exact sup_le (iSup₂_le fun i hi => le_sup_of_le_left
          (le_iSup₂_of_le i hi (naturalFiltration_le_sigmaBrownian _ s)))
          (le_sup_of_le_right (naturalFiltration_le_sigmaPoisson _ s))
      · exact sup_le (naturalFiltration_le_sigmaBrownian _ s)
          (comap_increment_le_sigmaBrownian (D.W.W j) s t)

/-- `N` is a Poisson random measure for the joint filtration. -/
theorem isPoissonFiltration : Poisson.IsPoissonFiltration D.N D.filtration where
  measurable _ _ hB hBm :=
    ((Poisson.isPoissonFiltration_natural D.N).measurable hB hBm).mono
      (D.naturalFiltration_poisson_le _) le_rfl
  indep := by
    intro s t hs hst A hA hAν
    rw [filtration_apply, sup_comm]
    refine Probability.indep_sup_left_of_indep
      ((naturalFiltration_le_sigmaPoisson _ s).trans (sigmaPoisson_le _))
      (iSup_le fun i => (naturalFiltration_le_sigmaBrownian _ s).trans (sigmaBrownian_le _))
      ((comap_count_le_sigmaPoisson D.N (measurableSet_Ioc.prod hA)).trans (sigmaPoisson_le _))
      ((Poisson.isPoissonFiltration_natural D.N).indep hs hst hA hAν) ?_
    refine indep_of_indep_of_le_right (indep_of_indep_of_le_left D.indep ?_) ?_
    · exact iSup_le fun i => le_iSup_of_le i (naturalFiltration_le_sigmaBrownian _ s)
    · exact sup_le (naturalFiltration_le_sigmaPoisson _ s)
        (comap_count_le_sigmaPoisson D.N (measurableSet_Ioc.prod hA))

end LevyDriver

end LevyStochCalc.Driver
