/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Brownian.MultidimFiltered
import LevyStochCalc.Poisson.Filtered
import LevyStochCalc.Probability.IndepJoin

/-!
# The joint filtration of an independent Brownian motion and Poisson random measure

A `LevyDriver` is a `d`-dimensional Brownian motion `W` and a Poisson random measure `N` on one
probability space, with `σ(W)` independent of `σ(N)`. Its joint natural filtration
`(⨆ i, ℱ^{Wⁱ}) ⊔ ℱ^N` is one for which every coordinate `Wⁱ` is a Brownian motion and `N` a
Poisson random measure (`LevyDriver.isBrownianFiltration`, `LevyDriver.isPoissonFiltration`):
the increments of `Wⁱ` after `s` are independent of `ℱ^{Wⁱ} s`, and the rest of the joint
filtration at time `s` is independent of `σ(Wⁱ)` altogether, so the join stays independent
(`indep_sup_left_of_indep`); likewise for the future counts of `N`.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d : ℕ}

/-- The σ-algebra generated by all the counts of a Poisson random measure. -/
noncomputable abbrev sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) : MeasurableSpace Ω :=
  ⨆ B ∈ {C : Set (ℝ × E) | MeasurableSet C}, MeasurableSpace.comap (fun ω => N.N ω B) inferInstance

lemma sigmaPoisson_le (N : Poisson.PoissonRandomMeasure P ν) :
    sigmaPoisson N ≤ ‹MeasurableSpace Ω› :=
  iSup₂_le fun _ hB => (N.measurable_eval hB).comap_le

lemma naturalFiltration_le_sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) (s : ℝ) :
    Poisson.naturalFiltration N s ≤ sigmaPoisson N :=
  iSup₂_le fun B hB => le_iSup₂ (f := fun B (_ : B ∈ {C : Set (ℝ × E) | MeasurableSet C}) =>
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance) B hB.2

lemma comap_count_le_sigmaPoisson (N : Poisson.PoissonRandomMeasure P ν) {B : Set (ℝ × E)}
    (hB : MeasurableSet B) :
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance ≤ sigmaPoisson N :=
  le_iSup₂ (f := fun B (_ : B ∈ {C : Set (ℝ × E) | MeasurableSet C}) =>
    MeasurableSpace.comap (fun ω => N.N ω B) inferInstance) B hB

/-- A `d`-dimensional Brownian motion and a Poisson random measure on one probability space,
generating independent σ-algebras. -/
structure LevyDriver (P : Measure Ω) [IsProbabilityMeasure P] (d : ℕ) (ν : Measure E)
    [SigmaFinite ν] where
  /-- The Brownian motion. -/
  W : Brownian.Multidim.MultidimBrownianMotion P d
  /-- The Poisson random measure. -/
  N : Poisson.PoissonRandomMeasure.{u, v, w} P ν
  /-- `σ(W)` and `σ(N)` are independent. -/
  indep : Indep (⨆ i, Brownian.sigmaBrownian (W.W i)) (sigmaPoisson N) P

namespace LevyDriver

variable (D : LevyDriver.{u, v, w} P d ν)

/-- The joint natural filtration of the driver, `(⨆ i, ℱ^{Wⁱ}) ⊔ ℱ^N`. -/
noncomputable def filtration : Filtration ℝ ‹MeasurableSpace Ω› :=
  D.W.naturalFiltration ⊔ Poisson.naturalFiltration D.N

lemma filtration_apply (s : ℝ) :
    D.filtration s = D.W.naturalFiltration s ⊔ Poisson.naturalFiltration D.N s := by
  unfold filtration
  rw [Filtration.coeFn_sup, Pi.sup_apply]

lemma naturalFiltration_brownian_le (s : ℝ) : D.W.naturalFiltration s ≤ D.filtration s := by
  rw [filtration_apply]
  exact le_sup_left

lemma naturalFiltration_poisson_le (s : ℝ) : Poisson.naturalFiltration D.N s ≤ D.filtration s := by
  rw [filtration_apply]
  exact le_sup_right

/-- Every coordinate of `W` is a Brownian motion for the joint filtration. -/
theorem isBrownianFiltration (j : Fin d) :
    Brownian.IsBrownianFiltration (D.W.W j) D.filtration :=
  (D.W.isBrownianFiltration_natural j).of_le_sup
    (fun t => ((D.W.isBrownianFiltration_natural j).measurable t).mono
      (D.naturalFiltration_brownian_le t) le_rfl)
    (m := fun s => Poisson.naturalFiltration D.N s) (fun s => (Poisson.naturalFiltration D.N).le s)
    (fun s => (D.filtration_apply s).le)
    (fun s t _ _ => indep_of_indep_of_le_right
      (indep_of_indep_of_le_left D.indep.symm (naturalFiltration_le_sigmaPoisson _ s))
      (sup_le (D.W.naturalFiltration_le_iSup_sigmaBrownian s)
        ((Brownian.comap_increment_le_sigmaBrownian (D.W.W j) s t).trans
          (le_iSup (fun i => Brownian.sigmaBrownian (D.W.W i)) j))))

/-- `N` is a Poisson random measure for the joint filtration. -/
theorem isPoissonFiltration : Poisson.IsPoissonFiltration D.N D.filtration where
  measurable _ _ hB hBm :=
    ((Poisson.isPoissonFiltration_natural D.N).measurable hB hBm).mono
      (D.naturalFiltration_poisson_le _) le_rfl
  indep := by
    intro s t hs hst A hA hAν
    rw [filtration_apply, sup_comm]
    refine Probability.indep_sup_left_of_indep
      ((naturalFiltration_le_sigmaPoisson _ s).trans (sigmaPoisson_le _))
      (D.W.naturalFiltration.le s)
      ((comap_count_le_sigmaPoisson D.N (measurableSet_Ioc.prod hA)).trans (sigmaPoisson_le _))
      ((Poisson.isPoissonFiltration_natural D.N).indep hs hst hA hAν) ?_
    refine indep_of_indep_of_le_right
      (indep_of_indep_of_le_left D.indep (D.W.naturalFiltration_le_iSup_sigmaBrownian s)) ?_
    exact sup_le (naturalFiltration_le_sigmaPoisson _ s)
      (comap_count_le_sigmaPoisson D.N (measurableSet_Ioc.prod hA))

end LevyDriver

end LevyStochCalc.Driver
