/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.GaussianInitial
import LevyStochCalc.Brownian.StandardBorel
import LevyStochCalc.Poisson.StandardBorel

/-!
# Lévy drivers on a standard Borel space

For every `d` and every σ-finite intensity `ν` on a standard Borel mark space `E`, the product of
a standard Borel space carrying a `d`-dimensional Brownian motion
(`MultidimBrownianMotion.exists_standardBorel`) and one carrying a Poisson random measure with
intensity `ν` (`PoissonRandomMeasure.exists_standardBorel`) is standard Borel and carries a Lévy
driver (`levyDriverProd`).

On `Ω × X` under `P ⊗ μ₀`, the pullback of a Lévy driver `D` along the first projection is a Lévy
driver whose joint filtration factors through the first coordinate, so the second coordinate is an
initial value of law `μ₀` independent of `⨆ t, ℱ_t`. When `X` is standard Borel so is `Ω × X`.

## Main definitions

* `LevyStochCalc.Driver.LevyDriver.prodInitial`: the pullback of `D` to `Ω × X` under `P ⊗ μ₀`
  along the first projection.

## Main statements

* `LevyStochCalc.Driver.LevyDriver.exists_standardBorel`: for every `d` and every σ-finite
  intensity `ν` on a standard Borel mark space, some standard Borel probability space carries a
  Lévy driver.
* `LevyStochCalc.Driver.LevyDriver.indep_comap_snd_iSup_filtration_prodInitial`: under `P ⊗ μ₀`
  the σ-algebra of the second coordinate is independent of `⨆ t, ℱ_t` for `D.prodInitial μ₀`.
* `LevyStochCalc.Driver.LevyDriver.exists_standardBorel_initial`: the same space may also carry a
  random element of a standard Borel space with any prescribed law, whose σ-algebra is
  independent of `⨆ t, ℱ_t`.
* `LevyStochCalc.Driver.LevyDriver.exists_standardBorel_initial_memLp`: an initial σ-algebra `𝒢₀`
  independent of `⨆ t, ℱ_t` carrying an `ℝⁿ`-valued initial value of any square-integrable law.
-/

open MeasureTheory ProbabilityTheory

namespace LevyStochCalc.Driver

universe u v w

namespace LevyDriver

/-- **Existence of a Lévy driver on a standard Borel space.** For every `d` and every σ-finite
intensity `ν` on a standard Borel mark space `E`, some standard Borel probability space carries a
`d`-dimensional Brownian motion and a Poisson random measure with intensity `ν` generating
independent σ-algebras. -/
theorem exists_standardBorel (d : ℕ) (E : Type v) [MeasurableSpace E] [StandardBorelSpace E]
    (ν : Measure E) [SigmaFinite ν] :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P),
      StandardBorelSpace Ω ∧ Nonempty (LevyDriver.{v, v, w} P d ν) := by
  obtain ⟨Ω₁, _, P₁, _, _, ⟨W⟩⟩ :=
    Brownian.Multidim.MultidimBrownianMotion.exists_standardBorel.{v} d
  obtain ⟨Ω₂, _, P₂, _, _, ⟨N⟩⟩ := Poisson.PoissonRandomMeasure.exists_standardBorel.{v, w} E ν
  exact ⟨Ω₁ × Ω₂, inferInstance, P₁.prod P₂, inferInstance, inferInstance, ⟨levyDriverProd W N⟩⟩

section Initial

variable {Ω : Type u} [MeasurableSpace Ω] {X : Type u} [MeasurableSpace X]
  {E : Type v} [MeasurableSpace E] {P : Measure Ω} [IsProbabilityMeasure P]
  {ν : Measure E} [SigmaFinite ν] {d : ℕ} (μ₀ : Measure X) [IsProbabilityMeasure μ₀]

/-- The Lévy driver on `Ω × X` under `P ⊗ μ₀` read off the first coordinate. -/
noncomputable def prodInitial (D : LevyDriver.{u, v, w} P d ν) :
    LevyDriver.{u, v, w} (P.prod μ₀) d ν :=
  D.comap (measurePreserving_fst (μ := P) (ν := μ₀))

/-- The joint filtration of `D.prodInitial μ₀` is the comap along the first projection of the
joint filtration of `D`. -/
theorem filtration_prodInitial (D : LevyDriver.{u, v, w} P d ν) (s : ℝ) :
    (D.prodInitial μ₀).filtration s = (D.filtration s).comap Prod.fst :=
  D.filtration_comap _ s

/-- Under `P ⊗ μ₀` the σ-algebra of the second coordinate is independent of the σ-algebra
generated by the whole joint filtration of `D.prodInitial μ₀`. -/
theorem indep_comap_snd_iSup_filtration_prodInitial (D : LevyDriver.{u, v, w} P d ν) :
    Indep (MeasurableSpace.comap (Prod.snd : Ω × X → X) inferInstance)
      (⨆ t, (D.prodInitial μ₀).filtration t) (P.prod μ₀) := by
  have hprod : Indep (MeasurableSpace.comap (Prod.snd : Ω × X → X) inferInstance)
      (MeasurableSpace.comap (Prod.fst : Ω × X → Ω) inferInstance) (P.prod μ₀) :=
    (indepFun_prod (μ := P) (ν := μ₀) (X := id) (Y := id) measurable_id measurable_id).symm
  refine indep_of_indep_of_le_right hprod (iSup_le fun t => ?_)
  rw [D.filtration_prodInitial μ₀ t]
  exact MeasurableSpace.comap_mono (D.filtration.le t)

end Initial

/-- **A Lévy driver on a standard Borel space with an independent initial value of any law.**
For every `d`, every σ-finite intensity `ν` on a standard Borel mark space `E`, and every
probability measure `μ₀` on a standard Borel space `X`, some standard Borel probability space
carries a Lévy driver `D` and a random element `ξ₀` of `X` with law `μ₀` whose σ-algebra is
independent of the σ-algebra generated by the joint filtration of `D`. -/
theorem exists_standardBorel_initial (d : ℕ) (E : Type v) [MeasurableSpace E]
    [StandardBorelSpace E] (ν : Measure E) [SigmaFinite ν] {X : Type v} [MeasurableSpace X]
    [StandardBorelSpace X] (μ₀ : Measure X) [IsProbabilityMeasure μ₀] :
    ∃ (Ω : Type v) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P),
      StandardBorelSpace Ω ∧ ∃ (D : LevyDriver.{v, v, w} P d ν) (ξ₀ : Ω → X),
        MeasurePreserving ξ₀ P μ₀ ∧
          Indep (MeasurableSpace.comap ξ₀ inferInstance) (⨆ t, D.filtration t) P := by
  obtain ⟨Ω, _, P, _, _, ⟨D⟩⟩ := LevyDriver.exists_standardBorel.{v, w} d E ν
  exact ⟨Ω × X, inferInstance, P.prod μ₀, inferInstance, inferInstance, D.prodInitial μ₀,
    Prod.snd, measurePreserving_snd, D.indep_comap_snd_iSup_filtration_prodInitial μ₀⟩

/-- **A Lévy driver on a standard Borel space with an independent square-integrable initial
value in `ℝⁿ`.** For every `d`, every σ-finite intensity `ν` on a standard Borel mark space `E`,
and every probability measure `μ₀` on `ℝⁿ` whose coordinates are square integrable, some standard
Borel probability space carries a Lévy driver `D`, a sub-σ-algebra `𝒢₀` independent of the
σ-algebra generated by the joint filtration of `D`, and `𝒢₀`-measurable square-integrable
coordinates `ξ₀ a` whose joint law is `μ₀`. -/
theorem exists_standardBorel_initial_memLp (d n : ℕ) (E : Type v) [MeasurableSpace E]
    [StandardBorelSpace E] (ν : Measure E) [SigmaFinite ν] (μ₀ : Measure (Fin n → ℝ))
    [IsProbabilityMeasure μ₀] (hμ₀ : ∀ a, MemLp (fun x => x a) 2 μ₀) :
    ∃ (Ω : Type v) (𝒢₀ : MeasurableSpace Ω) (mΩ : MeasurableSpace Ω) (P : Measure Ω)
      (_ : IsProbabilityMeasure P), StandardBorelSpace Ω ∧ ∃ (D : LevyDriver.{v, v, w} P d ν)
        (ξ₀ : Fin n → Ω → ℝ), 𝒢₀ ≤ mΩ ∧ Indep 𝒢₀ (⨆ t, D.filtration t) P ∧
          (∀ a, StronglyMeasurable[𝒢₀] (ξ₀ a)) ∧ (∀ a, MemLp (ξ₀ a) 2 P) ∧
          MeasurePreserving (fun ω a => ξ₀ a ω) P μ₀ := by
  let e : ULift.{v} (Fin n → ℝ) ≃ᵐ (Fin n → ℝ) := MeasurableEquiv.ulift
  haveI : IsProbabilityMeasure (μ₀.map e.symm) :=
    Measure.isProbabilityMeasure_map e.symm.measurable.aemeasurable
  obtain ⟨Ω, _, P, _, _, D, ξ, hξ, hind⟩ :=
    LevyDriver.exists_standardBorel_initial.{v, w} d E ν (μ₀.map e.symm)
  have he : MeasurePreserving e (μ₀.map e.symm) μ₀ :=
    ⟨e.measurable, by rw [Measure.map_map e.measurable e.symm.measurable]; simp⟩
  have hmp : MeasurePreserving (fun ω a => (e (ξ ω)) a) P μ₀ := he.comp hξ
  refine ⟨Ω, MeasurableSpace.comap ξ inferInstance, inferInstance, P, inferInstance,
    inferInstance, D, fun a ω => e (ξ ω) a, hξ.measurable.comap_le, hind, fun a => ?_,
    fun a => (hμ₀ a).comp_measurePreserving hmp, hmp⟩
  exact ((measurable_pi_apply a).comp
    (e.measurable.comp (Measurable.of_comap_le le_rfl))).stronglyMeasurable

end LevyDriver

end LevyStochCalc.Driver
