/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.GridIncrement

/-!
# The driver's data at finitely many times, against `ℱ₊ 0`

Along a grid starting at `s > 0` the driver's data measured from `s` is independent of `ℱ₊ s`
(`Driver/GridIncrement.lean`), hence of the smaller `ℱ₊ 0`. Letting `s ↓ 0` turns increments into
values: `W_t − W_s → W_t` because `W` is continuous with `W 0 = 0`, and the count on the part of a
region after `s` increases to the count on its part after `0`. So `ℱ₊ 0` is independent of the
σ-algebra generated by the driver's values at any finite set of positive times together with the
counts on the corresponding pieces of any finite family of regions.

## Main statements

* `LevyDriver.valueSigma` — the σ-algebra of that data at one time.
* `LevyDriver.indep_iSup_valueSigma` — finitely many of them against `ℱ₊ 0`.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d : ℕ}

namespace LevyDriver

variable (D : LevyDriver.{u, v, w} P d ν)

/-- The σ-algebra generated by the driver's data up to time `t`: the Brownian coordinates at `t`
and the counts on the parts of the regions `C k` lying in `(0, t]`. -/
noncomputable abbrev valueSigma {m : ℕ} (C : Fin m → Set (ℝ × E)) (t : ℝ) : MeasurableSpace Ω :=
  (⨆ j : Fin d, MeasurableSpace.comap (fun ω => (D.W.W j).W t ω) inferInstance)
    ⊔ ⨆ k, D.regionSigma (C k ∩ Set.Ioc 0 t ×ˢ Set.univ)

/-- **The driver's data at finitely many positive times is independent of `ℱ₊ 0`.** -/
theorem indep_iSup_valueSigma {m : ℕ} (C : Fin m → Set (ℝ × E))
    (hCm : ∀ k, MeasurableSet (C k)) {t : ℕ → ℝ} (ht : StrictMono t) (ht0 : 0 < t 0) (n : ℕ) :
    Indep (⨆ l, ⨆ _ : l < n, D.valueSigma C (t l)) (D.filtration.rightCont 0) P := by
  classical
  -- a sequence of starting points decreasing to `0`, all below `t 0`
  set c : ℕ → ℝ := fun p => t 0 / (p + 2) with hc
  have hc_pos : ∀ p, 0 < c p := fun p => div_pos ht0 (by positivity)
  have hc_lt : ∀ p, c p < t 0 := fun p => by
    have h2 : (1 : ℝ) < (p : ℝ) + 2 := by
      have : (0 : ℝ) ≤ (p : ℝ) := Nat.cast_nonneg p
      linarith
    calc c p = t 0 / ((p : ℝ) + 2) := rfl
      _ < t 0 / 1 := div_lt_div_of_pos_left ht0 zero_lt_one h2
      _ = t 0 := div_one _
  have hc_anti : Antitone c := fun a b hab =>
    div_le_div_of_nonneg_left ht0.le (by positivity)
      (by exact_mod_cast Nat.add_le_add_right hab 2)
  have hc_tend : Filter.Tendsto c Filter.atTop (nhds 0) := by
    have h := (tendsto_const_div_atTop_nhds_zero_nat (t 0)).comp (Filter.tendsto_add_atTop_nat 2)
    simpa [hc, Function.comp_def, add_comm] using h
  -- the grid: `c p` first, then the given times
  set g : ℕ → ℕ → ℝ := fun p j => if j = 0 then c p else t (j - 1) with hg
  have hg_mono : ∀ p, StrictMono (g p) := by
    intro p a b hab
    rcases Nat.eq_zero_or_pos a with rfl | ha
    · have hb : b ≠ 0 := by omega
      simp only [hg, if_pos rfl, if_neg hb]
      exact (hc_lt p).trans_le (ht.monotone (Nat.zero_le _))
    · have ha' : a ≠ 0 := by omega
      have hb' : b ≠ 0 := by omega
      simp only [hg, if_neg ha', if_neg hb']
      exact ht (by omega)
  have hg0 : ∀ p, g p 0 = c p := fun p => by simp [hg]
  have hgk : ∀ p l, g p (l + 1) = t l := fun p l => by simp [hg]
  -- the data measured from `c p`, and its limit
  set X : ℕ → Ω → (Fin d × Fin n → ℝ) × (Fin n × Fin m → ℝ≥0∞) := fun p ω =>
    (fun q => (D.W.W q.1).W (t q.2) ω - (D.W.W q.1).W (c p) ω,
      fun q => D.N.N ω (C q.2 ∩ Set.Ioc (c p) (t q.1) ×ˢ Set.univ)) with hX
  set Y : Ω → (Fin d × Fin n → ℝ) × (Fin n × Fin m → ℝ≥0∞) := fun ω =>
    (fun q => (D.W.W q.1).W (t q.2) ω,
      fun q => D.N.N ω (C q.2 ∩ Set.Ioc 0 (t q.1) ×ˢ Set.univ)) with hY
  have hrm : ∀ (a b : ℝ) (k : Fin m), MeasurableSet (C k ∩ Set.Ioc a b ×ˢ Set.univ) :=
    fun a b k => (hCm k).inter (measurableSet_Ioc.prod MeasurableSet.univ)
  have hX_meas : ∀ p, Measurable (X p) := fun p =>
    (measurable_pi_lambda _ fun q : Fin d × Fin n =>
      ((D.W.W q.1).measurable_eval (t q.2)).sub ((D.W.W q.1).measurable_eval (c p))).prodMk
    (measurable_pi_lambda _ fun q : Fin n × Fin m =>
      D.N.measurable_eval (hrm (c p) (t q.1) q.2))
  have hY_meas : Measurable Y :=
    (measurable_pi_lambda _ fun q : Fin d × Fin n =>
      (D.W.W q.1).measurable_eval (t q.2)).prodMk
      (measurable_pi_lambda _ fun q : Fin n × Fin m =>
        D.N.measurable_eval (hrm 0 (t q.1) q.2))
  have key : Indep (D.filtration.rightCont 0)
      (MeasurableSpace.comap Y inferInstance) P := by
    refine Probability.indep_comap_of_tendsto_ae (D.filtration.rightCont.le 0)
      hX_meas hY_meas (fun p => ?_) ?_
    · have hstart : 0 ≤ g p 0 := by rw [hg0 p]; exact (hc_pos p).le
      have hgrid := D.indep_iSup_stepSigma_start C hCm (hg_mono p) hstart n
      rw [hg0 p] at hgrid
      refine indep_of_indep_of_le_right (indep_of_indep_of_le_left hgrid.symm
        (D.filtration.rightCont.mono (hc_pos p).le)) ?_
      rw [hX, Probability.comap_prod_eq_sup,
        Probability.comap_pi_eq_iSup (fun q : Fin d × Fin n => fun ω =>
          (D.W.W q.1).W (t q.2) ω - (D.W.W q.1).W (c p) ω),
        Probability.comap_pi_eq_iSup (fun q : Fin n × Fin m => fun ω =>
          D.N.N ω (C q.2 ∩ Set.Ioc (c p) (t q.1) ×ˢ Set.univ))]
      refine sup_le (iSup_le fun q => ?_) (iSup_le fun q => ?_)
      · refine le_iSup₂_of_le (q.2 : ℕ) q.2.2 ?_
        rw [hgk p (q.2 : ℕ)]
        exact le_sup_of_le_left (le_iSup (fun j => D.incrementSigma j (c p) (t q.2)) q.1)
      · refine le_iSup₂_of_le (q.1 : ℕ) q.1.2 ?_
        rw [hgk p (q.1 : ℕ)]
        exact le_sup_of_le_right (le_iSup (fun k =>
          D.regionSigma (C k ∩ Set.Ioc (c p) (t q.1) ×ˢ Set.univ)) q.2)
    · filter_upwards [ae_all_iff.2 fun j : Fin d => (D.W.W j).continuous_paths,
        ae_all_iff.2 fun j : Fin d => (D.W.W j).initial_zero] with ω hcont hzero
      refine Filter.Tendsto.prodMk_nhds (tendsto_pi_nhds.2 fun q => ?_)
        (tendsto_pi_nhds.2 fun q => ?_)
      · have hlim : Filter.Tendsto
            (fun p => (D.W.W q.1).W (t q.2) ω - (D.W.W q.1).W (c p) ω) Filter.atTop
            (nhds ((D.W.W q.1).W (t q.2) ω - (D.W.W q.1).W 0 ω)) :=
          tendsto_const_nhds.sub (((hcont q.1).tendsto 0).comp hc_tend)
        simpa [hzero q.1] using hlim
      · have hmono : Monotone fun p => C q.2 ∩ Set.Ioc (c p) (t q.1) ×ˢ Set.univ :=
          fun a b hab => Set.inter_subset_inter_right _
            (Set.prod_mono (Set.Ioc_subset_Ioc_left (hc_anti hab)) le_rfl)
        have hunion : ⋃ p, C q.2 ∩ Set.Ioc (c p) (t q.1) ×ˢ Set.univ
            = C q.2 ∩ Set.Ioc 0 (t q.1) ×ˢ Set.univ := by
          refine Set.Subset.antisymm (Set.iUnion_subset fun p =>
            Set.inter_subset_inter_right _
              (Set.prod_mono (Set.Ioc_subset_Ioc_left (hc_pos p).le) le_rfl)) fun x hx => ?_
          obtain ⟨p, hp⟩ := (hc_tend.eventually (eventually_lt_nhds hx.2.1.1)).exists
          exact Set.mem_iUnion.2 ⟨p, hx.1, ⟨hp, hx.2.1.2⟩, Set.mem_univ _⟩
        have := tendsto_measure_iUnion_atTop (μ := D.N.N ω) hmono
        rwa [hunion] at this
  refine (indep_of_indep_of_le_right key ?_).symm
  have hYm : Measurable[MeasurableSpace.comap Y inferInstance] Y :=
    Measurable.of_comap_le le_rfl
  refine iSup₂_le fun l hl => sup_le (iSup_le fun j => ?_) (iSup_le fun k => ?_)
  · exact ((measurable_pi_apply (j, (⟨l, hl⟩ : Fin n))).comp
      (measurable_fst.comp hYm)).comap_le
  · exact ((measurable_pi_apply ((⟨l, hl⟩ : Fin n), k)).comp
      (measurable_snd.comp hYm)).comap_le

end LevyDriver

end LevyStochCalc.Driver
