/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc.Driver.Joint
import LevyStochCalc.Poisson.IndependentScattering
import LevyStochCalc.Probability.ComapTuple
import LevyStochCalc.Probability.IndepLimit

/-!
# The Brownian increment vector of a Lévy driver

`LevyDriver.isBrownianFiltration` says that each coordinate's increment is independent of the
joint filtration. The vector of all `d` increments is a stronger statement, and it does not follow
from the coordinatewise ones by joining: the second coordinate's increment would have to be
independent of `ℱ_s ⊔ σ(ΔW¹)`, which sits inside `ℱ_t`, of which it is itself measurable. It
follows instead from the driver's own independence structure — the coordinates generate
independent σ-algebras and `σ(W) ⟂ σ(N)` — so that `σ(ΔWʲ)` is independent of the join of `Wʲ`'s
own past with *everything* the other coordinates and `N` generate.

## Main statements

* `LevyDriver.indep_incrementSigma_rest` — `σ(ΔWʲ)` against that join.
* `LevyDriver.indep_iSup_incrementSigma` — the whole increment vector against `ℱ s`.
* `LevyDriver.indep_iSup_incrementSigma_rightCont` — the same against `ℱ₊ s`.
* `LevyDriver.indep_iSup_regionSigma` — the Poisson counterpart, for the counts on a finite
  family of measurable regions lying after `s`. Arbitrary regions, not just products `(s, t] × A`:
  `sigmaPoisson` is generated by counts on all measurable subsets of `ℝ × E`.
* `LevyDriver.indep_stepSigma`, `LevyDriver.indep_stepSigma_rightCont` — the mixed tuple.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace LevyStochCalc.Driver

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω] {E : Type v} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν] {d : ℕ}

namespace LevyDriver

variable (D : LevyDriver.{u, v, w} P d ν)

/-- The σ-algebra generated by the increment of coordinate `j` over `(s, t]`. -/
noncomputable abbrev incrementSigma (j : Fin d) (s t : ℝ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω => (D.W.W j).W t ω - (D.W.W j).W s ω) inferInstance

/-- Everything the driver generates apart from the coordinate `j` itself. -/
noncomputable abbrev restSigma (j : Fin d) : MeasurableSpace Ω :=
  (⨆ i ∈ {i : Fin d | i ≠ j}, Brownian.sigmaBrownian (D.W.W i)) ⊔ sigmaPoisson D.N

theorem restSigma_le (j : Fin d) : D.restSigma j ≤ ‹MeasurableSpace Ω› :=
  sup_le (iSup₂_le fun _ _ => Brownian.sigmaBrownian_le _) (sigmaPoisson_le _)

/-- The σ-algebra of everything but coordinate `j` is independent of `σ(Wʲ)`. -/
theorem indep_restSigma (j : Fin d) :
    Indep (D.restSigma j) (Brownian.sigmaBrownian (D.W.W j)) P := by
  refine Probability.indep_sup_left_of_indep (iSup₂_le fun _ _ => Brownian.sigmaBrownian_le _)
    (sigmaPoisson_le _) (Brownian.sigmaBrownian_le _)
    (Brownian.indep_iSup_sigmaBrownian_ne D.W j) ?_
  refine indep_of_indep_of_le_right D.indep.symm (sup_le ?_ ?_)
  · exact iSup₂_le fun i _ => le_iSup (fun i => Brownian.sigmaBrownian (D.W.W i)) i
  · exact le_iSup (fun i => Brownian.sigmaBrownian (D.W.W i)) j

/-- **The increment of coordinate `j` is independent of its own past joined with everything the
other coordinates and `N` generate.** -/
theorem indep_incrementSigma_rest (j : Fin d) {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    Indep (Brownian.Martingale.naturalFiltration (D.W.W j) s ⊔ D.restSigma j)
      (D.incrementSigma j s t) P := by
  refine Probability.indep_sup_left_of_indep
    ((Brownian.naturalFiltration_le_sigmaBrownian _ s).trans (Brownian.sigmaBrownian_le _))
    (D.restSigma_le j)
    ((Brownian.comap_increment_le_sigmaBrownian _ s t).trans (Brownian.sigmaBrownian_le _))
    (Brownian.Martingale.increment_indep_naturalFiltration_aux (D.W.W j) hs hst) ?_
  exact indep_of_indep_of_le_right (D.indep_restSigma j)
    (sup_le (Brownian.naturalFiltration_le_sigmaBrownian _ s)
      (Brownian.comap_increment_le_sigmaBrownian _ s t))

/-- **The whole increment vector is independent of the joint filtration.** -/
theorem indep_iSup_incrementSigma {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    Indep (⨆ j, D.incrementSigma j s t) (D.filtration s) P := by
  classical
  have hle : ∀ j : Fin d, D.incrementSigma j s t ≤ ‹MeasurableSpace Ω› := fun j =>
    (Brownian.comap_increment_le_sigmaBrownian _ s t).trans (Brownian.sigmaBrownian_le _)
  have key : ∀ S : Finset (Fin d),
      Indep (⨆ j ∈ S, D.incrementSigma j s t) (D.filtration s) P := by
    intro S
    induction S using Finset.induction_on with
    | empty => simpa using indep_bot_left (D.filtration s)
    | insert a S ha ih =>
      have hsplit : (⨆ j ∈ insert a S, D.incrementSigma j s t)
          = (⨆ j ∈ S, D.incrementSigma j s t) ⊔ D.incrementSigma a s t := by
        rw [Finset.iSup_insert]; exact sup_comm _ _
      rw [hsplit]
      refine Probability.indep_sup_left_of_indep (iSup₂_le fun j _ => hle j) (hle a)
        (D.filtration.le s) ih ?_
      refine indep_of_indep_of_le_right
        (D.indep_incrementSigma_rest a hs hst).symm (sup_le ?_ ?_)
      · refine iSup₂_le fun j hj => le_sup_of_le_right ?_
        have hja : j ∈ {i : Fin d | i ≠ a} := by
          simp only [Set.mem_setOf_eq, ne_eq]
          rintro rfl
          exact ha hj
        exact le_sup_of_le_left (le_iSup₂_of_le j hja
          (Brownian.comap_increment_le_sigmaBrownian _ s t))
      · rw [D.filtration_apply, D.W.naturalFiltration_apply]
        refine sup_le (iSup_le fun i => ?_) ?_
        · rcases eq_or_ne i a with rfl | hia
          · exact le_sup_left
          · exact le_sup_of_le_right (le_sup_of_le_left
              (le_iSup₂_of_le i hia (Brownian.naturalFiltration_le_sigmaBrownian _ s)))
        · exact le_sup_of_le_right (le_sup_of_le_right (naturalFiltration_le_sigmaPoisson _ s))
  simpa using key Finset.univ

/-- **The increment vector is independent of the right-continuous joint filtration.** -/
theorem indep_iSup_incrementSigma_rightCont {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) :
    Indep (⨆ j, D.incrementSigma j s t) (D.filtration.rightCont s) P := by
  obtain ⟨r, -, hr_mem, hr_tend⟩ := exists_seq_strictAnti_tendsto' hst
  have hle : ∀ n, D.filtration.rightCont s ≤ D.filtration (r n) := fun n => by
    rw [Filtration.rightCont_eq_of_neBot_nhdsGT D.filtration s]
    exact iInf₂_le (r n) (hr_mem n).1
  have hmeas : ∀ u : ℝ, Measurable fun ω => fun j : Fin d => (D.W.W j).W t ω - (D.W.W j).W u ω :=
    fun u => measurable_pi_lambda _ fun j =>
      ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval u)
  have hcomap : ∀ u : ℝ,
      MeasurableSpace.comap (fun ω => fun j : Fin d => (D.W.W j).W t ω - (D.W.W j).W u ω)
          inferInstance = ⨆ j, D.incrementSigma j u t :=
    fun u => Probability.comap_pi_eq_iSup fun j ω => (D.W.W j).W t ω - (D.W.W j).W u ω
  have key : Indep (D.filtration.rightCont s)
      (MeasurableSpace.comap (fun ω => fun j : Fin d => (D.W.W j).W t ω - (D.W.W j).W s ω)
        inferInstance) P := by
    refine Probability.indep_comap_of_tendsto_ae (D.filtration.rightCont.le s)
      (X := fun n ω => fun j => (D.W.W j).W t ω - (D.W.W j).W (r n) ω)
      (fun n => hmeas (r n)) (hmeas s) (fun n => ?_) ?_
    · rw [hcomap (r n)]
      exact indep_of_indep_of_le_left
        (D.indep_iSup_incrementSigma (hs.trans (hr_mem n).1.le) (hr_mem n).2).symm (hle n)
    · filter_upwards [ae_all_iff.2 fun j : Fin d => (D.W.W j).continuous_paths] with ω hω
      exact tendsto_pi_nhds.2 fun j =>
        tendsto_const_nhds.sub (((hω j).tendsto s).comp hr_tend)
  rw [hcomap s] at key
  exact key.symm

/-- The σ-algebra generated by the count of `N` on a region. -/
noncomputable abbrev regionSigma (C : Set (ℝ × E)) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω => D.N.N ω C) inferInstance

theorem regionSigma_le {C : Set (ℝ × E)} (hC : MeasurableSet C) :
    D.regionSigma C ≤ sigmaPoisson D.N :=
  comap_count_le_sigmaPoisson D.N hC

/-- **The counts on finitely many regions after `s` are independent of the Poisson past.** -/
theorem indep_naturalFiltration_iSup_regionSigma {m : ℕ} (C : Fin m → Set (ℝ × E))
    (hCm : ∀ k, MeasurableSet (C k)) (s : ℝ) (hCs : ∀ k, C k ⊆ Set.Ioi s ×ˢ Set.univ) :
    Indep (Poisson.naturalFiltration D.N s) (⨆ k, D.regionSigma (C k)) P := by
  refine indep_of_indep_of_le_left (D.N.indep_of_disjoint_region_pair C hCm) ?_
  refine iSup₂_le fun B hB => le_iSup₂_of_le B ⟨fun k => ?_, hB.2⟩ le_rfl
  refine Set.disjoint_left.2 fun x hx hx' => ?_
  have h1 : x.1 ≤ s := (hB.1 hx).1
  have h2 : s < x.1 := (hCs k hx').1
  exact absurd h1 (not_le.2 h2)

/-- **The counts on regions after `s` are independent of everything the Brownian coordinates
generate together with the Poisson past.** -/
theorem indep_iSup_regionSigma_rest {m : ℕ} (C : Fin m → Set (ℝ × E))
    (hCm : ∀ k, MeasurableSet (C k)) (s : ℝ) (hCs : ∀ k, C k ⊆ Set.Ioi s ×ˢ Set.univ) :
    Indep (Poisson.naturalFiltration D.N s ⊔ ⨆ i, Brownian.sigmaBrownian (D.W.W i))
      (⨆ k, D.regionSigma (C k)) P :=
  Probability.indep_sup_left_of_indep
    ((naturalFiltration_le_sigmaPoisson _ s).trans (sigmaPoisson_le _))
    (iSup_le fun i => Brownian.sigmaBrownian_le (D.W.W i))
    (iSup_le fun k => (D.regionSigma_le (hCm k)).trans (sigmaPoisson_le _))
    (D.indep_naturalFiltration_iSup_regionSigma C hCm s hCs)
    (indep_of_indep_of_le_right D.indep
      (sup_le (naturalFiltration_le_sigmaPoisson _ s)
        (iSup_le fun k => D.regionSigma_le (hCm k))))

/-- **The counts on regions after `s` are independent of the joint filtration.** -/
theorem indep_iSup_regionSigma {m : ℕ} (C : Fin m → Set (ℝ × E))
    (hCm : ∀ k, MeasurableSet (C k)) (s : ℝ) (hCs : ∀ k, C k ⊆ Set.Ioi s ×ˢ Set.univ) :
    Indep (⨆ k, D.regionSigma (C k)) (D.filtration s) P := by
  refine (indep_of_indep_of_le_left (D.indep_iSup_regionSigma_rest C hCm s hCs) ?_).symm
  rw [D.filtration_apply]
  exact sup_le (le_sup_of_le_right (D.W.naturalFiltration_le_iSup_sigmaBrownian s)) le_sup_left

/-- The σ-algebra of the driver's data over one step: all `d` Brownian increments across `(s, t]`
and the counts on a finite family of regions. -/
noncomputable abbrev stepSigma {m : ℕ} (C : Fin m → Set (ℝ × E)) (s t : ℝ) :
    MeasurableSpace Ω :=
  (⨆ j, D.incrementSigma j s t) ⊔ ⨆ k, D.regionSigma (C k)

/-- **The step tuple after `s` is independent of the joint filtration.** -/
theorem indep_stepSigma {m : ℕ} (C : Fin m → Set (ℝ × E)) (hCm : ∀ k, MeasurableSet (C k))
    {s t : ℝ} (hs : 0 ≤ s) (hst : s < t) (hCs : ∀ k, C k ⊆ Set.Ioi s ×ˢ Set.univ) :
    Indep (D.stepSigma C s t) (D.filtration s) P := by
  refine Probability.indep_sup_left_of_indep
    (iSup_le fun j => (Brownian.comap_increment_le_sigmaBrownian _ s t).trans
      (Brownian.sigmaBrownian_le _))
    (iSup_le fun k => (D.regionSigma_le (hCm k)).trans (sigmaPoisson_le _))
    (D.filtration.le s) (D.indep_iSup_incrementSigma hs hst) ?_
  refine indep_of_indep_of_le_right (D.indep_iSup_regionSigma_rest C hCm s hCs).symm
    (sup_le ?_ ?_)
  · exact iSup_le fun j => le_sup_of_le_right (le_iSup_of_le j
      (Brownian.comap_increment_le_sigmaBrownian _ s t))
  · rw [D.filtration_apply]
    exact sup_le (le_sup_of_le_right (D.W.naturalFiltration_le_iSup_sigmaBrownian s)) le_sup_left

/-- **The step tuple is independent of the right-continuous joint filtration.** -/
theorem indep_stepSigma_rightCont {m : ℕ} (C : Fin m → Set (ℝ × E))
    (hCm : ∀ k, MeasurableSet (C k)) {s t : ℝ} (hs : 0 ≤ s) (hst : s < t)
    (hCs : ∀ k, C k ⊆ Set.Ioi s ×ˢ Set.univ) :
    Indep (D.stepSigma C s t) (D.filtration.rightCont s) P := by
  obtain ⟨r, hr_anti, hr_mem, hr_tend⟩ := exists_seq_strictAnti_tendsto' hst
  have hle : ∀ n, D.filtration.rightCont s ≤ D.filtration (r n) := fun n => by
    rw [Filtration.rightCont_eq_of_neBot_nhdsGT D.filtration s]
    exact iInf₂_le (r n) (hr_mem n).1
  set C' : ℕ → Fin m → Set (ℝ × E) := fun n k => C k ∩ Set.Ioi (r n) ×ˢ Set.univ with hC'
  have hC'm : ∀ n k, MeasurableSet (C' n k) := fun n k =>
    (hCm k).inter (measurableSet_Ioi.prod MeasurableSet.univ)
  have hC's : ∀ n k, C' n k ⊆ Set.Ioi (r n) ×ˢ Set.univ := fun n k => Set.inter_subset_right
  set Z : ℕ → Ω → (Fin d → ℝ) × (Fin m → ℝ≥0∞) := fun n ω =>
    (fun j => (D.W.W j).W t ω - (D.W.W j).W (r n) ω, fun k => D.N.N ω (C' n k)) with hZ
  set Y : Ω → (Fin d → ℝ) × (Fin m → ℝ≥0∞) := fun ω =>
    (fun j => (D.W.W j).W t ω - (D.W.W j).W s ω, fun k => D.N.N ω (C k)) with hY
  have hZ_meas : ∀ n, Measurable (Z n) := fun n =>
    (measurable_pi_lambda _ fun j =>
      ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval (r n))).prodMk
    (measurable_pi_lambda _ fun k => D.N.measurable_eval (hC'm n k))
  have hY_meas : Measurable Y :=
    (measurable_pi_lambda _ fun j =>
      ((D.W.W j).measurable_eval t).sub ((D.W.W j).measurable_eval s)).prodMk
    (measurable_pi_lambda _ fun k => D.N.measurable_eval (hCm k))
  have hZcomap : ∀ n, MeasurableSpace.comap (Z n) inferInstance = D.stepSigma (C' n) (r n) t := by
    intro n
    rw [hZ, Probability.comap_prod_eq_sup]
    exact congrArg₂ (· ⊔ ·)
      (Probability.comap_pi_eq_iSup fun j ω => (D.W.W j).W t ω - (D.W.W j).W (r n) ω)
      (Probability.comap_pi_eq_iSup fun k ω => D.N.N ω (C' n k))
  have hYcomap : MeasurableSpace.comap Y inferInstance = D.stepSigma C s t := by
    rw [hY, Probability.comap_prod_eq_sup]
    exact congrArg₂ (· ⊔ ·)
      (Probability.comap_pi_eq_iSup fun j ω => (D.W.W j).W t ω - (D.W.W j).W s ω)
      (Probability.comap_pi_eq_iSup fun k ω => D.N.N ω (C k))
  have key : Indep (D.filtration.rightCont s)
      (MeasurableSpace.comap Y inferInstance) P := by
    refine Probability.indep_comap_of_tendsto_ae (D.filtration.rightCont.le s)
      hZ_meas hY_meas (fun n => ?_) ?_
    · rw [hZcomap n]
      exact indep_of_indep_of_le_left
        (D.indep_stepSigma (C' n) (hC'm n) (hs.trans (hr_mem n).1.le) (hr_mem n).2
          (hC's n)).symm (hle n)
    · filter_upwards [ae_all_iff.2 fun j : Fin d => (D.W.W j).continuous_paths] with ω hω
      refine Filter.Tendsto.prodMk_nhds (tendsto_pi_nhds.2 fun j =>
        tendsto_const_nhds.sub (((hω j).tendsto s).comp hr_tend)) (tendsto_pi_nhds.2 fun k => ?_)
      have hmono : Monotone fun n => C' n k := fun a b hab =>
        Set.inter_subset_inter_right _ (Set.prod_mono (Set.Ioi_subset_Ioi (hr_anti.antitone hab))
          le_rfl)
      have hunion : ⋃ n, C' n k = C k := by
        refine Set.Subset.antisymm (Set.iUnion_subset fun n => Set.inter_subset_left) fun x hx => ?_
        obtain ⟨n, hn⟩ := (hr_tend.eventually (eventually_lt_nhds (hCs k hx).1)).exists
        exact Set.mem_iUnion.2 ⟨n, hx, hn, Set.mem_univ _⟩
      have := tendsto_measure_iUnion_atTop (μ := D.N.N ω) hmono
      rwa [hunion] at this
  rw [hYcomap] at key
  exact key.symm

end LevyDriver

end LevyStochCalc.Driver
