/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc
import NonvacuityContract

/-!
# Independent scattering on two disjoint time windows

A Poisson random measure of unit mark intensity `δ₁` on `[0, ∞) × ℝ` scatters independently: the
counts on the disjoint boxes `(0, 1] × ℝ` and `(1, 2] × ℝ` generate independent σ-algebras. Both
boxes carry reference intensity `1`, so each count vanishes with probability `exp (-1)`, neither
σ-algebra is trivial, and the two counts vanish simultaneously with probability
`exp (-1) * exp (-1)`.

## Main statements

* `referenceIntensity_stepRegion₂` — the box `(1, 2] × ℝ` has reference intensity `1` under the
  unit mark intensity, and `disjoint_stepRegion_stepRegion₂` — it is disjoint from `(0, 1] × ℝ`.
* `indep_iSup_comap_windows` and `indep_comap_windows` — the σ-algebra generated by the count on
  `(0, 1] × ℝ` is independent of the σ-algebra generated by the count on `(1, 2] × ℝ`.
* `indepFun_count_windows` — the two counts are independent random variables.
* `prob_count_stepRegion₂_eq_zero`, `comap_count_stepRegion_ne_bot` and
  `comap_count_stepRegion₂_ne_bot` — each count vanishes with probability `exp (-1)`, so neither
  of the two σ-algebras is trivial.
* `prob_count_windows_both_zero` — the two counts vanish simultaneously with probability
  `exp (-1) * exp (-1)`.
* `exists_poissonRandomMeasure_two_windows_independent` — the same statements on a probability
  space delivered by the existence theorem.

## References

* Applebaum, *Lévy Processes and Stochastic Calculus*, 2009, §2.3.
* Kallenberg, *Random Measures, Theory and Applications*, 2017, §3.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace LevyStochCalc.Examples.Nonvacuity

universe u v w

section SecondWindow

/-- The time-space box `(1, 2] × ℝ`. -/
def stepRegion₂ : Set (ℝ × ℝ) := Set.Ioc (1 : ℝ) 2 ×ˢ (Set.univ : Set ℝ)

/-- The box `(1, 2] × ℝ` is measurable. -/
theorem measurableSet_stepRegion₂ : MeasurableSet stepRegion₂ :=
  measurableSet_Ioc.prod MeasurableSet.univ

/-- The boxes `(0, 1] × ℝ` and `(1, 2] × ℝ` are disjoint. -/
theorem disjoint_stepRegion_stepRegion₂ : Disjoint stepRegion stepRegion₂ := by
  rw [Set.disjoint_left]
  rintro ⟨t, x⟩ ht ht₂
  simp only [stepRegion, stepRegion₂, Set.mem_prod, Set.mem_Ioc, Set.mem_univ,
    and_true] at ht ht₂
  exact absurd ht.2 (not_le.mpr ht₂.1)

/-- The reference intensity of the box `(1, 2] × ℝ` under the unit mark intensity is `1`. -/
theorem referenceIntensity_stepRegion₂ :
    Poisson.referenceIntensity markIntensity stepRegion₂ = 1 := by
  have hsub : Set.Ioc (1 : ℝ) 2 ⊆ Set.Ici (0 : ℝ) := fun x hx => (zero_lt_one.trans hx.1).le
  rw [stepRegion₂, Poisson.referenceIntensity, Measure.prod_prod,
    Measure.restrict_apply measurableSet_Ioc, Set.inter_eq_left.mpr hsub, Real.volume_Ioc,
    markIntensity_univ, mul_one]
  norm_num

/-- The reference intensity of the box `(1, 2] × ℝ` is finite. -/
theorem referenceIntensity_stepRegion₂_ne_top :
    Poisson.referenceIntensity markIntensity stepRegion₂ ≠ ⊤ := by
  rw [referenceIntensity_stepRegion₂]
  exact ENNReal.one_ne_top

end SecondWindow

section CountSigma

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
variable {E : Type v} [MeasurableSpace E] {ν : Measure E} [SigmaFinite ν]

/-- The event that a Poisson random measure has no point in a region belongs to the σ-algebra
generated by the count on that region. -/
theorem measurableSet_comap_count_zero (N : Poisson.PoissonRandomMeasure.{u, v, w} P ν)
    (C : Set (ℝ × E)) :
    MeasurableSet[MeasurableSpace.comap (fun ω => N.N ω C) inferInstance] {ω | N.N ω C = 0} :=
  ⟨{0}, measurableSet_singleton 0, rfl⟩

/-- The σ-algebra generated by the count on a region is nontrivial as soon as the count vanishes
with a probability different from `0` and from `1`. -/
theorem comap_count_ne_bot (N : Poisson.PoissonRandomMeasure.{u, v, w} P ν) (C : Set (ℝ × E))
    (h0 : P {ω | N.N ω C = 0} ≠ 0) (h1 : P {ω | N.N ω C = 0} ≠ 1) :
    MeasurableSpace.comap (fun ω => N.N ω C) inferInstance ≠ ⊥ := by
  intro h
  have hS := measurableSet_comap_count_zero N C
  rw [h] at hS
  rcases MeasurableSpace.measurableSet_bot_iff.mp hS with he | hu
  · exact h0 (by rw [he, measure_empty])
  · exact h1 (by rw [hu, measure_univ])

end CountSigma

section Windows

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]

/-- A Poisson random measure of unit mark intensity has no point in the box `(1, 2] × ℝ` with
probability `exp (-1)`. -/
theorem prob_count_stepRegion₂_eq_zero
    (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    P {ω | N.N ω stepRegion₂ = 0} = ENNReal.ofReal (Real.exp (-1)) := by
  rw [prob_count_eq_zero N measurableSet_stepRegion₂ referenceIntensity_stepRegion₂_ne_top,
    referenceIntensity_stepRegion₂]
  norm_num

/-- The σ-algebra generated by the count on the box `(0, 1] × ℝ` is not trivial. -/
theorem comap_count_stepRegion_ne_bot
    (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance ≠ ⊥ :=
  comap_count_ne_bot N stepRegion
    (by rw [prob_count_stepRegion_eq_zero N]; exact ofReal_exp_neg_one_ne_zero)
    (by rw [prob_count_stepRegion_eq_zero N]; exact ofReal_exp_neg_one_ne_one)

/-- The σ-algebra generated by the count on the box `(1, 2] × ℝ` is not trivial. -/
theorem comap_count_stepRegion₂_ne_bot
    (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance ≠ ⊥ :=
  comap_count_ne_bot N stepRegion₂
    (by rw [prob_count_stepRegion₂_eq_zero N]; exact ofReal_exp_neg_one_ne_zero)
    (by rw [prob_count_stepRegion₂_eq_zero N]; exact ofReal_exp_neg_one_ne_one)

/-- The σ-algebra generated by the counts on the one-element family `(0, 1] × ℝ` is independent
of the σ-algebra generated by the count on `(1, 2] × ℝ`. -/
theorem indep_iSup_comap_windows
    (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    Indep (⨆ _i : Fin 1, MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance)
      (MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance) P :=
  N.indep_iSup_comap_of_disjoint measurableSet_stepRegion₂ (fun _ : Fin 1 => stepRegion)
    (fun _ => measurableSet_stepRegion) (fun _ => disjoint_stepRegion_stepRegion₂)

/-- The σ-algebra generated by the count on the box `(0, 1] × ℝ` is independent of the σ-algebra
generated by the count on the box `(1, 2] × ℝ`. -/
theorem indep_comap_windows (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    Indep (MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance)
      (MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance) P := by
  have h := indep_iSup_comap_windows N
  rwa [iSup_const] at h

/-- The counts on the boxes `(0, 1] × ℝ` and `(1, 2] × ℝ` are independent random variables. -/
theorem indepFun_count_windows (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    IndepFun (fun ω => N.N ω stepRegion) (fun ω => N.N ω stepRegion₂) P :=
  (IndepFun_iff_Indep _ _ _).mpr (indep_comap_windows N)

/-- A Poisson random measure of unit mark intensity has no point in either of the boxes
`(0, 1] × ℝ` and `(1, 2] × ℝ` with probability `exp (-1) * exp (-1)`. -/
theorem prob_count_windows_both_zero
    (N : Poisson.PoissonRandomMeasure.{u, 0, w} P markIntensity) :
    P {ω | N.N ω stepRegion = 0 ∧ N.N ω stepRegion₂ = 0}
      = ENNReal.ofReal (Real.exp (-1)) * ENNReal.ofReal (Real.exp (-1)) := by
  have hset : {ω | N.N ω stepRegion = 0 ∧ N.N ω stepRegion₂ = 0}
      = (fun ω => N.N ω stepRegion) ⁻¹' {0} ∩ (fun ω => N.N ω stepRegion₂) ⁻¹' {0} := rfl
  have h1 : P ((fun ω => N.N ω stepRegion) ⁻¹' {0}) = ENNReal.ofReal (Real.exp (-1)) :=
    prob_count_stepRegion_eq_zero N
  have h2 : P ((fun ω => N.N ω stepRegion₂) ⁻¹' {0}) = ENNReal.ofReal (Real.exp (-1)) :=
    prob_count_stepRegion₂_eq_zero N
  rw [hset, (indepFun_count_windows N).measure_inter_preimage_eq_mul _ _
    (measurableSet_singleton 0) (measurableSet_singleton 0), h1, h2]

end Windows

section Existence

/-- Some probability space carries a Poisson random measure of unit mark intensity whose counts
on the boxes `(0, 1] × ℝ` and `(1, 2] × ℝ` generate independent nontrivial σ-algebras and vanish
simultaneously with probability `exp (-1) * exp (-1)`. -/
theorem exists_poissonRandomMeasure_two_windows_independent :
    ∃ (Ω : Type) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P)
      (N : Poisson.PoissonRandomMeasure P markIntensity),
      Indep (⨆ _i : Fin 1, MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance)
          (MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance) P ∧
        Indep (MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance)
          (MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance) P ∧
        MeasurableSpace.comap (fun ω => N.N ω stepRegion) inferInstance ≠ ⊥ ∧
        MeasurableSpace.comap (fun ω => N.N ω stepRegion₂) inferInstance ≠ ⊥ ∧
        P {ω | N.N ω stepRegion = 0 ∧ N.N ω stepRegion₂ = 0}
          = ENNReal.ofReal (Real.exp (-1)) * ENNReal.ofReal (Real.exp (-1)) := by
  obtain ⟨Ω, _, P, _, ⟨N⟩⟩ := Poisson.PoissonRandomMeasure.exists_of_sigmaFinite ℝ markIntensity
  exact ⟨Ω, inferInstance, P, inferInstance, N, indep_iSup_comap_windows N,
    indep_comap_windows N, comap_count_stepRegion_ne_bot N, comap_count_stepRegion₂_ne_bot N,
    prob_count_windows_both_zero N⟩

end Existence

end LevyStochCalc.Examples.Nonvacuity
