/-
Copyright (c) 2026 Christian Garry. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Garry
-/
import LevyStochCalc
import NonvacuityContract

/-!
# The two coordinates of a Brownian motion in the plane

The two coordinates of a Brownian motion in the plane generate independent σ-algebras, each
different from the trivial one, and their increments over `(0, 1]` form a pair whose σ-algebra is
the join of the two increment σ-algebras and is generated by neither increment alone.

## Main statements

* `measure_eq_zero_or_one_of_indep_self` and `not_indep_self_of_measure_eq_half` — a σ-algebra
  independent of itself carries only events of probability `0` or `1`.
* `iSup_sigmaBrownian_ne_zero` — for two coordinates the join over the coordinates other than `0`
  is the σ-algebra of the coordinate `1`, whence `indep_sigmaBrownian_one_zero`.
* `indepFun_coordIncrement` — the increments of the two coordinates over `(0, 1]` are
  independent, of variance `1` each (`variance_coordIncrement`) and generating σ-algebras
  different from the trivial one (`comap_coordIncrement_ne_bot`).
* `comap_coordIncrementTuple` — the σ-algebra of the pair of increments is the join of the two
  increment σ-algebras; it differs from the trivial σ-algebra
  (`comap_coordIncrementTuple_ne_bot`) and from the σ-algebra of the coordinate `0` alone
  (`not_comap_coordIncrement_le`).
* `exists_multidimBrownian_two_coordinates_nontrivial` — the same statements on a probability
  space delivered by the existence theorem.

## References

* Karatzas–Shreve, *Brownian Motion and Stochastic Calculus*, 1991, §2.5.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace LevyStochCalc.Examples.Nonvacuity

open Brownian.Multidim (MultidimBrownianMotion)

universe u

section SelfIndependence

variable {Ω : Type u} {mΩ : MeasurableSpace Ω} {P : Measure Ω} [IsProbabilityMeasure P]

/-- An event of a σ-algebra independent of itself has probability `0` or `1`. -/
theorem measure_eq_zero_or_one_of_indep_self {m : MeasurableSpace Ω} (h : Indep m m P)
    {A : Set Ω} (hA : MeasurableSet[m] A) : P A = 0 ∨ P A = 1 := by
  have hmul : P (A ∩ A) = P A * P A := (Indep_iff m m P).mp h A A hA hA
  rw [Set.inter_self] at hmul
  by_cases h0 : P A = 0
  · exact Or.inl h0
  · exact Or.inr ((ENNReal.mul_eq_left h0 (measure_ne_top P A)).mp hmul.symm)

/-- A σ-algebra carrying an event of probability `1 / 2` is not independent of itself. -/
theorem not_indep_self_of_measure_eq_half {m : MeasurableSpace Ω} {A : Set Ω}
    (hA : MeasurableSet[m] A) (hP : P A = 1 / 2) : ¬ Indep m m P := by
  intro h
  rcases measure_eq_zero_or_one_of_indep_self h hA with h0 | h1
  · rw [h0, one_div] at hP
    exact (ENNReal.inv_ne_zero.mpr (by norm_num : (2 : ℝ≥0∞) ≠ ⊤)) hP.symm
  · rw [h1, one_div, eq_comm, ENNReal.inv_eq_one] at hP
    norm_num at hP

end SelfIndependence

section TwoCoordinates

variable {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
variable (W : MultidimBrownianMotion P 2)

/-- The indices of `Fin 2` other than `0` form the singleton `{1}`. -/
theorem setOf_ne_zero_fin_two : {i : Fin 2 | i ≠ 0} = {1} := by
  ext i
  fin_cases i <;> simp

/-- For a Brownian motion in the plane the coordinates other than `0` generate the σ-algebra of
the coordinate `1`. -/
theorem iSup_sigmaBrownian_ne_zero :
    (⨆ i ∈ {i : Fin 2 | i ≠ 0}, Brownian.sigmaBrownian (W.W i))
      = Brownian.sigmaBrownian (W.W 1) := by
  rw [setOf_ne_zero_fin_two]
  exact iSup_singleton

/-- The σ-algebra of the coordinate `1` of a Brownian motion in the plane is independent of the
σ-algebra of the coordinate `0`. -/
theorem indep_sigmaBrownian_one_zero :
    Indep (Brownian.sigmaBrownian (W.W 1)) (Brownian.sigmaBrownian (W.W 0)) P := by
  have h := Brownian.indep_iSup_sigmaBrownian_ne W 0
  rwa [iSup_sigmaBrownian_ne_zero W] at h

/-- The increment of a coordinate of a Brownian motion in the plane over `(0, 1]`. -/
def coordIncrement (i : Fin 2) : Ω → ℝ := fun ω => (W.W i).W 1 ω - (W.W i).W 0 ω

/-- The σ-algebra generated by the increment of a coordinate over `(0, 1]` sits inside the
σ-algebra generated by that coordinate. -/
theorem comap_coordIncrement_le (i : Fin 2) :
    MeasurableSpace.comap (coordIncrement W i) inferInstance ≤ Brownian.sigmaBrownian (W.W i) :=
  Brownian.comap_increment_le_sigmaBrownian (W.W i) 0 1

/-- The increments over `(0, 1]` of the two coordinates of a Brownian motion in the plane are
independent. -/
theorem indepFun_coordIncrement : IndepFun (coordIncrement W 1) (coordIncrement W 0) P :=
  (IndepFun_iff_Indep _ _ _).mpr
    (indep_of_indep_of_le (indep_sigmaBrownian_one_zero W) (comap_coordIncrement_le W 1)
      (comap_coordIncrement_le W 0))

/-- The increment of a coordinate of a Brownian motion in the plane over `(0, 1]` has variance
`1`. -/
theorem variance_coordIncrement (i : Fin 2) :
    Var[fun x : ℝ => x; P.map (coordIncrement W i)] = 1 :=
  variance_increment_unit (W.W i)

/-- The probability that the increment of a coordinate of a Brownian motion in the plane over
`(0, 1]` is positive is `1 / 2`. -/
theorem prob_coordIncrement_pos (i : Fin 2) : P {ω | 0 < coordIncrement W i ω} = 1 / 2 :=
  prob_increment_unit_pos (W.W i)

/-- The event that the increment of a coordinate of a Brownian motion in the plane over `(0, 1]`
is positive belongs to the σ-algebra that increment generates. -/
theorem measurableSet_coordIncrement_pos (i : Fin 2) :
    MeasurableSet[MeasurableSpace.comap (coordIncrement W i) inferInstance]
      {ω | 0 < coordIncrement W i ω} :=
  measurableSet_increment_unit_pos (W.W i)

/-- The σ-algebra generated by the increment of a coordinate of a Brownian motion in the plane
over `(0, 1]` is not trivial. -/
theorem comap_coordIncrement_ne_bot (i : Fin 2) :
    MeasurableSpace.comap (coordIncrement W i) inferInstance ≠ ⊥ :=
  comap_increment_unit_ne_bot (W.W i)

/-- The pair of increments over `(0, 1]` of the two coordinates of a Brownian motion in the
plane. -/
def coordIncrementTuple : Ω → Fin 2 → ℝ := fun ω i => coordIncrement W i ω

/-- The σ-algebra generated by the pair of increments over `(0, 1]` is the join of the σ-algebras
generated by the two increments. -/
theorem comap_coordIncrementTuple :
    MeasurableSpace.comap (coordIncrementTuple W) MeasurableSpace.pi
      = ⨆ i, MeasurableSpace.comap (coordIncrement W i) inferInstance :=
  Probability.comap_pi_eq_iSup (coordIncrement W)

/-- The σ-algebra generated by the pair of increments over `(0, 1]` of a Brownian motion in the
plane is not trivial. -/
theorem comap_coordIncrementTuple_ne_bot :
    MeasurableSpace.comap (coordIncrementTuple W) MeasurableSpace.pi ≠ ⊥ := by
  rw [comap_coordIncrementTuple W]
  intro h
  refine comap_coordIncrement_ne_bot W 0 (le_bot_iff.mp ?_)
  rw [← h]
  exact le_iSup (fun i : Fin 2 => MeasurableSpace.comap (coordIncrement W i) inferInstance) 0

/-- The σ-algebra generated by the increment of the coordinate `1` of a Brownian motion in the
plane over `(0, 1]` is not contained in the one generated by the increment of the coordinate
`0`. -/
theorem not_comap_coordIncrement_le :
    ¬ MeasurableSpace.comap (coordIncrement W 1) inferInstance
        ≤ MeasurableSpace.comap (coordIncrement W 0) inferInstance := by
  intro hle
  refine not_indep_self_of_measure_eq_half (measurableSet_coordIncrement_pos W 1)
    (prob_coordIncrement_pos W 1) ?_
  exact indep_of_indep_of_le_right ((IndepFun_iff_Indep _ _ _).mp (indepFun_coordIncrement W)) hle

end TwoCoordinates

section Existence

/-- Some probability space carries a Brownian motion in the plane whose coordinate σ-algebras are
independent and differ from the trivial σ-algebra, whose coordinate increments over `(0, 1]` are
independent of variance `1`, and whose pair of increments generates the join of the two increment
σ-algebras, a σ-algebra that differs from the trivial one and from the σ-algebra of the
coordinate `0` alone. -/
theorem exists_multidimBrownian_two_coordinates_nontrivial :
    ∃ (Ω : Type) (_ : MeasurableSpace Ω) (P : Measure Ω) (_ : IsProbabilityMeasure P)
      (W : MultidimBrownianMotion P 2),
      Indep (⨆ i ∈ {i : Fin 2 | i ≠ 0}, Brownian.sigmaBrownian (W.W i))
          (Brownian.sigmaBrownian (W.W 0)) P ∧
        Brownian.sigmaBrownian (W.W 0) ≠ ⊥ ∧
        Brownian.sigmaBrownian (W.W 1) ≠ ⊥ ∧
        IndepFun (coordIncrement W 1) (coordIncrement W 0) P ∧
        (∀ i : Fin 2, Var[fun x : ℝ => x; P.map (coordIncrement W i)] = 1) ∧
        MeasurableSpace.comap (coordIncrementTuple W) MeasurableSpace.pi
            = ⨆ i, MeasurableSpace.comap (coordIncrement W i) inferInstance ∧
        MeasurableSpace.comap (coordIncrementTuple W) MeasurableSpace.pi ≠ ⊥ ∧
        ¬ MeasurableSpace.comap (coordIncrement W 1) inferInstance
            ≤ MeasurableSpace.comap (coordIncrement W 0) inferInstance := by
  obtain ⟨Ω, _, P, _, ⟨W⟩⟩ := MultidimBrownianMotion.exists.{0} 2
  exact ⟨Ω, inferInstance, P, inferInstance, W, Brownian.indep_iSup_sigmaBrownian_ne W 0,
    sigmaBrownian_ne_bot (W.W 0), sigmaBrownian_ne_bot (W.W 1), indepFun_coordIncrement W,
    fun i => variance_coordIncrement W i, comap_coordIncrementTuple W,
    comap_coordIncrementTuple_ne_bot W, not_comap_coordIncrement_le W⟩

end Existence

end LevyStochCalc.Examples.Nonvacuity
